### ISSUE TITLE
N neighbors in knn with GlobalEmbeddingSpaceTester

### ISSUE THREAD

**Issue by rproskuryakov** [KevinMusgrave/pytorch-metric-learning#114]
Hello, I've read the docs but didn't found how to set n neighbors, with my data this value is set to 728 automatically and I can`t properly calculate metrics. Is there a way to set n neighbors manually?

**Comment by KevinMusgrave** [comment]
@rproskuryakov I've made a change which you can access in 0.9.87.dev3:
```
pip install pytorch-metric-learning=0.9.87.dev3
```

Example:
```python
# For versions >= 0.9.87.dev0, you have to import from utils.accuracy_calculator
# In prior versions you could import directly from utils
from pytorch_metric_learning.utils.accuracy_calculator import AccuracyCalculator
from pytorch_metric_learning.testers import GlobalEmbeddingSpaceTester

AC = AccuracyCalculator(k=100)
T = GlobalEmbeddingSpaceTester(accuracy_calculator=AC)
```

A couple things to note:
- The default knn accuracy metrics ```mean_average_precision_at_r``` and ```r_precision``` only really make sense when k is automatically determined. If you have a custom accuracy metric you want to implement, then you can extend AccuracyCalculator. See the [documentation](https://kevinmusgrave.github.io/pytorch-metric-learning/utils/#accuracycalculator)
- knn is done using faiss, and faiss has a limitation of either 1024 or 2048 nearest neighbors, depending on your version of cuda: https://github.com/facebookresearch/faiss/issues/1032

Let me know if that helps.
