### ISSUE TITLE
Question about MAP@R

### ISSUE THREAD

**Issue by zgpio** [KevinMusgrave/pytorch-metric-learning#116]
> R-Precision is defined as follows: for each sample, determine the number of
other samples, R, that are of the same class. Find the R nearest neighbors,
and count the number, r, that are the same class as the sample.

As far as I know, R is a variable for each evaluation sample, because the number of neighbors for each evaluation sample in the dataset is inconsistent, but in the experimental code, it seems to be a fixed value, e.g. k-nn with k=60.

**Comment by KevinMusgrave** [comment]
Yeah for the k-nn search using faiss, I set k to the maximum necessary. For example, if there are 3 classes, and there "R" values are [3,30,300], then I'll set k to 300. (As far as I know, you have to use one value of k for the whole matrix.)

After k-nn, I create a ["relevance mask" for each row](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/src/pytorch_metric_learning/utils/accuracy_calculator.py#L17), and use that to determine the denominator for R-precision and MAP@R.

**Comment by zgpio** [comment]
Thank you for your quick reply, I understand now, this is the best open source code in the field of metric learning.

**Comment by KevinMusgrave** [comment]
Thanks! 😄
