### ISSUE TITLE
How to train on my own dataset?

### ISSUE THREAD

**Issue by Moonteresa** [KevinMusgrave/pytorch-metric-learning#117]
when I change datasets.CIFAR100 to datasets.Imagefolder and other codes related to data, error occered "TypeError: "Compose" object is not iterable" in function Compose()  in transform.py
Is there any way to train on my own dataset? Thanks very much !

**Comment by KevinMusgrave** [comment]
Hmm, it sounds like there's a problem with either the way you're setting up the dataset or the transform. Can you paste in some of your code, or the full error?

**Comment by Moonteresa** [comment]
Thanks for your kindly reply! The above question was solved as you said!
When testing models, can I use some funtions in your lib to match a query in my gallery?(I see "InferenceModel.get_embeddings")

**Comment by KevinMusgrave** [comment]
Check out the [example notebook for inference](https://colab.research.google.com/github/KevinMusgrave/pytorch-metric-learning/blob/master/examples/notebooks/Inference.ipynb).

It's a brand new module (requires version 0.9.87.dev2 or higher), so let me know if you have any suggestions to improve it.

**Comment by KevinMusgrave** [comment]
Closing for now. Please reopen if you have further questions.

**Comment by Moonteresa** [comment]
Sorry to ask another question about "how to combine two weights(trunk.pth&embedding.pth) into a single weight?" Cause I want to transform the model to other Deep learning framework, could you please kindly give some advice?

**Comment by KevinMusgrave** [comment]
You could load the trunk and embedder weights, then create a wrapper module, and save its weights:
```python
import torch

class CombinedModel(torch.nn.Module):
    def __init__(self, trunk, embedder):
        self.trunk = trunk
        self.embedder = embedder

    def forward(self, x):
        return self.embedder(self.trunk(x))


# after you've loaded the trunk and embedder weights:
model = CombinedModel(trunk, embedder)
torch.save(model.state_dict(), filepath)
```

**Comment by Moonteresa** [comment]
Thank you so much for your code! It works well in my case. Thanks for your work ,it helps me a lot!^-^
