### ISSUE TITLE
Label as string not working

### ISSUE THREAD

**Issue by StefanMojsilovic** [KevinMusgrave/pytorch-metric-learning#16]
My dataset returns an image as torch.Tensor and a label as string: 
`return image, label`

Using the code similar to example_MetricLossOnly.py with my dataset produces the following error:

 File "/opt/conda/lib/python3.6/site-packages/pytorch_metric_learning/utils/common_functions.py", line 51, in map_labels
    if labels.ndim == 2:
AttributeError: 'tuple' object has no attribute 'ndim'

The error can be fixed by encoding the labels to integers in range(0, n_labels). I have also tried turning the label to tensor and to numpy array but with no success.

However, I would like to be able to work with string labels directly.

**Comment by KevinMusgrave** [comment]
@StefanMojsilovic In version 0.9.77 you can use label strings with the trainers and testers. Here's how:

```python
# Get all the string labels of your dataset. This can be a list or np.array.
all_string_labels = your_dataset.labels  

# When you create your trainer, set the following arguments
trainer = trainers.MetricLossOnly(..., 
    dataset_labels=all_string_labels,
    set_min_label_to_zero=True
)

# Same with testers
tester = testers.GlobalEmbeddingSpaceTester(..., 
    dataset_labels=all_string_labels,
    set_min_label_to_zero=True
)
```

Now when your dataset returns a string label, it will be converted to a unique integer, which represents the string label's alphabetical rank among the set of labels.

Hope that works for you!
