### ISSUE TITLE
CPU support

### ISSUE THREAD

**Issue by konstantinkobs** [KevinMusgrave/pytorch-metric-learning#160]
Hey, thanks for this library!

At installation time, the library wants to install faiss-gpu, which presumably needs a compatible GPU. On my development notebook, I get an error when faiss-gpu should be installed and the library gets not installed successfully.
I now want to ask, if there are any plans to modify this library to make it work on CPUs, so I can use it locally until I run the final product on the server with a dedicated GPU.

Maybe this is trivial by just replacing the faiss-gpu requirement with the faiss-cpu library, but maybe there are other places in the code where an Nvidia GPU is required for this library to function.

Thank you very much and have a great week!

**Comment by KevinMusgrave** [comment]
If you install faiss-cpu it should work. I believe the rest of the code should work on gpu or cpu.

**Comment by konstantinkobs** [comment]
Indeed, it does work, when I switch faiss-gpu with faiss-cpu. 🎉 

Thank you!

**Comment by KevinMusgrave** [comment]
Good point, but actually, faiss isn't part of the install requirements. Specifically:

1. This will not install faiss
```
pip install pytorch-metric-learning
```

2. This will install with faiss-gpu 
```
pip install pytorch-metric-learning[with-hooks]
```

3. This will install with faiss-cpu
```
pip install pytorch-metric-learning[with-hooks-cpu]
```

In the example notebooks, faiss-gpu is installed as a separate command, but that can be easily replaced.
