### ISSUE TITLE
lr_scheduler object has no attribute 'parameters'

### ISSUE THREAD

**Issue by StefanMojsilovic** [KevinMusgrave/pytorch-metric-learning#17]
Using one of the torch.optim.lr_schedulers object with the example codes produces the following error:

 File "/opt/conda/lib/python3.6/site-packages/pytorch_metric_learning/utils/common_functions.py", line 235, in operate_on_dict_of_models
    if opt_cond or len([i for i in v.parameters()]) > 0:
AttributeError: 'StepLR' object has no attribute 'parameters'

The error can be quick-fixed by subclassing the desired lr_scheduler and wrapping the state_dict() function by the parameters() function.

However, this will later conflict with the base_trainer when using ReduceLROnPlateau since it will no longer be a part of the torch.optim module.

This can be further fixed by replacing the base_trainer with your own, etc. However, this is not the desired behavior.

**Comment by KevinMusgrave** [comment]
I'll get rid of that if-statement, and instead wrap the "save_model" call with a try block.

**Comment by KevinMusgrave** [comment]
@StefanMojsilovic This is fixed in the latest version, 0.9.76
