### ISSUE TITLE
NUMPY_RANDOM_STATE breaks reproducibility

### ISSUE THREAD

**Issue by WeirdKeksButtonK** [KevinMusgrave/pytorch-metric-learning#18]
Hi! This line...
https://github.com/KevinMusgrave/pytorch-metric-learning/blob/28d640ffc080044c76e736a1d8836a8ccb55fd65/pytorch_metric_learning/utils/common_functions.py#L9
breaks the effect of the following conventional approach...
```python
np.random.seed(my_seed)
``` 
... and forces users to do the following in order to write reproducible code:
```python
import pytorch_metric_learning.utils.common_functions as tmp
tmp.NUMPY_RANDOM_STATE = np.random.RandomState(my_seed)
```
I would suggest replacing all usages of `NUMPY_RANDOM_STATE`'s methods with analogous functions from the module `np.random`. It will make the library's code both simpler and easier-to-make-reproducible.

**Comment by KevinMusgrave** [comment]
I could make ```np.random``` the default, but have a flag in the init file which allows users to switch to the RandomState version. So at the top of common_functions:
```python
from .. import USE_NUMPY_RANDOM_STATE
import numpy as np
NUMPY_RANDOM = np.random.RandomState() if USE_NUMPY_RANDOM_STATE else np.random
```

And in the top level init file:
```python
__version__ = "0.9.75"
USE_NUMPY_RANDOM_STATE = False
```

Then for users:
```python
# If you want to use RandomState
# Do this before any other imports
import pytorch_metric_learning
pytorch_metric_learning.USE_NUMPY_RANDOM_STATE = True
```
What do you think?

**Comment by WeirdKeksButtonK** [comment]
I'm definitely in favor of making `np.random` the default approach. In this case I will be (hopefully) the last person to debug reproducibility 😃 
As for `NUMPY_RANDOM_STATE`, I don't understand how it can be useful. If you think it is worth supporting it, some flag is fine (personally, I would prefer a private flag and public setter and getter).

**Comment by KevinMusgrave** [comment]
I believe using RandomState() is the same as using np.random.seed() with a random seed, so I don't have to generate a random seed myself. So it's mainly for convenience.

**Comment by KevinMusgrave** [comment]
@WeirdKeksButtonK In the latest version (0.9.76), NUMPY_RANDOM = np.random(). I didn't bother adding a flag for setting it to random state, as it can be set directly if desired.
