### ISSUE TITLE
how can i visualize the mined triplets?

### ISSUE THREAD

**Issue by lolongcovas** [KevinMusgrave/pytorch-metric-learning#183]
how can i visualize the mined triplets? or how can i get the mined triplets?

**Comment by KevinMusgrave** [comment]
Can you be more specific? Are you using one of the triplet miners? These mine triplets at every iteration. Do you want to see the images of these mined triplets, or do you mean something like a t-SNE or UMAP plot?

**Comment by lolongcovas** [comment]
Sorry about too generic question. Yes, you are right, I am using one of the triplet miners (but can be whatever miner of this repo). The objective is visualizing the images of these mined triplets, but I guess the miners only returns the index of my dataset (for instance the class label index). As extra, if it is possible to visualize the images in 3D space with t-SNE directly using this framework, otherwise it will be done with tensorboard.

Thanks

**Comment by KevinMusgrave** [comment]
There isn't a built in way to do this, so you'll have to extract the images based on the mined indices. Also, the indices are per batch, not for the entire dataset.

**Comment by KevinMusgrave** [comment]
To elaborate: this library doesn't have offline miners yet. So the available miners work per batch, and therefore the indices they return are within batch indices. 

If you're working with a triplet miner, its output will be a tuple, ```(anchors, positives, negatives)```, where ```anchors```, ```positives```, ```negatives``` are each 1d tensors of indices.

**Comment by KevinMusgrave** [comment]
Closing for now, please re-open if you have further questions
