### ISSUE TITLE
Make it possible to run the unit tests on CPU

### ISSUE THREAD

**Issue by bcdarwin** [KevinMusgrave/pytorch-metric-learning#184]
The tests hard-code the following:

```
    def setUpClass(self):
        self.device = torch.device('cuda')
```

Thus, they can't be run on the CPU, and, in particular, running without a GPU/CUDA stack available will cause them to error.

**Comment by KevinMusgrave** [comment]
I could make a ```DEVICE``` variable in ```tests/__init__.py``` that can be set to GPU or CPU, and then all the tests import that variable. That would get rid of a lot of redundancy too.

**Comment by bcdarwin** [comment]
I guess you could either get this from an environment variable via `os.getenv` or from the command line as in described [here](https://docs.pytest.org/en/latest/example/simple.html)?

**Comment by KevinMusgrave** [comment]
You can now specify cuda or cpu, as well as the data types to test on. For example:

```
TEST_DTYPES=float32,float64 TEST_DEVICE=cpu python -m unittest discover
```
