### ISSUE TITLE
SUGGESTION: Default margin values of ContrastiveLoss

### ISSUE THREAD

**Issue by JoOkuma** [KevinMusgrave/pytorch-metric-learning#19]
The default margin values of `ContrastiveLoss` are not appropriate when `use_similarity` is `True`. 

Currently, the loss is like this with the default values:

* Dissimilarity:
<img src="https://latex.codecogs.com/gif.latex?$L&space;=&space;\[d_{pos}&space;-&space;0\]_&plus;&space;&plus;&space;[1&space;-&space;d_{neg}]_&plus;$" title="$L = \[d_{pos} - 0\]_+ + [1 - d_{neg}]_+$" />

* Similarity:
<img src="https://latex.codecogs.com/gif.latex?$L&space;=&space;\[0&space;-&space;d_{pos}\]_&plus;&space;&plus;&space;[d_{neg}&space;-&space;1]_&plus;$" title="$L = \[0 - d_{pos}\]_+ + [d_{neg} - 1]_+$" />

In the dissimilarity case, it works correctly.

However, the similarity is not correct; the first term will only penalize if the positive similarity is negative, which does not happen in most cases because the embedding is after a ReLU layer, resulting in only positive inner products. The second term is never penalized if the embedding is normalized because the dot product is at most 1.

I'm not sure if this needs changes in the code itself, but I think it should be in the documentation that the default values are not appropriate for this case.

One solution would be to switch the margins when the similarity is used, but this might generate some confusion.

Also, I think it would be appreciated if the formulas were added to the documentation.

**Comment by KevinMusgrave** [comment]
You're right the default margins aren't appropriate if ```use_similarity=True```. Like you said, I think adding a note to the documentation is the best solution here.

**Comment by KevinMusgrave** [comment]
I added this to the documentation [here](https://kevinmusgrave.github.io/pytorch-metric-learning/losses/#contrastiveloss)

**Comment by KevinMusgrave** [comment]
I haven't added equations since that's a more complicated task. I'll need to check out how to display equations in mkdocs.
