### ISSUE TITLE
Ranked List Loss (RLL) implementation

### ISSUE THREAD

**Issue by say2sarwar** [KevinMusgrave/pytorch-metric-learning#191]
Do you have any plans to implement RLL in this DML?

**Comment by KevinMusgrave** [comment]
Link to [paper](https://arxiv.org/pdf/1903.03238.pdf) as mentioned [here](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/285)

**Comment by KevinMusgrave** [comment]
Added by @domenicoMuscill0 in v2.4.0:

```
pip install pytorch-metric-learning==2.4.0
```
