### ISSUE TITLE
SNR and Euclidean distances

### ISSUE THREAD

**Issue by Ali-692** [KevinMusgrave/pytorch-metric-learning#198]
Hi,
I am new to metric learning. I am interested to see the results of TripletMarginLoss under the SNR and Euclidean distances. In the SNR paper (Signal-to-Noise Ratio: A Robust Distance Metric for Deep Metric Learning), they showed that SNR incorporated TripletMarginLoss has superior performance compared to the Euclidean distance; however, I did not see the difference in pytorch metric learning library.  

I am using the cars dataset, with embedding size of 16, batch size 100, model bn_inception, optimizer sgd (similar as SNR paper). Could anyone help me where is the problem or these distances respective settings. Thanks in advance.

**Comment by KevinMusgrave** [comment]
Closing this issue for now. If anyone has ideas feel free to chime in

**Comment by deividbotina-alv** [comment]
Hello,
I don't know if the problem was solved but I think the following links may help:
https://github.com/KevinMusgrave/pytorch-metric-learning
https://kevinmusgrave.github.io/pytorch-metric-learning/distances/#snrdistance
