### ISSUE TITLE
Pytorch pip dependence

### ISSUE THREAD

**Issue by marued** [KevinMusgrave/pytorch-metric-learning#199]
Is it possible to remove the Pytorch prerequisite when installing the package? Pytorch can be installed multiple ways on a system and it's possible that _pip_ is not aware of it. For example, if you install it through anaconda or build your own version. 

Specifying the minimal version in the README or in documentation should be enough and less limiting at install time.

**Comment by KevinMusgrave** [comment]
Hmm, what about using the ```--no-deps``` flag?
```
pip install --no-deps pytorch-metric-learning
```

**Comment by marued** [comment]
well... why did I not think of that. Thanks!

**Comment by marued** [comment]
Actually, the only down side of this solution is when you want to add pytorch-metric-learning in your requirement.txt file. In that case, it's not possible to add the option --no-deps in the file.

**Comment by KevinMusgrave** [comment]
Hmm, this might be unorthodox, but for each pip release, I could have a separate version with no dependencies, like v0.9.92.no_deps
