### ISSUE TITLE
What is the recommended miner for NCA loss

### ISSUE THREAD

**Issue by zitongzhan** [KevinMusgrave/pytorch-metric-learning#201]
since NCA loss usually needs the following form:
```
(
one anchor sample,
n * positive sample,
m * negative sample,
)
```
This is similar to the Triplet miner, except that it requires n * positive sample and m * negative sample. Do you have any suggestion? Thanks in advance!

**Comment by KevinMusgrave** [comment]
I haven't tried any miners with NCALoss. Maybe someone else might have suggestions, so I'll leave this issue open for now.

You might also be interested in applying passing a reducer to NCALoss: https://kevinmusgrave.github.io/pytorch-metric-learning/reducers/

**Comment by KevinMusgrave** [comment]
Closing this issue for now. If anyone has ideas feel free to chime in
