### ISSUE TITLE
Huge memory consumption using NT-Xent loss

### ISSUE THREAD

**Issue by NCTU-VRDL** [KevinMusgrave/pytorch-metric-learning#203]
Hi, Thanks for the great tools for metric-learning!

I am using the NT-Xent loss with a large batch, however, it seems that it require lots of memory. Is there anyway to reduce the memory usage? Thank you!

Code for reproducing OOM error. I want to use the 256 positive sample to group the positive paris and 256 negative samples for negative paris
```python
nxt_loss = NTXentLoss(temperature=0.5)

pos_pair = torch.randn(256, 128).cuda()
neg_pair = torch.randn(256, 128).cuda()

embeddings = torch.cat([pos_pair, neg_pair], dim=0)

labels = torch.cat([torch.zeros(pos_pair.shape[0]),
                    torch.arange(1, embeddings.shape[0]-pos_pair.shape[0]+1)]).long().cuda()
point_loss = nxt_loss(embeddings, labels) 
```
```
RuntimeError: CUDA out of memory. Tried to allocate 11.94 GiB
```

**Comment by KevinMusgrave** [comment]
It's running out of memory because there are a lot more than 256 positive pairs and 256 negative pairs based on the labels. Actually, there are 256*255 = 65280 positive pairs, and 256*256*2 = 131072 negative pairs. 

To reduce the number of pairs, you can pass in a tuple of indices to the loss function. But it's not clear to me how your embeddings are shaped. You say ```pos_pair``` consists of 256 positive pairs, but it only contains 256 elements. "256 pairs" implies there should be 512 elements. Can you clarify what ```embeddings``` contains?

**Comment by NCTU-VRDL** [comment]
Hi @KevinMusgrave!

Thanks for your reply. Sorry for the confusion, you're right for the number of the positive pairs and negative pairs of my need.

So it looks like I need a random sample indices to solve this issue, is that correct? Thank you!

**Comment by KevinMusgrave** [comment]
Yeah, this is probably the best way to do it:

```python
nxt_loss = NTXentLoss(temperature=0.5)

pos_pair = torch.randn(256, 128).cuda()
neg_pair = torch.randn(256, 128).cuda()

embeddings = torch.cat([pos_pair, neg_pair], dim=0)

labels = torch.cat([torch.zeros(pos_pair.shape[0]),
                    torch.arange(1, embeddings.shape[0]-pos_pair.shape[0]+1)]).long().cuda()

### create 1000 positive pairs ###
positives = torch.randint(low=0, high=256, size=(1000, 2))

### create 10000 negative pairs ###
negatives = torch.randint(low=0, high=256, size=(10000, 2))
negatives[:,1] += 256

a1, p = positives[:,0], positives[:,1]
a2, n = negatives[:,0], negatives[:,1]
indices_tuple = (a1, p, a2, n)

point_loss = nxt_loss(embeddings, labels, indices_tuple) 
```

**Comment by NCTU-VRDL** [comment]
Hi @KevinMusgrave!
Thanks so much for your help! Now my model is successfully trained!

**Comment by KevinMusgrave** [comment]
Glad to hear that 😄
