### ISSUE TITLE
embedding vector

### ISSUE THREAD

**Issue by jamesrobertwilliams** [KevinMusgrave/pytorch-metric-learning#221]
How do I go about converting the embedding vector which I provide to the loss function to logits for classification? is there a builtin function to do this? I pretty much try the sme approach as in the docs:

```
loss_func = losses.LargeMarginSoftmaxLoss(...).to(torch.device('cuda'))
loss_optimizer = torch.optim.SGD(loss_func.parameters(), lr=0.01)
# then during training:
loss_optimizer.step()
```

and I cannot seem to find anything in the docs to provide logits for classification (for example in inference mode).

**Comment by KevinMusgrave** [comment]
You can use [LogitGetter](https://kevinmusgrave.github.io/pytorch-metric-learning/inference_models/#logitgetter).

```python
from pytorch_metric_learning.utils.inference import LogitGetter
LG = LogitGetter(loss_fn)
embeddings = torch.randn(32, 512)
logits = LG(embeddings)
```

A couple things to note:
- The inference module requires ```faiss``` even though LogitGetter doesn't use faiss. This is dumb, so I'll fix this in the next release.
- LogitGetter makes a copy of the loss function's weights. So if you create a LogitGetter object, and then update the weights of your loss function, the LogitGetter will still be using the old weights. In the next release I'll add an option for not copying the weights.
- If your embedding size is equal to the number of classes, then the output of the LogitGetter (using default settings) might be incorrect. Let me know if this is the case and I can explain more.

**Comment by WUQUANJIANG** [comment]
from pytorch_metric_learning.utils.inference import LogitGetter
ImportError: cannot import name 'LogitGetter'

Pycharm keeps reporting this error, I want to know if my pytorch_Metric_learning version is wrong or something else

**Comment by KevinMusgrave** [comment]
@WUQUANJIANG Sorry about that, the code changed. Can you try this?

```python
logits = loss_fn.get_logits(embeddings)
```
