### ISSUE TITLE
Recombining trunk and embedder for inference

### ISSUE THREAD

**Issue by mightyroy** [KevinMusgrave/pytorch-metric-learning#224]
After training do we load the trained embedder and trunk separately in order to recombine them back into a single network? Would the model checkpoint files only be embedder_best.pth and trunk_best.pth? If I've got the right direction, do you have the script to recombine them neatly?

**Comment by KevinMusgrave** [comment]
> After training do we load the trained embedder and trunk separately in order to recombine them back into a single network?

Yes

> Would the model checkpoint files only be embedder_best.pth and trunk_best.pth? 

Yes

> If I've got the right direction, do you have the script to recombine them neatly?

You can create a module that wraps the trunk and embedder. Take a look at this link: https://github.com/KevinMusgrave/pytorch-metric-learning/issues/117#issuecomment-647505992

By the way, if you don't want to split your model into a trunk and embedder, you can pass just a trunk into the trainer and it'll still work. (The "embedder" will be set to "Identity" which does nothing.)

**Comment by mightyroy** [comment]
Thanks very much!!
