### ISSUE TITLE
when query and gallery is cross domain，it may be should  some modify

### ISSUE THREAD

**Issue by yulinhuyang** [KevinMusgrave/pytorch-metric-learning#234]
if I use this pytorch-metric-learning for image retival , the query and gallery is in different domain. how should I use the mining_func ? I used like this mining_func（query_feature, query_label, gallery_feature, gallery_label）,but it did not works very well. thanks!

**Comment by KevinMusgrave** [comment]
Yes, using the mining function like that should return pairs/triplets such that the anchors all come from ```query``` and the positives and negatives come from ```gallery```.
