### ISSUE TITLE
Question regarding precision_at_1

### ISSUE THREAD

**Issue by ivanpanshin** [KevinMusgrave/pytorch-metric-learning#249]
Hey :) 

Am I correct to think of precision_at_1 as pretty much simple classification accuracy? That is, precision_at_1 = whether the nearest sample in the KNN search is of the same class as the query. So if we sum up that for all validation samples, we get precision_at_1 from accuracy calculator, and that is classification accuracy. Correct?

**Comment by KevinMusgrave** [comment]
Yes. If you classify your queries using just the 1st nearest neighbor, then precision at 1 == classification accuracy.
