### ISSUE TITLE
where is the help documentation of get_all_embeddings 

### ISSUE THREAD

**Issue by yuxiaokang-source** [KevinMusgrave/pytorch-metric-learning#257]
when I run the mnist example provided on the package, I found 
```
def get_all_embeddings(dataset, model):
    tester = testers.BaseTester()
    return tester.get_all_embeddings(dataset, model)
```
I want to know all methods provided by the class testers.BaseTester(),the documentation provided on online only is the property of class BaseTester, but I can't find the help documentation of the methods(for example, the function get_all_embeddings)?

**Comment by KevinMusgrave** [comment]
Sorry about that. I haven't written documentation for various helper functions in this library. I'll put it on my to-do list though.

In case you're wondering about ```get_all_embeddings``` specifically, you can view the code here: https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/src/pytorch_metric_learning/testers/base_tester.py#L101

**Comment by KevinMusgrave** [comment]
Added a bit of documentation explaining ```get_all_embeddings```

**Comment by imneonizer** [comment]
I have a concern about `get_all_embeddings` It tends to load all vectors into memory, and I keep on hitting out of memory issue.

**Comment by KevinMusgrave** [comment]
They have to all be loaded into memory, for the purpose of calculating k-nn and clustering accuracy, which is what the testers in this library are for.

**Comment by imneonizer** [comment]
For anyone facing the same issue, you can set device to CPU for `AccuracyCalculator` it might be a bit slow but will work also the actual out of memory issue is raised bya `faiss`.

````python
accuracy_calculator = AccuracyCalculator(include=("precision_at_1",), device=torch.device("cpu"))
````

**Comment by Egorignatenko** [comment]
accuracy_calculator = AccuracyCalculator(include=("precision_at_1",), device=torch.device("cpu"))
