### ISSUE TITLE
SUGGESTION: Dataset sampler reshuffle data at every epoch.

### ISSUE THREAD

**Issue by JoOkuma** [KevinMusgrave/pytorch-metric-learning#26]
I've tested at my application, and shuffling the data at every epoch improved the results; it seems adequate because this way, the optimization process is more stochastic and more triplets are evaluated.

Do you think this change would be appreciated? It is just a small change to the `Samplers` classes.

**Comment by KevinMusgrave** [comment]
Aren't the two available samplers already completely random though?

**Comment by JoOkuma** [comment]
It was a bug on my part :P.

I thought that the same random batches were sampled at every epochs.
