### ISSUE TITLE
What is the meaning of the parameters in the documents?

### ISSUE THREAD

**Issue by Allennn-An** [KevinMusgrave/pytorch-metric-learning#266]
I just cannot understand what is the meaning of these parameters(q, k_+, k_i) in the documents (https://kevinmusgrave.github.io/pytorch-metric-learning/losses/#ntxentloss). Does the q, k_+, k_i in the formula of the documents for NTXentLoss convey the same meaning of the x_A, x_B in the paper of [SimCLR](https://arxiv.org/pdf/2002.05709.pdf)? Looking forward to your reply. Thank you!

**Comment by KevinMusgrave** [comment]
The equation shown is from the MoCo paper.
- ```q``` is the query embedding
- ```k_+``` is the embedding that has the same label as ```q```
- ```k_i``` is all the embeddings that have a different label from ```q```

Note that in the SimCLR and MoCo papers, there is only 1 positive pair in each batch. However, there is no such restriction when you use ```NTXentLoss```. In other words, there can be many ```k_+``` embeddings in the batch.

**Comment by Allennn-An** [comment]
So may I ask that if there are many k_+ embeddings in one batch, how is the loss of this batch computed? For example, in one batch, the embedding is (q, pos1, pos2, neg1, neg2) and the label is (1, 1, 1, 2, 2). In this case, is the loss computed as the following formula?
![image](https://user-images.githubusercontent.com/44702863/105130871-c4944880-5b22-11eb-8ae4-c0d1702396b1.png)

**Comment by KevinMusgrave** [comment]
The 2nd formula

**Comment by Allennn-An** [comment]
Thank you. But will the pair (pos1, pos2) be also considered as one positive pair in the batch because pos1 and pos2 both have the same label 1? So should the numerator of 2nd formula contain the pair (pos1, pos2), i.e. computing the loss as the following new formula?
![image](https://user-images.githubusercontent.com/44702863/105144315-024f9c00-5b38-11eb-8980-27f3a97f924b.png)

**Comment by KevinMusgrave** [comment]
Yes. Actually, if the labels are (1, 1, 1, 2, 2), then the following positive pairs will be used:

- (q, pos1)
- (pos1, q)
- (q, pos2)
- (pos2, q)
- (pos1, pos2)
- (pos2, pos1)
- (neg1, neg2)
- (neg2, neg1)

(q, pos1) and (pos1, q) are the same, unless you're using a non-symmetric distance measure.

**Comment by Allennn-An** [comment]
So to be more specific, the numerator of 2nd formula to compute the final loss of this batch should be the sum containing the eight loss corresponding to the eight positive pairs as you commented. And the denominator of the 2nd formula should be 8. Is my thinking correct here?

**Comment by KevinMusgrave** [comment]
That's correct

**Comment by Allennn-An** [comment]
Awesome. Thank you very much for your help!
