### ISSUE TITLE
How to define a custom miner function?

### ISSUE THREAD

**Issue by yuxiaokang-source** [KevinMusgrave/pytorch-metric-learning#271]
I have some problem in how to implement my own miner function! Could you give an example with how to define a new miner function?Should I inherit from the base miner class and then implement the method of the class?

**Comment by KevinMusgrave** [comment]
I've added a page on how to write your own miner: https://kevinmusgrave.github.io/pytorch-metric-learning/extend/miners/

Let me know if you have questions.
