### ISSUE TITLE
Small fix for NTXentLoss with no negative pairs

### ISSUE THREAD

**Issue by stephantul** [KevinMusgrave/pytorch-metric-learning#272]
If all instances in a single batch have the same class, the `NTXentLoss` crashes with an uninformative warning:
```
AttributeError: 'list' object has no attribute 'dtype'
```
This is because [this line](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/19b347a1bf0e1a74a009534285e529ae5d128dbb/src/pytorch_metric_learning/losses/generic_pair_loss.py#L37) assigns an empty list to `neg_pairs` if there are no negative pairs.
This crash can be avoided by moving the check for dtype in `NTXentLoss` (i.e.,  [this line](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/19b347a1bf0e1a74a009534285e529ae5d128dbb/src/pytorch_metric_learning/losses/ntxent_loss.py#L16)) a bit down, so it is enclosed by the if statement.

Should be a rare occurrence anyway, but I'd thought I'd signal it nonetheless 🐱 

I can do a PR if you'd like, but maybe this is such a small fix that it doesn't need a separate PR

**Comment by KevinMusgrave** [comment]
Thanks for finding this bug. I've fixed it in the latest commit
