### ISSUE TITLE
would you make implementation of Ranked List Loss 

### ISSUE THREAD

**Issue by DogeWatch** [KevinMusgrave/pytorch-metric-learning#285]
paper name is : Ranked List Loss for Deep Metric Learning
here is the paper: https://arxiv.org/pdf/1903.03238.pdf

**Comment by KevinMusgrave** [comment]
I might do this sometime in the future, but I'm unlikely to do it anytime soon

**Comment by KevinMusgrave** [comment]
Closing because this is a duplicate of #191
