### ISSUE TITLE
Error while using Bert as trunk

### ISSUE THREAD

**Issue by akuma3078** [KevinMusgrave/pytorch-metric-learning#29]
**When i use Bert as trunk, the output vector i get from Bert is torch.Size([1, 130, 768]) and i assume It expects to be 2D instead of 3D. Please check the traceback below.**

`RuntimeError                              Traceback (most recent call last)
<ipython-input-45-a7a9a6962bd0> in <module>
----> 1 trainer.train(num_epochs=num_epochs)

~/.local/lib/python3.6/site-packages/pytorch_metric_learning/trainers/base_trainer.py in train(self, start_epoch, num_epochs)
     84                 pbar.set_description("total_loss=%.5f" % self.losses["total_loss"])
     85             self.step_lr_schedulers()
---> 86             if self.end_of_epoch_hook(self) is False:
     87                 break
     88 

~/.local/lib/python3.6/site-packages/pytorch_metric_learning/utils/logging_presets.py in actual_hook(trainer)
     44             self.record_keeper.maybe_add_custom_figures_to_tensorboard(trainer.get_global_iteration())
     45             if trainer.epoch % test_interval == 0:
---> 46                 best_epoch = self.save_models_and_eval(trainer, dataset_dict, model_folder, test_interval, tester)
     47                 continue_training = self.patience_remaining(trainer.epoch, best_epoch, patience)
     48             return continue_training

~/.local/lib/python3.6/site-packages/pytorch_metric_learning/utils/logging_presets.py in save_models_and_eval(self, trainer, dataset_dict, model_folder, test_interval, tester, **kwargs)
     88     def save_models_and_eval(self, trainer, dataset_dict, model_folder, test_interval, tester, **kwargs):
     89         epoch = trainer.epoch
---> 90         tester.test(dataset_dict, epoch, trainer.models["trunk"], trainer.models["embedder"], list(dataset_dict.keys()), trainer.collate_fn, **kwargs)
     91         is_new_best, curr_accuracy, best_epoch, best_accuracy = self.is_new_best_accuracy(tester, self.validation_split_name, epoch)
     92         trainer.step_lr_plateau_schedulers(curr_accuracy)

~/.local/lib/python3.6/site-packages/pytorch_metric_learning/testers/base_tester.py in test(self, dataset_dict, epoch, trunk_model, embedder_model, splits_to_eval, collate_fn, **kwargs)
    185         embedder_model.eval()
    186         splits_to_eval, splits_to_compute_embeddings = self.get_splits_to_compute_embeddings(dataset_dict, splits_to_eval)
--> 187         embeddings_and_labels = self.get_all_embeddings_for_all_splits(dataset_dict, trunk_model, embedder_model, splits_to_compute_embeddings, collate_fn)
    188         self.maybe_compute_tsne(embeddings_and_labels, epoch)
    189         self.all_accuracies = defaultdict(dict)

~/.local/lib/python3.6/site-packages/pytorch_metric_learning/testers/base_tester.py in get_all_embeddings_for_all_splits(self, dataset_dict, trunk_model, embedder_model, splits_to_compute_embeddings, collate_fn)
    173         for split_name in splits_to_compute_embeddings:
    174             logging.info('Getting embeddings for the %s split'%split_name)
--> 175             embeddings_and_labels[split_name] = self.get_all_embeddings(dataset_dict[split_name], trunk_model, embedder_model, collate_fn)
    176         return embeddings_and_labels
    177 

~/.local/lib/python3.6/site-packages/pytorch_metric_learning/testers/base_tester.py in get_all_embeddings(self, dataset, trunk_model, embedder_model, collate_fn)
     80     def get_all_embeddings(self, dataset, trunk_model, embedder_model, collate_fn):
     81         dataloader = c_f.get_eval_dataloader(dataset, self.batch_size, self.dataloader_num_workers, collate_fn)
---> 82         embeddings, labels = self.compute_all_embeddings(dataloader, trunk_model, embedder_model)
     83         embeddings = self.maybe_normalize(embeddings)
     84         return embeddings, labels

~/.local/lib/python3.6/site-packages/pytorch_metric_learning/testers/base_tester.py in compute_all_embeddings(self, dataloader, trunk_model, embedder_model)
     71                 e = s + q.size(0)
     72                 all_q[s:e] = q
---> 73                 labels[s:e] = label
     74                 s = e
     75             labels = labels.cpu().numpy()

RuntimeError: The expanded size of the tensor (130) must match the existing size (32) at non-singleton dimension 0.  Target sizes: [130, 1].  Tensor sizes: [32, ### 1]`

**Comment by lebionick** [comment]
@akuma3078 
So, you should use some kind of _pooling_ at the end of BERT (or beginning of `embedder`). It can be _mean_ or _max_ operation (performed over all tokens, maybe excluding `<SEP>` or something like that). Or you can just use embedding of `<CLS>` token by selecting first channel of yours 130. 
P.S. I'm doing the same task and don't know what is better yet, maybe even concatenation of all embeddings or LSTM over all tokens in `embedder`

**Comment by akuma3078** [comment]
Yeah,
Got it.I have been trying both ,concat and sum, lets see what work best.
