### ISSUE TITLE
Choose FAISS gpu usage

### ISSUE THREAD

**Issue by elias-ramzi** [KevinMusgrave/pytorch-metric-learning#292]
Hi,

Thanks a lot for the library !

I had an issue using AccuracyCalculator because FAISS was using other gpus than the one I was working on.
Would it be possible to change the function [`get_knn`](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/src/pytorch_metric_learning/utils/stat_utils.py) so that it would take an optional argument, that if passed the FAISS knn search would be done on a single gpu (the one where the embeddings are stored).

```
def get_knn(
      reference_embeddings, test_embeddings, k, embeddings_come_from_same_source=False, use_all_gpu=True
  ):
      device = reference_embeddings.device
      reference_embeddings = c_f.to_numpy(reference_embeddings).astype(np.float32)
      test_embeddings = c_f.to_numpy(test_embeddings).astype(np.float32)

      d = reference_embeddings.shape[1]
      logging.info("running k-nn with k=%d" % k)
      logging.info("embedding dimensionality is %d" % d)
      index = faiss.IndexFlatL2(d)
      if faiss.get_num_gpus() > 0:
          if use_all_gpu:
              index = faiss.index_cpu_to_all_gpus(index)
          else:
              res = faiss.StandardGpuResources()
              index = faiss.index_cpu_to_gpu(res, device.index, index)
      index.add(reference_embeddings)
      distances, indices = index.search(test_embeddings, k + 1)
      distances = c_f.to_device(torch.from_numpy(distances), device=device)
      indices = c_f.to_device(torch.from_numpy(indices), device=device)
      if embeddings_come_from_same_source:
          return indices[:, 1:], distances[:, 1:]
      return indices[:, :k], distances[:, :k]
```
The following changes would have to be also done for the `run_kmeans` function.

And then you would be able to pass the same argument to AccuracyCalculator.

Thanks

**Comment by KevinMusgrave** [comment]
Makes sense

**Comment by farahFif** [comment]
Has this problem been solved ?

**Comment by KevinMusgrave** [comment]
Not yet

**Comment by elias-ramzi** [comment]
Hey, I had no time to take a closer look at this. For now I just use `CUDA_VISIBLE_DEVICES`.

**Comment by KevinMusgrave** [comment]
Added ```gpus``` argument to v1.0.0:
```python
knn_func = FaissKNN(gpus=[0,1,2])
```
Related issue: https://github.com/KevinMusgrave/pytorch-metric-learning/issues/368

Relevant docs:
- [Accuracy Calculation](https://kevinmusgrave.github.io/pytorch-metric-learning/accuracy_calculation/)
- [FaissKNN](https://kevinmusgrave.github.io/pytorch-metric-learning/inference_models/#faissknn)
