### ISSUE TITLE
Question about Accuracy Calculation in GlobalTwoStreamEmbeddingSpaceTester

### ISSUE THREAD

**Issue by gkouros** [KevinMusgrave/pytorch-metric-learning#301]
Hello Kevin,

I would like to request your advice on an issue I'm facing with this library.

I have a dataset that has 2 samples per class, no more no less. Adding more positives per class or doing data augmentation is not an option. My Dataset returns a tuple (anchor, positive, label), where anchor and positive are the 2 samples. I have tried to adapt the [TwoStreamMetricLoss](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/examples/notebooks/TwoStreamMetricLoss.ipynb)  example notebook to my problem.

Similarly to the example, I use the following:
- losses.TripletMarginLoss
- miners.TripletMarginMiner
- samplers.MPerClassSampler (with m=1)
- testers.GlobalTwoStreamEmbeddingSpaceTester (with AccuracyCalculator(k=1))
- trainers.TwoStreamMetricLoss

My problem is that while training, the tester reports a 0 accuracy in the beginning, and afterwards for each epoch there is the warning "[WARNING] None of the query labels are in the reference set." and I don't get any improvements on the performance metrics. Is my approach valid and if so is there something I can change to fix the issue (eg. make a custom accuracy calculator)?

Thank you in advance.

George

**Comment by KevinMusgrave** [comment]
I think there is a bug in ```GlobalTwoStreamEmbeddingSpaceTester```. Can you try this?

```python
from pytorch_metric_learning.utils.accuracy_calculator import AccuracyCalculator

class CustomAccuracyCalculator(AccuracyCalculator):
    def get_accuracy(self, query, reference, query_labels, reference_labels, embeddings_come_from_same_source, include=(), exclude=()):
        return super().get_accuracy(query, reference, query_labels, reference_labels, False, include, exclude)

# pass in CustomAccuracyCalculator
tester = testers.GlobalTwoStreamEmbeddingSpaceTeste(accuracy_calculator=CustomAccuracyCalculator(k=1))
```

**Comment by gkouros** [comment]
Thank you for the quick response! Your suggestion worked!
