### ISSUE TITLE
Error in computing similarity with multiple GPUs

### ISSUE THREAD

**Issue by shashankvkt** [KevinMusgrave/pytorch-metric-learning#308]
Hi Kevin.
Thank you for providing this wonderful code for metric learning. I am facing a weird issue for which I seek your guidance. When I use a simple contrastive loss to train my network on multiple GPUs. I get the following error. 

```
File "../pytorch_metric_learning/distances/base_distance.py", line 26, in forward
    query_emb, ref_emb, query_emb_normalized, ref_emb_normalized
  File "../pytorch_metric_learning/distances/base_distance.py", line 74, in set_default_stats
    self.get_norm(query_emb)
RuntimeError: CUDA error: device-side assert triggered
```

However, this error **does not occur when I train my network on a single GPU**. Could you please let me know what might cause this issue and its possible fix? Its not the pytorch version issue because my `torch==1.7.1` and `torchvision==0.8.2`. I have used your latest code for metric learning.  
Thanks.

**Comment by KevinMusgrave** [comment]
Are you using DataParallel or DistributedDataParallel?

**Comment by shashankvkt** [comment]
I am using DataParallel.

**Comment by KevinMusgrave** [comment]
Hmm strange. What is the shape of your embeddings and labels?

**Comment by KevinMusgrave** [comment]
Also try running your code like this to get a better error message:

```
CUDA_LAUNCH_BLOCKING=1 python your_script.py
```

**Comment by shashankvkt** [comment]
So the shape of my embeddings and labels are torch.Size([4160, 128])

**Comment by KevinMusgrave** [comment]
Can you try this workaround?

```python
loss_func = ContrastiveLoss()
# set collect_stats to False to skip the set_default_stats call
loss_func.distance.collect_stats = False
```

**Comment by KevinMusgrave** [comment]
> So the shape of my embeddings and labels are torch.Size([4160, 128])

I assume you mean embeddings has shape (4160,128) and labels has shape (4160,)

Can you try a smaller batch size?

**Comment by shashankvkt** [comment]
Im sorry, my bad. Yes you are right about the dimensions. The above error still occurs for a smaller batchsize (without the workaround).
So the workaround of using ` loss_func.distance.collect_stats = False` works, but its raises another error when computing the loss as follows:

```
File "../pytorch_metric_learning/reducers/base_reducer.py", line 16, in forward
    losses, loss_indices, reduction_type, kwargs, embeddings, labels
  File "../pytorch_metric_learning/reducers/base_reducer.py", line 37, in reduce_the_loss
    return reduction_func(losses, loss_indices, embeddings, labels, **kwargs)
  File "../pytorch_metric_learning/reducers/threshold_reducer.py", line 23, in pos_pair_reduction
    return self.element_reduction_helper(losses, embeddings, "pos_pairs")
  File "../pytorch_metric_learning/reducers/threshold_reducer.py", line 36, in element_reduction_helper
    if num_past_filter >= 1:
RuntimeError: CUDA error: device-side assert triggered

```

**Comment by KevinMusgrave** [comment]
Can you try a dumb loss like this?
```python
loss = torch.mean(embeddings)
```

**Comment by shashankvkt** [comment]
`loss = torch.mean(embeddings)` works properly. But Im curious to understand the reason for the error when computing the similarity matrix. Does it have something to do with range of values of the embedding?

**Comment by KevinMusgrave** [comment]
I have no idea what's going on actually 😄 I've been able to train with DataParallel, and the error message you're getting is cryptic.

The similarity matrix is still being computed. (```loss_func.distance.collect_stats = False``` just turns off some unrelated computations)

I think it's also getting past the actual contrastive loss computation, but then getting stuck in the reducer.

You could try passing in a DoNothingReducer, and manually perform the reduction:

```python
from pytorch_metric_learning.reducers import DoNothingReducer
from pytorch_metric_learning.losses import ContrastiveLoss

loss_func = ContrastiveLoss(reducer=DoNothingReducer())

losses = loss_func(embeddings, labels)
pos_loss = losses["pos_loss"]["losses"]
neg_loss = losses["neg_loss"]["losses"]

pos_loss = pos_loss[pos_loss > 0]
neg_loss = neg_loss[neg_loss > 0]

loss = 0 
if len(pos_loss) > 0:
    loss += torch.mean(pos_loss)
if len(neg_loss) > 0:
    loss += torch.mean(neg_loss)
if loss > 0:
    loss.backward()
```

**Comment by KevinMusgrave** [comment]
What's also confusing is how it's getting stuck on the if-statement ```if num_past_filter >= 1```, but not the computation for ```num_past_filter``` which is ```num_past_filter = torch.sum(threshold_condition)```

**Comment by KevinMusgrave** [comment]
For the purpose of debugging, you could print the losses inside the reducer:

```python
from pytorch_metric_learning.reducers import AvgNonZeroReducer
from pytorch_metric_learning.losses import ContrastiveLoss

class CustomAvgNonZeroReducer(AvgNonZeroReducer):
    def forward(self, loss_dict, embeddings, labels):
        print("losses", loss_dict[list(loss_dict.keys())[0]]["losses"])
        return super().forward(loss_dict, embeddings, labels)

loss_func = ContrastiveLoss(reducer=CustomAvgNonZeroReducer())
```

**Comment by shashankvkt** [comment]
Hi Kevin, thank you for your feedback. I was busy in some other work due to which I could not try out your suggestion. Will get back to you shortly on this.

**Comment by shashankvkt** [comment]
Hi Kevin, sorry for the delay in response.  
So, the problem is not with the code but with the way in which the similarities of positive and negative pairs are computed across multiple GPUs. So, in the code below 

```
if len(a1) > 0:
      pos_pair_dist = similarity_matrix[a1, p]
if len(a2) > 0:
      neg_pair_dist = similarity_matrix[a2, n]
```
in my case, the similarity matrix and the indices of the positive and negative pairs get split across these GPUs in such a way that the indexing becomes out of bounds. I notice that the matrix is not evenly split between the GPUs.  I think the solution would be to collect them all in one GPU and then move forward with computing the loss.

**Comment by KevinMusgrave** [comment]
I see, so you're wrapping the loss function with DataParallel? That would cause the problem. I guess if you don't wrap the loss function with DataParallel, then you run out of memory on one of the GPUs?

**Comment by shashankvkt** [comment]
I guess it is not a memory issue, but an indexing issue. For e.g. in one of my GPUs, let say that the similarity matrix has a shape 50x50, then I find that a1, p might have values like 52 or 53 which are out of bounds with respect to the matrix in that GPU. This basically causes the issue.

**Comment by KevinMusgrave** [comment]
Yeah my point is do you need to wrap the loss function with DataParallel? Usually you can just wrap the model with DataParallel, and leave the loss as is.

**Comment by shashankvkt** [comment]
strangely I observe this when I do not wrap the loss in DataParallel, which is super weird.

**Comment by KevinMusgrave** [comment]
Maybe the embeddings are spread across multiple devices before they are passed to the loss function. You could try moving them to a single device:

```python
gpu0 = torch.device('cuda:0')
embeddings = embeddings.to(gpu0)
labels = labels.to(gpu0)
loss = loss_fn(embeddings, labels)
```

**Comment by KevinMusgrave** [comment]
That's probably all I can think of, and there doesn't seem to be a PML-related solution because the error is a bit mysterious. Closing this issue for now.
