### ISSUE TITLE
Applying TripletMarginMiner To Image Segmentation

### ISSUE THREAD

**Issue by H0PP3R** [KevinMusgrave/pytorch-metric-learning#317]
Hello, I'm attempting to train a segmentation network via triplet loss on the COCO dataset and am running into problems in regards to mining triplet samples from my segmentation masks. I'm using an FCN network (AlexNet with the last layer removed), and the embeddings when I pass my data in is of size [N, 1000] with N = batch size. I  want my labels to be segmentation masks but as stated in your documentation, labels must be of size [N]. My labels are of size [N, mask width, mask height]. Even reshaping my segmentation mask from [mask width, mask height] to [mask width* mask height] wouldn't help with the mining function accepting my input as labels as it still is of size [N, mask width*mask height]. I've tried other triplet loss libraries and they seem to require the same input size of [N] for labels. Is there anything I'm missing from this library that could help with my issue?

**Comment by KevinMusgrave** [comment]
Based on the shapes, it seems like your embeddings and labels are coming from 2 different places. The embeddings look like classification logits, and the labels look like segmentation labels.

Here's my best guess at what you should do:

1. Use the segmentation logits as embeddings. This will probably have shape ```(N, num_classes, mask_width, mask_height)```.
2. Reshape the embeddings to have size ```(N*mask_width*mask_height, num_classes)```.
3. Reshape the segmentation labels to have size ```(N*mask_width*mask_height,)```.

Then everything will be the correct shape.

Having said that, you will probably run out of memory when you try doing the triplet mining (see issue #229). I haven't yet figured out how to make tuple-based losses and miners work on massive batch sizes. 

If you're okay with using classification based losses, you could try [ArcFaceLoss](https://kevinmusgrave.github.io/pytorch-metric-learning/losses/#arcfaceloss). This should work better in terms of memory.

**Comment by KevinMusgrave** [comment]
Some corrections to my above reply:

1. The embeddings should have shape ```(N, embedding_size, mask_width, mask_height)```, i.e. the 2nd dimension doesn't need to be ```num_classes```. The embedding size is determined by your model architecture.
2. Therefore, you should reshape your embeddings to be of shape ```(N*mask_width*mask_height, embedding_size)```. Again the difference from my previous reply is that the 2nd dimension is ```embedding_size``` rather than ```num_classes```.

**Comment by H0PP3R** [comment]
Ok thank you, I'll try applying your suggestion.

**Comment by H0PP3R** [comment]
I've tried out your suggestion and the mining function has accepted the inputs and as predicted I have received an memory allocation error but that is out of my control. Thank you very much for your help!
