### ISSUE TITLE
how to implement a custom trainer?

### ISSUE THREAD

**Issue by Sino0904** [KevinMusgrave/pytorch-metric-learning#325]
Hello,

Can you provide an example for how to utilize the BaseTrainer to implement a custom trainer? I essentially want to extend TrainWithClassifier by adding a regression head. But I am not sure how to do it.

Thanks a lot!

**Comment by Sino0904** [comment]
I was doing something similar too. I first installed the library using pip and had code below as a separate file.

import pytorch_metric_learning
from pytorch_metric_learning.utils import common_functions as c_f
from pytorch_metric_learning.trainers import TrainWithClassifier

class TrainWithClassifierRegressor(TrainWithClassifier):
    def calculate_loss(self, curr_batch):
        data, labels = curr_batch
        embeddings = self.compute_embeddings(data)
        logits = self.maybe_get_logits(embeddings)
        reglogits = self.maybe_get_reglogits(embeddings)
        indices_tuple = self.maybe_mine_embeddings(embeddings, labels[0])
        self.losses["metric_loss"] = self.maybe_get_metric_loss(embeddings, labels, indices_tuple)
        self.losses["classifier_loss"] = self.maybe_get_classifier_loss(logits, labels[0])
        self.losses["regressor_loss"] = self.maybe_get_regressor_loss(reglogits, labels[1])

    def maybe_get_reggressor_loss(self, logits, labels):
        if logits is not None:
            return self.loss_funcs["regressor_loss"](
                logits, c_f.to_device(labels, logits)
            )
        return 0

    def maybe_get_reglogits(self, embeddings):
        if (
            self.models.get("regressor", None)
            and self.loss_weights.get("regressor_loss", 0) > 0
        ):  
            return self.models["regressor"](embeddings)
        return None

    def modify_schema(self):
        super().modify_schema()
        self.schema["models"].keys += ["regressor"]
        self.schema["loss_funcs"].keys += ["regressor_loss"]


However I am getting the following error:

Traceback (most recent call last):
  File "main.py", line 186, in <module>
    end_of_epoch_hook = end_of_epoch_hook)
  File "/vis/home/ashishsingh/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/pytorch_metric_learning/trainers/base_trainer.py", line 62, in __init__
    self.verify_dict_keys()
  File "/vis/home/ashishsingh/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/pytorch_metric_learning/trainers/base_trainer.py", line 268, in verify_dict_keys
    self.verify_models_keys()
  File "/vis/home/ashishsingh/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/pytorch_metric_learning/trainers/base_trainer.py", line 339, in verify_models_keys
    important_keys=[x for x in self.allowed_model_keys() if x != "trunk"],
  File "/vis/home/ashishsingh/anaconda3/envs/pytorch_1.7/lib/python3.6/site-packages/pytorch_metric_learning/trainers/base_trainer.py", line 293, in _verify_dict_keys
    ), "%s keys must be one of %s" % (obj_name, ", ".join(allowed_keys))
AssertionError: models keys must be one of trunk, embedder, classifier

**Comment by KevinMusgrave** [comment]
Your example works for me. Are you on version 0.9.99?

**Comment by Sino0904** [comment]
No I was not. I just updated to the latest version and tried again. It is working now. Thanks a lot!
