### ISSUE TITLE
Root __init__.py is not included in the distribution file

### ISSUE THREAD

**Issue by fralik** [KevinMusgrave/pytorch-metric-learning#33]
The title says it all. This results in the following behaviour.

**Ways to reproduce:**
1. Install the package (either build locally or from pip).
2. Try to run `import pytorch_metric_learning; pytorch_metric_learning.__version__`.

**Expected:**
Expected to see version information.

**Actual:**
Error `AttributeError: module 'pytorch_metric_learning' has no attribute '__version__'`.

It is still possible to get version number like this:
```python
import pkg_resources
pkg_resources.get_distribution("pytorch_metric_learning").version
```
but I think that `.__version__` is easier.

One way to fix it is to move folder `pytorch_metric_learning` under `src` and change `setup.py` a bit.

I can make a PR for this if this is not by design.

**Comment by KevinMusgrave** [comment]
@fralik Thanks for pointing this out. A PR to fix it would be great!
