### ISSUE TITLE
Using samplers with DistributedSampler

### ISSUE THREAD

**Issue by sayakpaul** [KevinMusgrave/pytorch-metric-learning#336]
Hi. 

Could you provide a minimal snippet that shows how to use `DistributedSampler` with the samplers discussed [here](https://kevinmusgrave.github.io/pytorch-metric-learning/samplers/) in the official doc?

**Comment by KevinMusgrave** [comment]
Good question! Unfortunately I don't have much experience with ```DistributedSampler```, so I don't know how exactly it interacts with regular samplers. This thread might be relevant: https://github.com/pytorch/pytorch/issues/23430

**Comment by sayakpaul** [comment]
Thanks for the prompt response. I think I can take it from here. Closing the issue.
