### ISSUE TITLE
For each query images, get top k most similar images from reference images when they are in separate datasets

### ISSUE THREAD

**Issue by KennyThinh** [KevinMusgrave/pytorch-metric-learning#342]
I have my model which is already trained well.

When it comes to Inference phase, I follow your notebook here [https://colab.research.google.com/github/KevinMusgrave/pytorch-metric-learning/blob/master/examples/notebooks/Inference.ipynb](url)

It seems when compare 2 images, they are all from 1 dataset. How can I compare images from 2 different dataset (i.e., they are stored in different folders so they need different dataloader to load)?

The reason is that: I separate my reference images and query images into 2 datasets. And then I want to check "for each query images, get top k the most similar images from reference images"? If you know how to do this with InferenceModel, please tell me.

Thanks a lot

**Comment by KevinMusgrave** [comment]
I think this should work:

```python
# set dataset1 as the reference
inference_model.train_indexer(dataset1)

# loop through dataset2
dataloader = torch.utils.data.DataLoader(dataset2, batch_size=1024)
for imgs, _ in dataloader:
    # get the 10 nearest neighbors in dataset1 for each query in dataset2
    indices, distances = inference_model.get_nearest_neighbors(imgs, k=10)
```

**Comment by KennyThinh** [comment]
No, it does not work. It said that "RuntimeError: Index must be trained by running `train_indexer`".

**Comment by KevinMusgrave** [comment]
Hmm it worked on my end. Did you run ```inference_model.train_indexer(dataset1)```?

**Comment by KennyThinh** [comment]
My bad variable management on jupyter notebooks. It fixed now. Thanks you, very interesting and helpful library.

**Comment by KevinMusgrave** [comment]
Great!

**Comment by KennyThinh** [comment]
I have one more question.  get_nearest_neighbors(img, k) basically compare the embedding of img with the embedding of each image in dataset1 and return the k images with the highest similarity?

**Comment by KevinMusgrave** [comment]
Yes, it returns:
- indices of the most similar images in dataset1
- distances from the query embedding to those image embeddings

The "most similar" reference images are the ones that have embeddings closest to the query embedding.

Also by default all embeddings are normalized to have an L2 norm of 1. You can turn this off if you want:

```python
inference_model = InferenceModel(..., normalize_embeddings=False)
```

**Comment by KennyThinh** [comment]
Yes, thank you. I am thinking about the strategy to return the most relevant class for 1 query given that we already have multiple reference images per class. Something like this

Method 1
1. Combining embeddings of reference images to be 1 embeddings vector. So each class will have 1 combined embedding vector.
2. Compare this combined embedding with the embedding of query image. 
3. Return the class which has the most similarity btw its combined embedding and query image

Meethod 2
1. Select top k (i.e k=10) by using get_nearest_neighbors(img, k)
2. Return class which have the most indices within top k (e.g within 10 indices, there are 5 indices belong to the class 5, so return class 5)

I can use InferenceModel to implement Method 2. But how can I use InferenceModel to implement Method 1? (Or not necessary InferenceModel is fine)

**Comment by KevinMusgrave** [comment]
There isn't a built-in way to do method 1, but something like this should work (might be buggy, I spent 5 minutes on it):

```python
# this is just a convenient way of getting all the reference embeddings
from pytorch_metric_learning.testers import BaseTester
tester = BaseTester(normalize_embeddings=True)
embeddings, labels = tester.get_all_embeddings(reference_dataset, model)

# compute class centers
class_centers = []
for L in torch.unique(labels, sorted=True):
    mask = labels == L
    class_embeddings = embeddings[mask]
    center = torch.mean(class_embeddings, dim=0)
    class_centers.append(center)

class_centers = torch.cat(class_centers, dim=0)

from pytorch_metric_learning.utils.inference import FaissIndexer, InferenceModel
indexer = FaissIndexer()
indexer.train_index(class_centers)

inference_model = InferenceModel(..., indexer=indexer)

# skip the "train_indexer" step
dataloader = torch.utils.data.DataLoader(query_dataset, batch_size=1024)
for imgs, _ in dataloader:
    indices, distances = inference_model.get_nearest_neighbors(imgs, k=1)

```

**Comment by KennyThinh** [comment]
thanks you very much for your time and efforts!

**Comment by KennyThinh** [comment]
Just want to confirm.
If the get_nearest_neighbors (k=6) returns like this
```
indices = np.array([[0,2,1,5,4,3]]) 
distances =np.array([[0.36101693, 0.54732907, 0.6231322, 1.1509585, 1.1570907, 1.3241544]])

```
so this mean the indices 0 is the most similar one because it has the smallest distance?

**Comment by KevinMusgrave** [comment]
Yes

**Comment by KennyTC** [comment]
I would like to ask follow -up questions. 

1) If I use Method 1 during inference, what is the proper metric during training model? (For a little sensitive reason, I have to prefer using Method 1 for inference). So far, I use to optimize `precision_at_1` metric during my training, then it seems not generalize well if I use Method 1 during inference. 
I do think the metric "precision_at_1" during training is the best match with "get_nearest_neighbors" during Inference, right?

2) Do I need to worry about the speed if using Method 2? As k increases, or reference images increase, `inference_model.get_nearest_neighbors(imgs, k=1)` will take longer time as we need to go into all reference images to find the most k relevant images, right.
I saw some real time apps can recognize face very fast. I am wondering if they also use something like ``inference_model.get_nearest_neighbors(imgs)` for real-time recognition? If you know, please give me some hints.

**Comment by KevinMusgrave** [comment]
> 1. If I use Method 1 during inference, what is the proper metric during training model? (For a little sensitive reason, I have to prefer using Method 1 for inference). So far, I use to optimize `precision_at_1` metric during my training, then it seems not generalize well if I use Method 1 during inference.
>    I do think the metric "precision_at_1" during training is the best match with "get_nearest_neighbors" during Inference, right?

Any of the metrics in AccuracyCalculator will be a reasonable indicator of accuracy. Maybe you should try using method 1 during validation.

> 2. Do I need to worry about the speed if using Method 2? As k increases, or reference images increase, `inference_model.get_nearest_neighbors(imgs, k=1)` will take longer time as we need to go into all reference images to find the most k relevant images, right.
>    I saw some real time apps can recognize face very fast. I am wondering if they also use something like ``inference_model.get_nearest_neighbors(imgs)` for real-time recognition? If you know, please give me some hints.

Yes, method 1 will be faster than method 2 because the search space of method 1 is the number of classes, whereas the search space for method 2 is number of samples. I don't have experience deploying ML models for real-time applications.

**Comment by KennyTC** [comment]
Sorry for get back to this. 

> Maybe you should try using method 1 during validation.

I do really want to implement method 1 during validation. 
I have read this (https://kevinmusgrave.github.io/pytorch-metric-learning/accuracy_calculation/), and know that I need to build customer accuracy class to do it. But still I found it difficult to implement the idea. 
1) My validation set should include gallery and query set right?
2) If I am using tester like below, should I replace accuracy_calculator with the custome accuracy class? In this case, dataset_dict should also include train_data and val_data?
3) If possible, can you help me the structure of the implementation?

Thanks a lot.
```
record_keeper, _, _ = logging_presets.get_record_keeper(...)
hooks = logging_presets.get_hook_container(record_keeper, primary_metric="precision_at_1")
dataset_dict = {"train":train_data, "val": val_data}
model_folder = ...

def visualizer_hook(umapper, umap_embeddings, labels, split_name, keyname, *args):
    ....
    plt.show()

# Create the tester
tester = testers.GlobalEmbeddingSpaceTester(end_of_testing_hook = hooks.end_of_testing_hook, 
                                            visualizer = umap.UMAP(), 
                                            visualizer_hook = visualizer_hook,
                                            dataloader_num_workers = 8,
                                            accuracy_calculator=AccuracyCalculator(k="max_bin_count"))

end_of_epoch_hook = hooks.end_of_epoch_hook(tester, 
                                            dataset_dict, 
                                            model_folder, 
                                            test_interval = 1,
                                            patience = 5)
```

**Comment by KevinMusgrave** [comment]
Pass this accuracy calculator into the tester:

```python
from pytorch_metric_learning.utils.accuracy_calculator import AccuracyCalculator
from pytorch_metric_learning.utils import stat_utils

class CustomAccuracyCalculator(AccuracyCalculator):
    def calculate_nearest_centroid_accuracy(self, query, reference, query_labels, reference_labels, **kwargs):
        centroids, labels = [], []
        
        for L in torch.unique(reference_labels):
            labels.append(torch.tensor([L]))
            idx = reference_labels == L
            centroids.append(torch.mean(reference[idx], dim=0, keepdims=True))
        labels = torch.cat(labels, dim=0).to(query_labels.device)
        centroids = torch.cat(centroids, dim=0).to(query.device)
        print(centroids.shape)
        print(query.shape)

        knn_indices, _ = stat_utils.get_knn(centroids, query, 1, False)
        knn_indices = knn_indices[:, 0]
        labels = labels[knn_indices]
        return torch.mean((query_labels == labels).float()) 
```

**Comment by KennyTC** [comment]
Thank you very much. I will  try.

**Comment by pheersaquoff** [comment]
> There isn't a built-in way to do method 1, but something like this should work (might be buggy, I spent 5 minutes on it):
> 
> ```python
> # this is just a convenient way of getting all the reference embeddings
> from pytorch_metric_learning.testers import BaseTester
> tester = BaseTester(normalize_embeddings=True)
> embeddings, labels = tester.get_all_embeddings(reference_dataset, model)
> 
> # compute class centers
> class_centers = []
> for L in torch.unique(labels, sorted=True):
>     mask = labels == L
>     class_embeddings = embeddings[mask]
>     center = torch.mean(class_embeddings, dim=0)
>     class_centers.append(center)
> 
> class_centers = torch.cat(class_centers, dim=0)
> 
> from pytorch_metric_learning.utils.inference import FaissIndexer, InferenceModel
> indexer = FaissIndexer()
> indexer.train_index(class_centers)
> 
> inference_model = InferenceModel(..., indexer=indexer)
> 
> # skip the "train_indexer" step
> dataloader = torch.utils.data.DataLoader(query_dataset, batch_size=1024)
> for imgs, _ in dataloader:
>     indices, distances = inference_model.get_nearest_neighbors(imgs, k=1)
> ```

@KevinMusgrave Hi, could you please help me, is this still the most convenient way to get classes centroids and get class prediction for a query image? As I see there is no FaissIndexer more and I'm stacked a little bit with indexers, getting ValueError: self.index is None. It needs to be initialized before being used. when try to initialize inferencemodel without indexer

**Comment by KevinMusgrave** [comment]
@pheersaquoff It's called FaissKNN now. Also make sure to do `torch.stack` instead of `torch.cat` for the `class_centers`:

```python
import torch
from pytorch_metric_learning.utils.inference import InferenceModel, FaissKNN

embeddings = torch.randn(1000, 32)
labels = torch.randint(0, 10, size=(1000,))

# compute class centers
class_centers = []
for L in torch.unique(labels, sorted=True):
    mask = labels == L
    class_embeddings = embeddings[mask]
    center = torch.mean(class_embeddings, dim=0)
    class_centers.append(center)

class_centers = torch.stack(class_centers, dim=0)

model = torch.nn.Linear(128,32)
knn = FaissKNN(reset_before=False, reset_after=False)
knn.train(class_centers)
inference_model = InferenceModel(model, knn_func=knn)

query = torch.randn(1000, 128)
indices, distances = inference_model.get_nearest_neighbors(query, k=1)
```

**Comment by pheersaquoff** [comment]
@KevinMusgrave thank you for reply! and precision\recall should be computed of ```_, reference_labels = BaseTester.get_all_embeddings(test_dataset, ...)``` and ```_, query_labels = InferenceModel.get_nearest_neighbors(k=1,...)```, is that right?

**Comment by KevinMusgrave** [comment]
`get_nearest_neighbors` returns `indices, distances`, so to get the retrieved label you would do something like `reference_labels[indices]`
