### ISSUE TITLE
The way of get distance by using cosine simlarity instead of L2

### ISSUE THREAD

**Issue by kehuantiantang** [KevinMusgrave/pytorch-metric-learning#348]
Hello:
Given a query sample, I try to visualize the most closed reference sample by using knn distance, but I find the method of `get_knn` is based on the `faiss.IndexFlatL2` from here:
```python
def get_knn(
    reference_embeddings, test_embeddings, k, embeddings_come_from_same_source=False
):
    if embeddings_come_from_same_source:
        k = k + 1
    device = reference_embeddings.device
    reference_embeddings = c_f.to_numpy(reference_embeddings).astype(np.float32)
    test_embeddings = c_f.to_numpy(test_embeddings).astype(np.float32)

    d = reference_embeddings.shape[1]
    logging.info("running k-nn with k=%d" % k)
    logging.info("embedding dimensionality is %d" % d)
    #calculate the L2 distance
    cpu_index = faiss.IndexFlatL2(d)
    distances, indices = try_gpu(cpu_index, reference_embeddings, test_embeddings, k)
    distances = c_f.to_device(torch.from_numpy(distances), device=device)
    indices = c_f.to_device(torch.from_numpy(indices), device=device)
    if embeddings_come_from_same_source:
        return indices[:, 1:], distances[:, 1:]
    return indices, distances
```
Could you help me to calcuate the distance by cosine-similarity, thanks a lot ^_^

**Comment by KevinMusgrave** [comment]
Currently there isn't a built-in way to change the faiss index type. 

You could manually replace ```cpu_index = faiss.IndexFlatL2(d)``` with ```cpu_index = faiss.IndexFlatIP(d)```.

Related issue: https://github.com/facebookresearch/faiss/issues/95

**Comment by kehuantiantang** [comment]
Hello, @KevinMusgrave 
Thank you so much for your replay
-  I find the reference_embeedings and test_embeddings is not normalized vectors. Is it correct to compute use this way ?
- Besides, following your method, the calcuated distance is not range from [0, 1],  cosine similarity is not range from 0 to 1?

Hope you can help me, thank you so much.

**Comment by kehuantiantang** [comment]
> Hello, @KevinMusgrave
> Thank you so much for your replay
> 
> * I find the reference_embeedings and test_embeddings is not normalized vectors. Is it correct to compute use this way ?
> * Besides, following your method, the calcuated distance is not range from [0, 1],  cosine similarity is not range from 0 to 1?
> 
> Hope you can help me, thank you so much.

I fix the problem by normalize them, according to your [**related issue**]( facebookresearch/faiss#95)
```python
def get_knn(
            self, reference_embeddings, test_embeddings, k, embeddings_come_from_same_source=False
    ):

        if embeddings_come_from_same_source:
            k = k + 1
        device = reference_embeddings.device
        reference_embeddings = c_f.to_numpy(reference_embeddings).astype(np.float32)
        test_embeddings = c_f.to_numpy(test_embeddings).astype(np.float32)

        faiss.normalize_L2(reference_embeddings)
        faiss.normalize_L2(test_embeddings)

        d = reference_embeddings.shape[1]
        logging.info("running k-nn with k=%d" % k)
        logging.info("embedding dimensionality is %d" % d)
        cpu_index = faiss.IndexFlatIP(d)
        distances, indices = try_gpu(cpu_index, reference_embeddings, test_embeddings, k)
        distances = c_f.to_device(torch.from_numpy(distances), device=device)
        indices = c_f.to_device(torch.from_numpy(indices), device=device)
        if embeddings_come_from_same_source:
            return indices[:, 1:], distances[:, 1:]
        return indices, distances
```
Thanks again ^_^
