### ISSUE TITLE
CosFace Loss Function Error

### ISSUE THREAD

**Issue by kameel2311** [KevinMusgrave/pytorch-metric-learning#357]
I am trying to train a simple embedding layer, such that the input is a list of feature vectors of length 512 with the following code below: 

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
@author: Kameel Amareen
"""
import os
import numpy as np
import pickle
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from pytorch_metric_learning import losses

class Net(nn.Module):
    def __init__(self, embedding_size,num_classes):
        super(Net, self).__init__()
        # Embedding fully connected layer
        self.fc1 = nn.Linear(embedding_size, embedding_size)
        # Second fully connected layer for Classification
        self.fc2 = nn.Linear(embedding_size, num_classes)
      
    def forward(self, x):
        # Normalize Vector Input
        x = F.normalize(x, p=2, dim=len(x.size())-1)
        # Pass data through fc1
        x = self.fc1(x)
        # Pass data through fc2 (Classification Layer)
        x = self.fc2(x)
        return x

def train(model, loss_func, device, train_loader, optimizer, epoch, scheduler):
    model.train()
    if epoch == 600 or epoch == 800:
        scheduler.step()

    for batch_idx, (data, labels) in enumerate(train_loader):
        data, labels = data.to(device), labels.to(device)
        optimizer.zero_grad()
        embeddings = model(data)
        loss = loss_func(embeddings, labels)
        loss.backward()
        optimizer.step()
        if batch_idx % 20 == 0:
            print("Epoch {} Lr {} Iteration {}: Loss = {}".format(epoch,scheduler.get_lr(),batch_idx, loss))

def test(model, device, test_loader):
    model.eval()
    test_loss = 0
    with torch.no_grad():
        for data, target in test_loader:
            data, target = data.to(device), target.to(device)
            embeddings = model(data)
            loss = loss_func(embeddings, target)
            test_loss += loss
    print('\nTest set: Average loss: {:.4f}'.format(test_loss))

if __name__ == '__main__':
    
    #Torch Initializations
    torch.manual_seed(1)
    if torch.cuda.is_available():
        print("CUDA GPU will be Utilized")
        device = torch.device("cuda")
    else:
        print("CPU will be Utilized")
        device = torch.device("cpu")
    
    #Data loading and Preparations
    print("Loading and Preparing Dataset")
    pathDataDir = "/home/developer/Desktop/IoULabeling"
    a_file = open(os.path.join(pathDataDir,'trainingFeatures.pkl'), "rb")
    trainingData = pickle.load(a_file)
    a_file = open(os.path.join(pathDataDir,'testingFeatures.pkl'), "rb")
    testingData = pickle.load(a_file)
    
    #Structure Re-Formatting
    train_data = []
    test_data = []
    for label in trainingData:
        dataList = trainingData[label]
        for feature in dataList:
            train_data.append([torch.Tensor(feature), label])
        dataList = testingData[label]
        for feature in dataList:
            test_data.append([torch.Tensor(feature), label])
    
    #Creating Dataloaders
    trainloader = torch.utils.data.DataLoader(train_data, shuffle=True, batch_size=100)
    testloader = torch.utils.data.DataLoader(test_data, batch_size=100)
    
    ##Training Data Visualisation
    #for batch, (feature,label) in enumerate(trainloader):
    #txt = str(batch)+": "+str(feature.shape)+" "+str(label)
    #print(txt)
    #print("\n")
    
    #Creating Network
    print("Creating Network")
    num_classes = len(trainingData)
    embedding_size = 512
    
    net = Net(embedding_size,num_classes).to(device)
    print(net)
    
    #Training Parameters
    num_epochs = 1000
    optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
    loss_func = losses.CosFaceLoss(num_classes, embedding_size, margin=0.35, scale=64)
    scheduler = optim.lr_scheduler.StepLR(optimizer,step_size=1,gamma=0.1)

    for epoch in range(1, num_epochs+1):
        train(net, loss_func, device, trainloader, optimizer, epoch,scheduler)
        test(net,device,testloader)
    
    #Saving the Trained Model
    torch.save(net,os.path.join(pathDataDir,"Model.pt"))
    print("##### Model Saved #####")
```
Running this code keeps giving this error:

`
  File "/home/developer/src/ISAAC/packages/FeatureMap/LearningNetwork.py", line 113, in <module>
    train(net, loss_func, device, trainloader, optimizer, epoch,scheduler)

  File "/home/developer/src/ISAAC/packages/FeatureMap/LearningNetwork.py", line 41, in train
    loss = loss_func(embeddings, labels)

  File "/home/developer/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)

  File "/home/developer/anaconda3/envs/objTFOne/lib/python3.6/site-packages/pytorch_metric_learning/losses/base_metric_loss_function.py", line 34, in forward
    loss_dict = self.compute_loss(embeddings, labels, indices_tuple)

  File "/home/developer/anaconda3/envs/objTFOne/lib/python3.6/site-packages/pytorch_metric_learning/losses/large_margin_softmax_loss.py", line 106, in compute_loss
    cosine = self.get_cosine(embeddings)

  File "/home/developer/anaconda3/envs/objTFOne/lib/python3.6/site-packages/pytorch_metric_learning/losses/large_margin_softmax_loss.py", line 57, in get_cosine
    return self.distance(embeddings, self.W.t())

  File "/home/developer/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)

  File "/home/developer/anaconda3/envs/objTFOne/lib/python3.6/site-packages/pytorch_metric_learning/distances/base_distance.py", line 28, in forward
    mat = self.compute_mat(query_emb_normalized, ref_emb_normalized)

  File "/home/developer/anaconda3/envs/objTFOne/lib/python3.6/site-packages/pytorch_metric_learning/distances/dot_product_similarity.py", line 14, in compute_mat
    return torch.matmul(query_emb, ref_emb.t())

RuntimeError: mat1 dim 1 must match mat2 dim 0`

I have opened the dot_product_similarity.py and printed the dimentions of the matricies: 
`    def compute_mat(self, query_emb, ref_emb):
        print(query_emb.size())
        print(ref_emb.size())
        return torch.matmul(query_emb, ref_emb.t())`
Output was: `torch.Size([100, 230])
torch.Size([230, 512])`

So I feel the tranpose in the code means that I need to flip or change something in the input or layer structures ?
@KevinMusgrave

**Comment by KevinMusgrave** [comment]
This library assumes the output of your model is the embedding space. Right now your model is outputting class logits, so you should remove the fc2 layer.

**Comment by KevinMusgrave** [comment]
You also need to create an optimizer for CosFaceLoss. See [the documentation](https://kevinmusgrave.github.io/pytorch-metric-learning/losses/#cosfaceloss)

**Comment by kameel2311** [comment]
> This library assumes the output of your model is the embedding space. Right now your model is outputting class logits, so you should remove the fc2 layer.

Thank you for your response, the idea is that I want to embed the features to a new features space. So I thought fc2 will learn the Classification Weights and fc1 will give me the new features I need, such that I will then remove fc2 during the application of the net. Is that correct ? Or I only need fc1 and its output is the new features embeddings ?

**Comment by kameel2311** [comment]
> You also need to create an optimizer for CosFaceLoss. See [the documentation](https://kevinmusgrave.github.io/pytorch-metric-learning/losses/#cosfaceloss)

Yes I use the SGD optimizer from Torch: 

optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

**Comment by KevinMusgrave** [comment]
> Thank you for your response, the idea is that I want to embed the features to a new features space. So I thought fc2 will learn the Classification Weights and fc1 will give me the new features I need, such that I will then remove fc2 during the application of the net. Is that correct ? Or I only need fc1 and its output is the new features embeddings ?

You are correct, but CosFaceLoss contains the classification weights. So when you deploy the model, you won't need to remove any layers from Net, because the classification layer you're referring to is actually in CosFaceLoss.

> Yes I use the SGD optimizer from Torch:
> 
> optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

That's for your embedding model, but you must also create an optimizer for CosFaceLoss, because it contains the classification weights.

**Comment by kameel2311** [comment]
> > Thank you for your response, the idea is that I want to embed the features to a new features space. So I thought fc2 will learn the Classification Weights and fc1 will give me the new features I need, such that I will then remove fc2 during the application of the net. Is that correct ? Or I only need fc1 and its output is the new features embeddings ?
> 
> You are correct, but CosFaceLoss contains the classification weights. So when you deploy the model, you won't need to remove any layers from Net, because the classification layer you're referring to is actually in CosFaceLoss.
> 
> > Yes I use the SGD optimizer from Torch:
> > optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
> 
> That's for your embedding model, but you must also create an optimizer for CosFaceLoss, because it contains the classification weights.

Ouh so it has its own classification weights, this means that the output of fc1 will remain the same and should not be edited to be the number of output classes I have.

As for the optimizer, I am  quite new to using this library and thus used to always think that there is one optimizer for the whole network. Can you please write me a pseudo code and where shall I place it in my code ? I would be really thankfull

**Comment by KevinMusgrave** [comment]
Looks correct 👍

**Comment by kameel2311** [comment]
> Looks correct 👍

Thank you again for your time and support, wish you a blessed day ! 😊
