### ISSUE TITLE
Accuracy Metric CosFace Loss

### ISSUE THREAD

**Issue by kameel2311** [KevinMusgrave/pytorch-metric-learning#360]
@KevinMusgrave 

I have implemented a simple neural network for feature embedding, such that it is trained using the LMCL (CosFace Loss). The problem is I am not sure if there is a way to plot the accuracy of the training, since all I can retrieve is the Loss (Training and Validation) and for this loss type I dont know how much of this loss is too much or not, or even if the loss should be low, given we train on about 10k different classes.

So is there a way to get the predicted class of the validation data ? And what is the logical loss range for such a training method (having thousands of classes ?)

**Comment by KevinMusgrave** [comment]
You can use [AccuracyCalculator](https://kevinmusgrave.github.io/pytorch-metric-learning/accuracy_calculation/) to assess the quality of the feature embeddings. Here's some code I grabbed from the [MNIST example notebook](https://colab.research.google.com/github/KevinMusgrave/pytorch-metric-learning/blob/master/examples/notebooks/TripletMarginLossMNIST.ipynb)

```python
from pytorch_metric_learning.utils.accuracy_calculator import AccuracyCalculator
from pytorch_metric_learning import testers

### convenience function ###
def get_all_embeddings(dataset, model):
    tester = testers.BaseTester()
    return tester.get_all_embeddings(dataset, model)

### compute accuracy using AccuracyCalculator from pytorch-metric-learning ###
def test(train_set, test_set, model, accuracy_calculator):
    train_embeddings, train_labels = get_all_embeddings(train_set, model)
    test_embeddings, test_labels = get_all_embeddings(test_set, model)
    print("Computing accuracy")
    accuracies = accuracy_calculator.get_accuracy(test_embeddings, 
                                                train_embeddings,
                                                test_labels,
                                                train_labels,
                                                False)
    print("Test set accuracy (Precision@1) = {}".format(accuracies["precision_at_1"]))


# initialize
accuracy_calculator = AccuracyCalculator(include = ("precision_at_1",), k = 1)

# call this when you want to compute accuracy
# dataset1 will be used as the reference set for dataset2
test(dataset1, dataset2, model, accuracy_calculator)
```

**Comment by kameel2311** [comment]
@KevinMusgrave 

So technically I can use r_precision to find the r nearest neighbors and thus get a metric to see how good are my features clustered after the new embedding. But since I am trying to minimize the cosine distance between the feature vectors, does the K-NN algorithm utilize the Euclidean Distance , or can I set it to use the Cosine Similarity Instead ?

**Comment by KevinMusgrave** [comment]
By default, embeddings are normalized before computing euclidean distance, so the ranking of results will be the same as when using cosine similarity. Customizing the k-nn distance type is on my todo list (issue https://github.com/KevinMusgrave/pytorch-metric-learning/issues/349)

If you use R precision, you should set k like this: ```k = "max_bin_count"```

**Comment by kameel2311** [comment]
@KevinMusgrave 

Now I got the idea and the inituion behind the Metrics, I want to compute 3 metrics: r_Precision, mean_average_precision_at_r and the precision_at_1.

So I think I need to create 2 AccuracyCalculator Objects where I set k = 1 for precision_at_1, and max_bin_count for the others in the 2nd object, or will it automatically adapt k when computing precision_at_1 ?

**Comment by KevinMusgrave** [comment]
> So I think I need to create 2 AccuracyCalculator Objects where I set k = 1 for precision_at_1, and max_bin_count for the others in the 2nd object, or will it automatically adapt k when computing precision_at_1 ?

This will compute all 3:
```python
accuracy_calculator = AccuracyCalculator(
    include=("precision_at_1", "r_precision", "mean_average_precision_at_r"),
    k="max_bin_count",
)
```

> Trying out the **mean_average_precision_at_r** and the **r_precision metric** has given me the following error: `RuntimeError: The size of tensor a (70) must match the size of tensor b (1150) at non-singleton dimension 1` , any idea on how to overcome this issue ?

Can you provide more details? Where does the error occur?

**Comment by kameel2311** [comment]
@KevinMusgrave 

So for the accuracy calculation I have defined the following function:
`def test_ranking(train_set, test_set, model, accuracy_calculator):
    train_embeddings, train_labels = get_all_embeddings(train_set, model)
    test_embeddings, test_labels = get_all_embeddings(test_set, model)
    print("Computing accuracy")
    accuracies = accuracy_calculator.get_accuracy(test_embeddings, train_embeddings, test_labels, train_labels, False)
    #print("Test set accuracy (Precision@1) = {}".format(accuracies["precision_at_1"]))
    return accuracies'
`

Where the AccuracyCalculator Object is defined so:
`accuracy_calculatorR_Metrics = AccuracyCalculator(include = ("r_precision","mean_average_precision_at_r"), k = "max_bin_count" )
`
And the Validation error is calculated after the training function in the Epoch Forloop as such:
`acc2 = test_ranking(train_data,test_data,net,accuracy_calculatorR_Metrics)`

Where the train_data is a 11029 long List , where each element is a list of 2 elements: the first is the PyTorch Feature tensor of size [512], and the second element is the int label.

As for the test_data the same applied but is 1150 long.

So upon running, during the Accuracy Calculation the following error appears:
`Net(
  (fc1): Linear(in_features=512, out_features=512, bias=True)
)
Epoch 1 Lr [0.1] Iteration 0: Loss = 31.905092239379883
Epoch 1 Lr [0.1] Iteration 20: Loss = 28.845409393310547
Epoch 1 Lr [0.1] Iteration 40: Loss = 28.62357521057129
Epoch 1 Lr [0.1] Iteration 60: Loss = 29.207454681396484
Epoch 1 Lr [0.1] Iteration 80: Loss = 28.299787521362305
Epoch 1 Lr [0.1] Iteration 100: Loss = 27.81867218017578

Output from spyder call 'get_namespace_view':
  0%|          | 0/345 [00:00<?, ?it/s]
Test set: Average loss: 28.4215
100%|██████████| 345/345 [00:00<00:00, 514.35it/s]
100%|██████████| 36/36 [00:00<00:00, 206.40it/s]
Computing accuracy
Traceback (most recent call last):

  File "/home/developer/src/ISAAC/packages/FeatureMap/LearningNetwork.py", line 154, in <module>
    acc2 = test_ranking(train_data,test_data,net,accuracy_calculatorR_Metrics)

  File "/home/developer/src/ISAAC/packages/FeatureMap/LearningNetwork.py", line 73, in test_ranking
    accuracies = accuracy_calculator.get_accuracy(test_embeddings, train_embeddings, test_labels, train_labels, False)

  File "/home/developer/anaconda3/envs/objTFOne/lib/python3.6/site-packages/pytorch_metric_learning/utils/accuracy_calculator.py", line 410, in get_accuracy
    return self._get_accuracy(self.curr_function_dict, **kwargs)

  File "/home/developer/anaconda3/envs/objTFOne/lib/python3.6/site-packages/pytorch_metric_learning/utils/accuracy_calculator.py", line 413, in _get_accuracy
    return {k: v(**kwargs) for k, v in function_dict.items()}

  File "/home/developer/anaconda3/envs/objTFOne/lib/python3.6/site-packages/pytorch_metric_learning/utils/accuracy_calculator.py", line 413, in <dictcomp>
    return {k: v(**kwargs) for k, v in function_dict.items()}

  File "/home/developer/anaconda3/envs/objTFOne/lib/python3.6/site-packages/pytorch_metric_learning/utils/accuracy_calculator.py", line 305, in calculate_mean_average_precision_at_r
    self.label_comparison_fn,

  File "/home/developer/anaconda3/envs/objTFOne/lib/python3.6/site-packages/pytorch_metric_learning/utils/accuracy_calculator.py", line 125, in mean_average_precision_at_r
    at_r=True,

  File "/home/developer/anaconda3/envs/objTFOne/lib/python3.6/site-packages/pytorch_metric_learning/utils/accuracy_calculator.py", line 87, in mean_average_precision
    equality = is_same_label * relevance_mask

RuntimeError: The size of tensor a (70) must match the size of tensor b (1150) at non-singleton dimension 1`

**Comment by KevinMusgrave** [comment]
Sorry about that, I forgot that the labels returned by BaseTester have an extra dim which needs to be removed:

```python
....
train_embeddings, train_labels = get_all_embeddings(train_set, model)
test_embeddings, test_labels = get_all_embeddings(test_set, model)

# remove extra dim
train_labels = train_labels.squeeze(1)
test_labels = test_labels.squeeze(1)
....
```

**Comment by kameel2311** [comment]
> Sorry about that, I forgot that the labels returned by BaseTester have an extra dim which needs to be removed:
> 
> ```python
> ....
> train_embeddings, train_labels = get_all_embeddings(train_set, model)
> test_embeddings, test_labels = get_all_embeddings(test_set, model)
> 
> # remove extra dim
> train_labels = train_labels.squeeze(1)
> test_labels = test_labels.squeeze(1)
> ....
> ```

Perfect , works now. Thank you lots for your support !
