### ISSUE TITLE
Processing of two different datasets

### ISSUE THREAD

**Issue by PaulZgy** [KevinMusgrave/pytorch-metric-learning#366]
Hi kevin,

I have a task now, which is to jointly train two different models by metric loss. I have read similar questions [305](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/305), but I still have no idea.

I have encountered difficulties in processing the dataset. How should I deal with two completely different datasets? If you know, can you tell me how to do it?

Thanks a lot

**Comment by KevinMusgrave** [comment]
Can you describe the 2 datasets? How are they completely different?
