### ISSUE TITLE
Feature Request: Mean Reciprocal Rank (mRR) accuracy calculation

### ISSUE THREAD

**Issue by pavan-kalyan** [KevinMusgrave/pytorch-metric-learning#369]
I couldn't find this metric in the AccuracyCalculator. I think it would be helpful as some papers use this metric along with mAP.

I guess I could implement my own following [this](https://web.stanford.edu/class/cs276/handouts/EvaluationNew-handout-1-per.pdf), but it would be nice to have it as part of the library.

Love the library by the way.

**Comment by KevinMusgrave** [comment]
Agreed

**Comment by KevinMusgrave** [comment]
The dictionary returned by ```AccuracyCalculator.get_accuracy()``` now includes ```"mean_reciprocal_rank"```

Available in 1.1.0.dev1:

```
pip install pytorch-metric-learning==1.1.0.dev1
```
