### ISSUE TITLE
Centroid Triplet Loss (CTL)

### ISSUE THREAD

**Issue by codeandproduce** [KevinMusgrave/pytorch-metric-learning#374]
As implemented in this paper about [image retrieval](https://arxiv.org/pdf/2104.13643.pdf).

Happy to work on a pull request if there aren't any reasons to object!

**Comment by KevinMusgrave** [comment]
Available in 1.1.0.dev0:

```
pip install pytorch-metric-learning==1.1.0.dev0
```
