### ISSUE TITLE
Manifold similarity loss

### ISSUE THREAD

**Issue by Kingofolk** [KevinMusgrave/pytorch-metric-learning#383]
Would you please repoduce the manifold similarity loss proposed in <Ensemble deep manifold similarity learning using hard proxies>>
thanks a lot!

**Comment by KevinMusgrave** [comment]
Paper link https://openaccess.thecvf.com/content_CVPR_2019/papers/Aziere_Ensemble_Deep_Manifold_Similarity_Learning_Using_Hard_Proxies_CVPR_2019_paper.pdf

**Comment by KevinMusgrave** [comment]
Added in v2.2.0
