### ISSUE TITLE
custom loss functions

### ISSUE THREAD

**Issue by turovapolina** [KevinMusgrave/pytorch-metric-learning#391]
Dear @KevinMusgrave and all pytorch-metric-learning team,

I am facing a problem when I am trying to create custom loss function.
I tried to initialise new loss class using your example with BarebonesLoss (https://kevinmusgrave.github.io/pytorch-metric-learning/extend/losses/) and got this error when loss function is called:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-17-100c7805a166> in <module>
      1 for epoch in range(1, num_epochs+1):
----> 2     train(model, loss_func, mining_func,train_dataloader, optimizer, epoch)
      3     test(training_data, test_data, model, accuracy_calculator)

<ipython-input-16-446205750fbd> in train(model, loss_func, mining_func, train_loader, optimizer, epoch)
     12         indices_tuple = mining_func(embeddings, labels)
     13         print ('indices_tuple', indices_tuple)
---> 14         loss = loss_func(embeddings, labels, indices_tuple)
     15         loss.backward()
     16         optimizer.step()

~/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
   1049         if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1050                 or _global_forward_hooks or _global_forward_pre_hooks):
-> 1051             return forward_call(*input, **kwargs)
   1052         # Do not call functions when jit is used
   1053         full_backward_hooks, non_full_backward_hooks = [], []

~/opt/anaconda3/lib/python3.8/site-packages/pytorch_metric_learning/losses/base_metric_loss_function.py in forward(self, embeddings, labels, indices_tuple, ref_emb, ref_labels)
     35         labels = c_f.to_device(labels, embeddings)
     36         ref_emb, ref_labels = c_f.set_ref_emb(embeddings, labels, ref_emb, ref_labels)
---> 37         loss_dict = self.compute_loss(
     38             embeddings, labels, indices_tuple, ref_emb, ref_labels
     39         )

TypeError: compute_loss() takes 4 positional arguments but 6 were given
```

As I understand in BaseMetricLoss class (during "forward" method) "compute_loss" method is called with additional arguments ref_emb, ref_labels:
```
loss_dict = self.compute_loss(
            embeddings, labels, indices_tuple, ref_emb, ref_labels
```

however these arguments are not defined in compute_loss method in this class (so this really looks like a problem):
```
    def compute_loss(self, embeddings, labels, indices_tuple=None):
        """
        This has to be implemented and is what actually computes the loss.
        """
        raise NotImplementedError
```

Could you please help me or give me some tips how this can be resolved and also why this problem doesn't appear when I am using losses from package (like TripletMarginLoss).

pytorch-metric-learning version 1.0.0

Thank you very much in advance!
Best regards,
Polina

**Comment by KevinMusgrave** [comment]
Sorry about that I forgot to update the documentation. 

```compute_loss``` should take in 5 arguments. See [TripletMarginLoss](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/src/pytorch_metric_learning/losses/triplet_margin_loss.py) for an example.

**Comment by KevinMusgrave** [comment]
Also you're the BaseMetricLossFunction definition is confusing, because its arguments are different from what is actually used.

https://github.com/KevinMusgrave/pytorch-metric-learning/blob/d0e54d8f8ffc958f86f34b536f04f5c19914dff3/src/pytorch_metric_learning/losses/base_metric_loss_function.py#L15-L19

Just ignore it for now

**Comment by turovapolina** [comment]
Dear @KevinMusgrave,

Thank you very much for quick answer and for the explanation! Now everything is clear!
Changed the input of `compute_loss` to 5 arguments and problem was resolved.

Best regards,
Polina
