### ISSUE TITLE
Feature Request: Retrieve per-class metrics in AccuracyCalculator

### ISSUE THREAD

**Issue by mlw214** [KevinMusgrave/pytorch-metric-learning#394]
Currently, AccuracyCalculator calculates and returns the average over all classes for each metric. I believe it would be beneficial to also be able to calculate and retrieve metric scores per class. The core logic is already present with `avg_of_avgs=True`, you'd just need to be able to get at those class averages somehow.

**Comment by mlw214** [comment]
@KevinMusgrave, I'm going to take a stab at this, as I need it for my own analyses on a project. Let me know if there's a particular design or approach you want me to take

**Comment by KevinMusgrave** [comment]
I guess the simplest approach is to add an argument like ```return_per_class```, and if True, return ```average_per_class``` here:
https://github.com/KevinMusgrave/pytorch-metric-learning/blob/b8952778c753f25b91ef4ba50a66addeb5d2cbf7/src/pytorch_metric_learning/utils/accuracy_calculator.py#L22-L23

That argument would have to be passed down from the AccuracyCalculator class.

**Comment by KevinMusgrave** [comment]
Available in 1.1.0.dev0:

```
pip install pytorch-metric-learning==1.1.0.dev0
```
