### ISSUE TITLE
Running on CPU

### ISSUE THREAD

**Issue by shaikaz** [KevinMusgrave/pytorch-metric-learning#4]
Hi, 
I'm trying to run the GAN example on a device without GPU, I saw that most of the code can work on both GPU and non-GPU devices, but in `utils.stat_utils.get_knn` (and maybe in more places)  the line:
`index = faiss.index_cpu_to_all_gpus(cpu_index)` cannot run on non-GPU device, although I'm using the faiss-cpu package (that works on CPU). I'm only trying to run the examples on CPU just for testing, I still wish to run the code on GPU device, so I still wish to keep the GPU option available.
Does anyone got into this issue?
Thanks!
Shai 
BTW, Great package!

**Comment by KevinMusgrave** [comment]
In both occurrences of that "index_cpu_to_all_gpus", I'll add this if-statement:

```python
if faiss.get_num_gpus() > 0:
    index = faiss.index_cpu_to_all_gpus(cpu_index)
```

**Comment by shaikaz** [comment]
Thanks!

**Comment by KevinMusgrave** [comment]
@shaikaz faiss-cpu should work in the latest version (0.9.68)
