### ISSUE TITLE
Does your code have "losses.MINDSSC" or "losses.margin_loss" function?

### ISSUE THREAD

**Issue by tphankr** [KevinMusgrave/pytorch-metric-learning#402]
Does your code have "losses.MINDSSC" or "losses.margin_loss" function?
I am looking the MINDSSC or margin_loss in the losses folder but not see yet? 

Thank you.

**Comment by KevinMusgrave** [comment]
This library has:

- [MarginLoss](https://kevinmusgrave.github.io/pytorch-metric-learning/losses/#marginloss), code [here](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/src/pytorch_metric_learning/losses/margin_loss.py)
- [TripletMarginLoss](https://kevinmusgrave.github.io/pytorch-metric-learning/losses/#tripletmarginloss), code [here](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/src/pytorch_metric_learning/losses/triplet_margin_loss.py).

It does not have MINDSSC

**Comment by tphankr** [comment]
Thank you @KevinMusgrave. You can close this issue.
