### ISSUE TITLE
Easy Triplet Hard Negative Mining

### ISSUE THREAD

**Issue by KevinMusgrave** [KevinMusgrave/pytorch-metric-learning#41]
Add this method to the miners: http://openaccess.thecvf.com/content_WACV_2020/papers/Xuan_Improved_Embeddings_with_Easy_Positive_Triplet_Mining_WACV_2020_paper.pdf

**Comment by marijnl** [comment]
Let me pick this up. I think it's good practice to write a miner to get more familiar with this great package. 

Just adding this comment to avoid double work.

**Comment by marijnl** [comment]
I see there is some code available if I'm not mistaken https://github.com/littleredxh/EasyPositiveHardNegative

**Comment by KevinMusgrave** [comment]
This would be great, thanks!

**Comment by abby621** [comment]
Wondering if there are any updates on getting this added -- we (the authors) would be happy to answer any questions about the implementation if there are any sticking points.

**Comment by marijnl** [comment]
Sorry I totally forgot on finishing this.
Let me check later today

**Comment by marijnl** [comment]
Ok. I just checked. Some time ago I implemented a Miner that takes parameters for easy/hard positive/negative mining
see https://github.com/marijnl/pytorch-metric-learning/blob/ephn_loss/src/pytorch_metric_learning/miners/batch_easy_hard_miner.py
The miner is very similar to `BatchHardMiner` but it is a bit more configurable.

I think your paper is using `NCALoss` which is already implemented in PML

Will try to find some time this week to PR for this

**Comment by KevinMusgrave** [comment]
@marijnl If you need help finishing it, make a PR and I can take a look. Also if you need to test the miner in combination with a loss, use NTXentLoss instead of NCALoss.

**Comment by KevinMusgrave** [comment]
@marijnl Feel free to make a PR with your existing code

**Comment by marijnl** [comment]
Thanks, will do tomorrow

**Comment by KevinMusgrave** [comment]
Appreciate it!

**Comment by marijnl** [comment]
#245

Implements `BatchEasyHardMiner` that is by default configured as Easy Positive Hard Negative miner.

I think this should cover http://openaccess.thecvf.com/content_WACV_2020/papers/Xuan_Improved_Embeddings_with_Easy_Positive_Triplet_Mining_WACV_2020_paper.pdf. Please let me know if I misinterpret something @abby621 and apologies for not delivering this earlier this year as I promised back then
