### ISSUE TITLE
Error when "embeddings_come_from_same_source" is set to "True"

### ISSUE THREAD

**Issue by TalhaUsuf** [KevinMusgrave/pytorch-metric-learning#420]
Following _Line_ in this [script](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/537a5f56529eb2e7da2589fc1f98b6e07e0db2ce/src/pytorch_metric_learning/utils/accuracy_calculator.py#L213) is the culprit :warning:  :

```
match_counts - c_f.to_dtype(label_matches_itself, dtype=torch.long) <= 0
```

It gives following error (I have also attached image):

```
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.
```

![image](https://user-images.githubusercontent.com/47290815/153201271-00eb2278-1a89-454b-87d8-cc2f2764b5fc.png)

I have tested it both in **single GPU training** as well as in **multi-GPU training**

Can you please help in finding the fix :zap:  ?

**Comment by KevinMusgrave** [comment]
Are you using [torch.autocast](https://pytorch.org/docs/stable/amp.html)?

**Comment by TalhaUsuf** [comment]
> Are you using [torch.autocast](https://pytorch.org/docs/stable/amp.html)?

Yes I am using automatic mixed precision training using *amp_backend* set to *native*. 

:green_apple:  After your answer, I have tried my code without mixed precision and it works :clap: . But does your library **support** mixed precision training, it would be helpful since it greatly reduces the training speed?

**Comment by KevinMusgrave** [comment]
Yes it autocast should work. The bug is most likely in the ```c_f.to_dtype``` function. I will fix it later today.

**Comment by TalhaUsuf** [comment]
> Yes autocast should work. The bug is most likely in the `c_f.to_dtype` function. I will fix it later today.

Glad to hear that, can you please leave a reply here once you are done with the said fix 💡 so that I may get the latest fixed version. Thanks for this wonderful library.

**Comment by KevinMusgrave** [comment]
Can you try this version:

```python
pip install pytorch-metric-learning==1.1.1.dev0
```

**Comment by TalhaUsuf** [comment]
> Can you try this version, and let me know if it works
> 
> ```python
> pip install pytorch-metric-learning==1.1.1.dev0
> ```

Thank you very much, I'm glad to know, code now **works** on mixed-precision :heart:  :bulb:  I have tested the proposed solution with `2 x 2080 Ti` GPUs using `DDP` mode
