### ISSUE TITLE
Cannot allocate memory : Getting RAM full issue while using 110 GB RAM and 1024 memory queue size.

### ISSUE THREAD

**Issue by abhinav3** [KevinMusgrave/pytorch-metric-learning#421]
Hi Kevin,
I have around 15k images and around 6k labels for them. While training for the first epoch itself, I see that my 110GB RAM space is occupied and hence the trainnig stops with error:

`RuntimeError: [enforce fail at CPUAllocator.cpp:68] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 51380224 bytes. Error code 12 (Cannot allocate memory)`

I have below settings:
batch_size = 8
out_embedding_size = 2048 # final embedding size
memory_size = 1024 #XBM queue size 

Attaching the RAM usage snapshot.
<img width="1131" alt="Ram full" src="https://user-images.githubusercontent.com/7069488/153206740-52ff1c7a-606c-4a0a-bb91-3c5f288ab49c.png">

**Comment by KevinMusgrave** [comment]
Does this happen immediately at the beginning of training, or does the memory usage slowly increase as training progresses?

**Comment by abhinav3** [comment]
Actually the memory usage slowly increase as training progresses.

**Comment by KevinMusgrave** [comment]
I don't think there is a memory leak in CrossBatchMemory, because it has a fixed size memory, and the input tensors are always detached before being added to memory. 

Perhaps you can try it without cross batch memory, and see if the memory still increases over time.

**Comment by KevinMusgrave** [comment]
Here's a colab notebook where I use the same loss function: https://colab.research.google.com/drive/1AhnG-qVlT0S24eIjLAqLCNCuxlQEmHKk?usp=sharing 

It looks like cpu memory usage is constant. Are you saving loss values to an array without first detaching them? That would cause a memory leak. Otherwise I'm not sure what's causing it.

**Comment by abhinav3** [comment]
Thanks for the notebook. I figured and you correctly pointed out that I was not detaching the loss term using `loss.item()` while summing them to find the running average. After detaching them, I'm getting expected RAM usage.
Closing this issue. Thanks a lot!
