### ISSUE TITLE
Repository cannot handle hierarchal (multi-level) string labels

### ISSUE THREAD

**Issue by psturmfels** [KevinMusgrave/pytorch-metric-learning#422]
I've noticed that the repository cannot handle hierarchical string labels.  For example, if my labels are 'A' and 'B' at one level and 'A.1', 'A.2' and 'B.1', 'B.2', the BaseTester code (BaseTester.test()) crashes with conversion errors.

I believe I also understand the issue. In the "process_label" function in common_functions.py, there is code to convert the labels to numpy, then map them to their indices before selecting the correct hierarchy. The issue happens here: https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/src/pytorch_metric_learning/utils/common_functions.py#L90

On this line, if the labels have 2 dimensions (are hierarchical), instead of overwriting the original labels (which may be strings), the line inserts the index-mapped labels directly into the original numpy array, which is of type string. This means that the return array retains its type, which is string rather than integer. This means that the resultant label array cannot be converted to a torch tensor resulting in downstream issues.

The fix would be simple enough: change the map labels function to something like the following.
```
def map_labels(label_map, labels):
    labels = to_numpy(labels)
    new_labels = np.zeros(labels.shape)
    if labels.ndim == 2:
        for h in range(labels.shape[1]):
            new_labels[:, h] = label_map(labels[:, h], h)
    else:
        labels = label_map(labels, 0)
    return new_labels
```

**Comment by KevinMusgrave** [comment]
Thanks, I've made the change and added a test: https://github.com/KevinMusgrave/pytorch-metric-learning/commit/9607e6b00a7b9154a843b6e0b664541556c1f831

The new code is available:
```python
pip install pytorch-metric-learning==1.1.1.dev1
```

Make sure to pass in ```set_min_label_to_zero=True``` to your trainer/tester.

Let me know if it works.
