### ISSUE TITLE
Documentation for certain attributes seems to be incorrect

### ISSUE THREAD

**Issue by psturmfels** [KevinMusgrave/pytorch-metric-learning#425]
Part of the trainers read me states that:

> All loss and mining functions in pytorch-metric-learning have an attribute called record_these. This attribute is a list of strings, which are the names of other attributes that are worth recording for the purpose of analysis. For example, the record_these list for TripletMarginLoss is ["avg_embedding_norm, "num_non_zero_triplets"], so at each iteration you could log the value of trainer.loss_funcs["metric_loss"].avg_embedding_norm and trainer.loss_funcs["metric_loss"].num_non_zero_triplets. To accomplish this programmatically, you can loop through record_these and use the python function getattr to retrieve the attribute value.

This seems to be simply not true. First of all, the attribute is called _record_these. Second of all, the triplet margin loss has neither of the mentioned recorded attributes.

Is this designed to be work in progress?

**Comment by KevinMusgrave** [comment]
Sorry about that, I have updated that paragraph now: https://kevinmusgrave.github.io/pytorch-metric-learning/trainers/#basetrainer

**Comment by psturmfels** [comment]
This is awesome! Thank you
