### ISSUE TITLE
ZeroMeanregulariser

### ISSUE THREAD

**Issue by jamesrobertwilliams** [KevinMusgrave/pytorch-metric-learning#444]
I am trying to understand this regulariser, but I dont think I am able to :( looking at the paper it looks like it is for siamese or triplet pairs via contrastive loss - is this correct? Is it possible to use this say without contrastive loss? say arcfaceloss?

Whn I try and do:

`regularizers.ZeroMeanRegularizer(num_classes,=2 centers_per_class=1)`

it says `num_classes` is not defined. Also, how does it choose a center? what does `centers_per_class` mean here :(

**Comment by KevinMusgrave** [comment]
The documentation is incorrect. ZeroMeanRegularizer doesn't take in ```num_classes``` or ```centers_per_class```. 

So you can initialize it like ```ZeroMeanRegularizer()```

Sorry about that.

**Comment by KevinMusgrave** [comment]
> I am trying to understand this regulariser, but I dont think I am able to :( looking at the paper it looks like it is for siamese or triplet pairs via contrastive loss - is this correct? Is it possible to use this say without contrastive loss? say arcfaceloss?

Yeah I think you can pass this in as an ```embedding_regularizer```

**Comment by jamesrobertwilliams** [comment]
hi @KevinMusgrave ! so, you are saying, instead of:

```
     R = regularizers.ZeroMeanRegularizer()
        criterion = losses.ArcFaceLoss(num_classes=2, embedding_size=576, margin=1, scale=1,weight_regularizer=R)
```

I do:

```
```
     R = regularizers.ZeroMeanRegularizer()
        criterion = losses.ArcFaceLoss(num_classes=N, embedding_size=512, margin=1, scale=1,embedding_regularizer=R)
```

Have I understood you correctly?

Thank you once again.

**Comment by KevinMusgrave** [comment]
Correct

**Comment by jamesrobertwilliams** [comment]
Thank you @KevinMusgrave !
