### ISSUE TITLE
Use of DistributedLossWrapper with CrossBatchMemory

### ISSUE THREAD

**Issue by lyakaap** [KevinMusgrave/pytorch-metric-learning#447]
In ver=0.9.99, the following code works, but in ver=1.2.0, it fails because CrossBatchMemory doesn't inherit BaseMetricLossFunction.
```
loss_fn = losses.ContrastiveLoss(pos_margin=args.pos_margin, neg_margin=args.neg_margin)
loss_fn = losses.CrossBatchMemory(loss_fn, embedding_size=args.embdding_size, memory_size=args.memory_size)
loss_fn = pml_dist.DistributedLossWrapper(loss=loss_fn, efficient=False)
```

I'd like to know a current suitable way to use CrossBatchMemory in DDP settings.
Does anyone know that?

**Comment by KevinMusgrave** [comment]
Sorry about that. Can you try it with this new version?
```
pip install pytorch-metric-learning==1.2.1.dev0
```
For now, ```efficient=True``` isn't supported with ```CrossBatchMemory```.

**Comment by lyakaap** [comment]
It works by updating `pytorch-metric-learning==1.2.1.dev0`.
I appreciate for your quick response :)
