### ISSUE TITLE
Question about embeddings_come_from_same_source argument meaning

### ISSUE THREAD

**Issue by Sorrow321** [KevinMusgrave/pytorch-metric-learning#464]
Hi everyone!
What is the purpose of **embeddings_come_from_same_source** argument of [get_accuracy](https://kevinmusgrave.github.io/pytorch-metric-learning/accuracy_calculation/#getting-accuracy) function? Let's consider a case in which query == index and I set this argument to **True**. Will it skip the first nearest neighbor when calculating the metrics (because it will always be the same sample)? Or this is about something else?

**Comment by KevinMusgrave** [comment]
Yes that's correct, when `True` it will skip the first nearest neighbor.

**Comment by Sorrow321** [comment]
Thanks!
Yes, maybe it's better to rename it or add some small explanation in the docs

**Comment by KevinMusgrave** [comment]
Starting in [v1.5.2](https://github.com/KevinMusgrave/pytorch-metric-learning/releases/tag/v1.5.2), it does something more complicated than just skipping the first neighbor, so maybe a better argument name will be `query_in_ref`.

**Comment by KevinMusgrave** [comment]
It'll be `ref_includes_query`
