### ISSUE TITLE
Invalid triplets returned by Miner

### ISSUE THREAD

**Issue by CinnamonJui** [KevinMusgrave/pytorch-metric-learning#476]
```python
miner = miners.BatchHardMiner()
# Indices for anchor, positive and negative
a_i, p_i, n_i = miner(embeddings, labels)

# ALL anchor and positive pairs have same label
#  NO anchor and negative pairs have same label
torch.all(labels[a_i] == labels[p_i]), torch.any(labels[a_i] == labels[n_i])
```
The last line of above codes is `(tensor(True), tensor(False))`, and I expect the same for [Problematic_Embeddings.zip](https://github.com/KevinMusgrave/pytorch-metric-learning/files/8791162/Problematic_Embeddings.zip)

```python
pe = torch.load(r'Problematic_Embeddings.pt')
embeddings, labels = pe['embeddings'], pe['labels']

miner = miners.BatchHardMiner()
a_i, p_i, n_i = miner(embeddings, labels)

torch.all(labels[a_i] == labels[p_i]), torch.any(labels[a_i] == labels[n_i])
```
The last line of above codes returns `(tensor(False), tensor(False))`

The problem is gone if I replace the embeddings with a dummy one
```python
dummy = torch.rand(embeddings.shape)
a_i, p_i, n_i = miner(dummy, labels)

torch.all(labels[a_i] == labels[p_i]), torch.any(labels[a_i] == labels[n_i])
```

Does there exist some requirements for `embeddings` passed to `miner`?

**Comment by KevinMusgrave** [comment]
There was a bug in the way the maximum distances per anchor were computed. It's a pretty major bug, so thank you for bringing this to my attention.

I uploaded a new version which I think fixes the bug. Let me know if it works for you:
```
pip install pytorch-metric-learning==1.3.2
```

**Comment by CinnamonJui** [comment]
Thank you. It's my pleasure to make a contribution to this awesome project 👍 

and yes! It works!
I'll notify you in case I find any other bugs.
