### ISSUE TITLE
Add Circle Loss

### ISSUE THREAD

**Issue by AlenUbuntu** [KevinMusgrave/pytorch-metric-learning#48]
Hello:
I'd like to add Circle Loss into the package and have completed the coding. 

FYI, Here is the CVPR 2020 paper that introduces circle loss:
https://arxiv.org/abs/2002.10857

How can I add this to your repo?

**Comment by KevinMusgrave** [comment]
That would be awesome! Here's how I think it should be done:

1. The class name should be ```CircleLoss```
2. It should be located in ```losses/circle_loss.py```
3. It should be added to ```losses/__init__.py``` like this:
```python
...
from .arcface_loss import ArcFaceLoss
from .circle_loss import CircleLoss
from .contrastive_loss import ContrastiveLoss
...
```

4. Then the structure of the class should be like this:

```python
from .base_metric_loss_function import BaseMetricLossFunction

class CircleLoss(BaseMetricLossFunction):
    def __init__(self, your_args, **kwargs):
        super().__init__(**kwargs)
        # init stuff

    def compute_loss(self, embeddings, labels, indices_tuple):
        # We can discuss in the pull request what to do with indices_tuple
        # calculate and return the loss
```

Can you open a pull request? We can discuss it further there.
