### ISSUE TITLE
Why fill diagonal with zeroes in get_matches_and_diffs

### ISSUE THREAD

**Issue by BrunoCoric** [KevinMusgrave/pytorch-metric-learning#488]
In this function why are diagonal elements filled with zeros? 
When using for example SupConLoss and having two matrices that have the same labels (so the positive pair is always on the diagonal) the loss will always be 0.

```
def get_matches_and_diffs(labels, ref_labels=None):
    if ref_labels is None:
        ref_labels = labels
    labels1 = labels.unsqueeze(1)
    labels2 = ref_labels.unsqueeze(0)
    matches = (labels1 == labels2).byte()
    diffs = matches ^ 1
    if ref_labels is labels:
        matches.fill_diagonal_(0)
    return matches, diffs
```

**Comment by KevinMusgrave** [comment]
It only fills the diagonal with zeros if labels and ref_labels are the same object. The reason is that we don't want an embedding to form a positive pair with itself.
