### ISSUE TITLE
Lambda functions and DDP incompatibilities

### ISSUE THREAD

**Issue by s-rog** [KevinMusgrave/pytorch-metric-learning#5]
```
AttributeError: Can't pickle local object 'WeightRegularizerMixin.__init__.<locals>.<lambda>'
```

The use of lambda functions causes distributed training to fail due to the use of pickling in fork. I searched for lambdas in the repo and there are only around 10 instances, should be an easy fix?

**Comment by KevinMusgrave** [comment]
Should I change all of the lambdas to function definitions?

**Comment by s-rog** [comment]
Yeah, for my use case I changed the lambda function in `WeightRegularizerMixin` to a regular function and now it works in my multi GPU training setup (I'm using the arcface loss). This would make the library available for those with more substantial/production hardware.

I have not yet done any other testing though.

**Comment by KevinMusgrave** [comment]
Thanks for pointing this out. In the latest version, all the lambda expressions have been converted to function definitions. Hopefully it works with distributed data parallel now.

**Comment by s-rog** [comment]
Cheers, I'll give the update a try soon. Thanks for exposing metric learning in an easy to use API.

**Comment by s-rog** [comment]
`AttributeError: Can't pickle local object 'WeightRegularizerMixin.initialize_regularizer.<locals>.regularizer'`
@KevinMusgrave I think nested functions cannot be pickled either.

**Comment by KevinMusgrave** [comment]
Ah damn! K I'll fix that. At what point do you get the pickle error? When you create the DistributedDataParallel object, or at some other point?

**Comment by s-rog** [comment]
I think the error happens when fork is called. When I did my own testing to get it to work I just placed the dummy regularizer outside the class though I guess it can be a class function too, just not nested haha.

**Comment by KevinMusgrave** [comment]
Are you using the loss function within pytorch lightning? I'd just like a way to test my changes before pushing them.

**Comment by s-rog** [comment]
Yeah I'm calling arcface loss in training_step

**Comment by KevinMusgrave** [comment]
I removed all nested function definitions, so pickling loss functions works now. Hopefully that fixes it! *fingers crossed*

**Comment by s-rog** [comment]
Awesome, I'll test it out soon!
