### ISSUE TITLE
Does DistributedWrapper support two stream input?

### ISSUE THREAD

**Issue by NoTody** [KevinMusgrave/pytorch-metric-learning#502]
Hi, how does the DistributedWrapper support two stream input? I see the original implementation DistributedWrapper class only has three input with `def forward(self, embeddings, labels)` , but I want something like `self.miner(query_embed, labels, doc_embed, labels.clone()) ` in my implementation after wrapping miner/loss (e.g. `self.miner = pml_dist.DistributedMinerWrapper(self.miner)`).

**Comment by KevinMusgrave** [comment]
It doesn't support `ref_emb` and `ref_labels`. I'll have to think about how to add that functionality.

**Comment by NoTody** [comment]
I have attempted to implement this functionality and it seems to work correctly. Can I send a pull request for this?

**Comment by KevinMusgrave** [comment]
Yes please do

**Comment by KevinMusgrave** [comment]
Added in v1.6.0
