### ISSUE TITLE
dominant centers in subcenter arcface loss.

### ISSUE THREAD

**Issue by abaqusstudent** [KevinMusgrave/pytorch-metric-learning#508]
I am going through the subcenter arcface loss: 
https://kevinmusgrave.github.io/pytorch-metric-learning/losses/#subcenterarcfaceloss
collab [tutorial](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/examples/notebooks/SubCenterArcFaceMNIST.ipynb) on MINST and I would like to extract the dominant centers of each class.

I presume that this snippet:

```
outliers, dominant_centers = loss_func.get_outliers(
    embeddings, labels, threshold=75, return_dominant_centers=True
)
```

will give me the dominant centers for each class. So, in the case of MINST, I will get 10 centers each belonging to a single class. Is my understanding correct?

Following this, how do I work out which center belong to which class? Is there some natural ordering?
Apologies if this is a daft question!

thank you.

**Comment by KevinMusgrave** [comment]
I'm going to be honest, I can't really remember how this works. I think `dominant_centers` will be shape `(embedding_size, num_classes)`, so you get 1 dominant center per class. For example, `dominant_centers[:, 3]` is the dominant center for MNIST digit 4.

**Comment by abaqusstudent** [comment]
@KevinMusgrave yea when I ran the collab I got the dom centers of size 128,10 which is ok. In MNIST we can easily say 0-9 as labels.. but if I had labels 1000-1050.. can I still safely assume that the dom_center[:,0] is for label 1000?

**Comment by KevinMusgrave** [comment]
> or if I had say classes 0 and 1, can I assume that dom_center[:,0] is for label 0 (this is actually my use case!)?

Yes

**Comment by abaqusstudent** [comment]
> > or if I had say classes 0 and 1, can I assume that dom_center[:,0] is for label 0 (this is actually my use case!)?
> 
> Yes

Thank you :D
