### ISSUE TITLE
Miners for Circle Loss

### ISSUE THREAD

**Issue by Varghese-Kuruvilla** [KevinMusgrave/pytorch-metric-learning#516]
Hi,
Firstly thank you for the great work that you have done on this repository. I am trying to build a Person-ReID model using Circle Loss. I am a little confused as to whether the miners for Triplet Loss (BatchHard, Semihard etc) provided in this repository would work with Circle Loss. 

Could you please clarify? Thanks in advance!

**Comment by KevinMusgrave** [comment]
The triplets will be converted to pairs. Each triplet `a, p, n` becomes a positive pair `a, p` and a negative pair `a, n`. Then CircleLoss operates on these pairs.

**Comment by Varghese-Kuruvilla** [comment]
Thanks a lot for the clarification. 
Closing this question.
