### ISSUE TITLE
In your experience is cosine distance better than L2 distance? 

### ISSUE THREAD

**Issue by puzzlecollector** [KevinMusgrave/pytorch-metric-learning#521]
@KevinMusgrave When I am using contrastive loss for training a text semantic similarity ranking model, it seems like using L2 distance gives better MRR and average rank compared to cosine distance. This is contrary to what I've read/heard i.e. when dealing with high dimensional vectors (in my case, 768 dimension vector from BERT), it is better to use cosine distance. In your experience is it weird if L2 gave better performance than cosine distance when training a model with high dimensional vectors?

**Comment by KevinMusgrave** [comment]
Are you using `LpDistance`? By default, it normalizes embeddings so that the L2 norm is 1.

**Comment by puzzlecollector** [comment]
Yes I am using LpDistance (this is the default distance for ContrastiveLoss right?). Okay so it could have a pretty good performance because it is normalized L2 distance?

**Comment by KevinMusgrave** [comment]
> this is the default distance for ContrastiveLoss right? 

Yes

> Okay so it could have a pretty good performance because it is normalized L2 distance?

Yes I think normalized embeddings help.
