### ISSUE TITLE
Deployment of model trained using ArcFace Loss

### ISSUE THREAD

**Issue by TEnsorTHiru** [KevinMusgrave/pytorch-metric-learning#523]
I have trained a model using ArcFace Loss, IDK how to deploy the model using Flask and in sagemaker

**Comment by KevinMusgrave** [comment]
Your questions is more of a general pytorch deployment question. Here's a relevant blogpost though: https://developers.facebook.com/blog/post/2020/08/03/connecting-web-app-pytorch-model-using-amazon-sagemaker/
