### ISSUE TITLE
Accuracy metric evaluation

### ISSUE THREAD

**Issue by wconnell** [KevinMusgrave/pytorch-metric-learning#53]
k-nn should only run if included accuracy metrics require. Right now it runs even if you are only evaluating on `AMI` / `NMI`. I think an `include` parameter to `AccuracyCalculator` may be more useful for general application.

**Comment by KevinMusgrave** [comment]
Makes sense, so in addition to ```requires_clustering```, there'll be a ```requires_knn```, and in addition to ```exclude_metrics``` there'll be an ```include_metrics```.

**Comment by wconnell** [comment]
+1 to the `requires_knn`

I don't know that `include_metrics` needs to be added if it ultimately accomplishes the same thing as `exclude_metrics`. 

What I was getting at is that IMHO it feels bloated to default include many eval criteria. This may be a reality for ML researchers but not necessarily for applied library use. Granted, this depends on what purpose you would like this library to provide to users. I'm just giving my 2 cents as an "implementor" rather than "ML researcher". So, the `include_metrics` parameter is a design strategy that fits with the paradigm of my personal use. Ultimately I'm just giving my perspective -and I may be a minority!

**Comment by KevinMusgrave** [comment]
v0.9.84.dev0 has ```requires_knn``` and ```include```, and I changed the name of ```exclude_metrics``` to ```exclude```.

**Comment by KevinMusgrave** [comment]
This is now in v0.9.84
