### ISSUE TITLE
Tester & Accuracy questions

### ISSUE THREAD

**Issue by brianw0924** [KevinMusgrave/pytorch-metric-learning#552]
Hi, I have some questions about tester and accuracy.

1. I studied the example code but can't understand what's the difference between using `testers.BaseTester` then run `tester.test` and put `testers.GlobalEmbeddingSpaceTester` into `end_of_epoch_hook` then `trainer.train`?

2. How does testers.GlobalEmbeddingSpaceTester select probes(or queries) and gallery(search space) if I simply pass val_dataset in it? I guess it iterate through all embeddings in val_dataset and the search space is all the other embeddings?

3. If I want to split to probes and gallery (like person Reid), I should use `testers.BaseTester` then run `tester.test` instead of testers.GlobalEmbeddingSpaceTester, right?

     For example: pass `splits_to_eval = [('probes', ['gallery'])]` to `tester.test` and my val_dataset is {'probes': probes, 'gallery': gallery}

4. If I set `accuracy_calculator=AccuracyCalculator(k="max_bin_count")` in `testers.GlobalEmbeddingSpaceTester`, does it mean that if my class is `imbalanced`, the k-nn classification result is always the `majority` of the classes since the search space is all embeddings?

5. What is the type of accuracy metric in testers.GlobalEmbeddingSpaceTester?
(according to the example code, it print something like INFO:PML:New best accuracy! 0.1055039207090762)

6. Is there any metrics behave like rank-n accuracy? (a common metric for person re-identification)

Sorry for asking so many questions. I want to run a Reid-like task using this package, or is there any example code recommended for Reid?

Thank you

**Comment by KevinMusgrave** [comment]
> 1. I studied the example code but can't understand what's the difference between using `testers.BaseTester` then run `tester.test` and put `testers.GlobalEmbeddingSpaceTester` into `end_of_epoch_hook` then `trainer.train`?

I used `testers.BaseTester` for some of its internal functions like `get_all_embeddings`. Actually I could have used `testers.GlobalEmbeddingSpaceTester` for the same purpose. It doesn't make a difference in this case.

`tester.test` is the function called inside `end_of_epoch_hook`.

Passing `tester=testers.GlobalEmbeddingSpaceTester` into `end_of_epoch_hook` gives the hook access to the tester. At the end of each epoch, the hook calls `tester.test`. 

`trainer.train` starts the whole training/testing process. At the end of each epoch, the trainer calls `hook.end_of_epoch_hook`, which calls `tester.test`.


> 2. How does testers.GlobalEmbeddingSpaceTester select probes(or queries) and gallery(search space) if I simply pass val_dataset in it? I guess it iterate through all embeddings in val_dataset and the search space is all the other embeddings?

The default behavior is to use the `val_dataset` as both the query set and gallery. It computes the accuracy for each embedding in `val_dataset` by finding its nearest neighbors in `val_datastet`.

> 3. If I want to split to probes and gallery (like person Reid), I should use `testers.BaseTester` then run `tester.test` instead of testers.GlobalEmbeddingSpaceTester, right?
>    For example: pass `splits_to_eval = [('probes', ['gallery'])]` to `tester.test` and my val_dataset is {'probes': probes, 'gallery': gallery}

No you should still use `testers.GlobalEmbeddingSpaceTester`, and call `tester.test`. 

The `dataset_dict` should be `{'probes': probes, 'gallery': gallery}`, and the `splits_to_eval` should be `[('probes', ['gallery'])]`.


> 4. If I set `accuracy_calculator=AccuracyCalculator(k="max_bin_count")` in `testers.GlobalEmbeddingSpaceTester`, does it mean that if my class is `imbalanced`, the k-nn classification result is always the `majority` of the classes since the search space is all embeddings?

By "k-nn classification" I assume you mean computing a class based on a majority vote (like in [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html)). This metric is not yet implemented in AccuracyCalculator.

> 5. What is the type of accuracy metric in testers.GlobalEmbeddingSpaceTester?
>    (according to the example code, it print something like INFO:PML:New best accuracy! 0.1055039207090762)

`GlobalEmbeddingSpaceTester` returns a dictionary containing all the metrics that AccuracyCalculator computes. The print statement you are referring to comes from the `HookContainer` which by default uses `mean_average_precision_at_r` to determine the best accuracy during training.

> 6. Is there any metrics behave like rank-n accuracy? (a common metric for person re-identification)

No that metric isn't implemented.

> Sorry for asking so many questions. I want to run a Reid-like task using this package, or is there any example code recommended for Reid?

I don't know of any examples for reid. You might find this repo useful though: https://github.com/layumi/Person_reID_baseline_pytorch

**Comment by brianw0924** [comment]
Thank you for the reply

> By "k-nn classification" I assume you mean computing a class based on a majority vote (like in [scikit-learn](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html)). This metric is not yet implemented in AccuracyCalculator.


Does it mean you use knn to rank the similarity first, then calculate metric like mAP but not a traditional classification?

**Comment by KevinMusgrave** [comment]
Yes you can extend AccuracyCalculator:

```python
from pytorch_metric_learning.utils.accuracy_calculator import AccuracyCalculator

class YourCalculator(AccuracyCalculator):
    # method name must start with "calculate_"
    def calculate_rank_n(self, knn_labels, query_labels, **kwargs):
        # knn_labels is a 2d tensor, where knn_labels[i, j] is the label of the jth nearest neighbor of the ith query embeddings
        # query_labels is a 1d tensor where query_labels[i] is the label of the ith query embedding

    def requires_knn(self):
        return super().requires_knn() + ["rank_n"] 
```

**Comment by brianw0924** [comment]
Hi Kevin, 

If I my testing dataset is {'probes': probes, 'gallery': gallery} then what should I assign to `validation_split_name` in HookContainer?


```
Traceback (most recent call last):
  File "/home/brianw0924/SN850/exp/avatar_identification/main_reid.py", line 205, in <module>
    main(args)
  File "/home/brianw0924/SN850/exp/avatar_identification/main_reid.py", line 201, in main
    trainer.train(num_epochs=args.num_epochs)
  File "/home/brianw0924/anaconda3/lib/python3.9/site-packages/pytorch_metric_learning/trainers/base_trainer.py", line 93, in train
    if self.end_of_epoch_hook(self) is False:
  File "/home/brianw0924/anaconda3/lib/python3.9/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 90, in actual_hook
    best_epoch = self.save_models_and_eval(
  File "/home/brianw0924/anaconda3/lib/python3.9/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 173, in save_models_and_eval
    prev_best_epoch, _ = self.get_best_epoch_and_accuracy(
  File "/home/brianw0924/anaconda3/lib/python3.9/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 304, in get_best_epoch_and_accuracy
    accuracies, key = self.get_accuracies_of_best_epoch(
  File "/home/brianw0924/anaconda3/lib/python3.9/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 286, in get_accuracies_of_best_epoch
    table_name = self.record_group_name(tester, split_name)
  File "/home/brianw0924/anaconda3/lib/python3.9/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 364, in record_group_name
    [name.upper() for name in sorted(tester.reference_split_names[split_name])]
KeyError: 'val'

```

**Comment by KevinMusgrave** [comment]
Assuming `splits_to_eval = [('probes', ['gallery'])]`, then:

> 1. If I my testing dataset is {'probes': probes, 'gallery': gallery}. Can I assign anything to `validation_split_name` in `HookContainer`?

The `validation_split_name` must be one of the query split names. In your case, the only query split is `"probes"`, so set `validation_split_name = "probes"`. 

> 2. Should I combine all dataset into one dataset_dict? e.g. {'train': train, 'probes': probes, 'gallery': gallery} and passed to tester?

The `dataset_dict` only needs to contain the splits specified in `splits_to_eval`. So `dataset_dict = {'probes': probes, 'gallery': gallery}` should be sufficient.
