### ISSUE TITLE
knn_func & Distance object

### ISSUE THREAD

**Issue by brianw0924** [KevinMusgrave/pytorch-metric-learning#554]
Hi Kevin,

1. I want to implement my own distance from `distances.BaseDistance` and my `query_emb` have different amount from `ref_emb`.

```
        # Must return a tensor where output[j] represents 
        # the distance/similarity between query_emb[j] and ref_emb[j]
        def pairwise_distance(self, query_emb, ref_emb):
                raise NotImplementedError
``` 
However the document says need to implement pairwise_distance with only one index `j`.  How to deal with this scenario? 

2. I want implement my own distance function while testing ( for knn ranking )
    Then I found these:

```
knn_func: A callable that takes in 4 arguments (query, k, reference, embeddings_come_from_same_source) 
and returns distances, indices. Default is pytorch_metric_learning.utils.inference.FaissKNN.
```
What do the return `distances`, `indices` mean?

Thank you

**Comment by KevinMusgrave** [comment]
> However the document says need to implement pairwise_distance with only one index `j`. How to deal with this scenario?

You can assume that whenever `pairwise_distance` is called, the inputs have the same number of elements.

Actually though, `pairwise_distance` isn't called in many places. Try just implementing `compute_mat` and leaving `pairwise_distance` empty and it'll probably work.


> ```
> knn_func: A callable that takes in 4 arguments (query, k, reference, embeddings_come_from_same_source) 
> and returns distances, indices. Default is pytorch_metric_learning.utils.inference.FaissKNN.
> ```
> 
> What do the return `distances`, `indices` mean?

- `distances[i, j]` is the distance (or similarity) from the ith query to the jth nearest neighbor for that query.
- `indices[i, j]` is an index of the reference set, such that `reference[indices[i, j]]` is the jth nearest neighbor embedding of the ith query

You don't need to write code that returns `distances` or `indices` if you use `CustomKNN`. Write your custom distance function and wrap it with `CustomKNN`:

```python
from pytorch_metric_learning.utils.inference import CustomKNN

knn_func = CustomKNN(your_distance_fn)
```
