### ISSUE TITLE
triplets_past_filter

### ISSUE THREAD

**Issue by where2go947** [KevinMusgrave/pytorch-metric-learning#556]
Hi, thanks for your implementation on metric learning.
I saw some code like
```
from pytorch_metric_learning import reducers

reducer_fn = reducers.AvgNonZeroReducer(collect_stats=True)
loss_fn = losses.TripletMarginLoss(margin=self.margin, 
                                    swap=True, 
                                    distance=self.distance,
                                    reducer=reducer_fn,
                                    collect_stats=True)
num_non_zero_triplets = loss_fn.reducer.triplets_past_filter
```
But I don't find the source code of `triplets_past_filter` in class `AvgNonZeroReducer`. Maybe it has been removed or renamed. Could you give me some help?
Looking forward to your reply.

**Comment by where2go947** [comment]
Oh, maybe I got it
https://github.com/KevinMusgrave/pytorch-metric-learning/blob/345cb2b0cabfd39cc7a25ff2a81fa29adc3ea885/src/pytorch_metric_learning/reducers/threshold_reducer.py#L28-L60

is it the same as below?
```
num_non_zero_triplets = len(losses[losses>0])
```

**Comment by KevinMusgrave** [comment]
Yes that's correct. The code is a bit confusing, which is something I'm [hoping to change eventually](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/436)

**Comment by HengDora** [comment]
You can solve this problem by using version 1.0 of pytorch_metric_learning.

To install it, use the following command:

`pip install pytorch_metric_learning==1.0`
