### ISSUE TITLE
Warning when running examples/example_TrainWithClassifier

### ISSUE THREAD

**Issue by nguyennth** [KevinMusgrave/pytorch-metric-learning#56]
Hello, I've got the following warnings when running example_TrainWithClassifier.py:
Warning:root:No module named 'record_keeper'
Warning:root:No record_keeper, so no preset hooks are being returned.
Although I could still run the script but didn't got any results in the model folder.

Could you please let me know how I can fix it? Thank you in advance for your help.

**Comment by KevinMusgrave** [comment]
@nguyennth ```pip install record-keeper tensorboard```.
Then you'll also be able to do ```tensorboard --logdir=example_tensorboard``` and then go to localhost:6006 in your browser to see various plots etc.

**Comment by KevinMusgrave** [comment]
I should add the ```pip install record-keeper tensorboard``` to the warning so that people know how to get rid of it.

**Comment by nguyennth** [comment]
Thanks for your reply. It works well now!
