### ISSUE TITLE
is this reasonable? 

### ISSUE THREAD

**Issue by GorillaSX** [KevinMusgrave/pytorch-metric-learning#562]
https://github.com/KevinMusgrave/pytorch-metric-learning/blob/345cb2b0cabfd39cc7a25ff2a81fa29adc3ea885/src/pytorch_metric_learning/utils/distributed.py#L112

**Comment by KevinMusgrave** [comment]
See: https://github.com/KevinMusgrave/pytorch-metric-learning/issues/10#issuecomment-835461731

**Comment by zhaoyuac09** [comment]
I understand that why a scale of loss is introduced. But after examining the detailed implementation of the cross memory loss in distributed setting, all embs are already gathered so the loss is not just for part on the local GPU. In that sense, I do think we don't have to scale it by world_size. I have also tested in both single machine and distributed environment, only without scaling by world_size, the results reproduce.

**Comment by zhaoyuac09** [comment]
> I understand that why a scale of loss is introduced. But after examining the detailed implementation of the cross memory loss in distributed setting, all embs are already gathered so the loss is not just for part on the local GPU. In that sense, I do think we don't have to scale it by world_size. I have also tested in both single machine and distributed environment, only without scaling by world_size, the results reproduce.

Sorry, After a testing script, I can confirm that I was wrong, the current version with the loss scale is the current one (which can reproduce the exact same result with running on single GPU )
