### ISSUE TITLE
Make pytorch-metric-learning available on conda-forge

### ISSUE THREAD

**Issue by giswqs** [KevinMusgrave/pytorch-metric-learning#569]
It would be great to publish pytorch-metric-learning available on conda-forge. Otherwise, downstream packages of pytorch-metric-learning can't be made available on conda-forge. Making it available on conda-forge will benefit all downstream packages and numerous conda-forge users. 

Relevant issue: https://github.com/autogluon/autogluon/issues/612

**Comment by arturdaraujo** [comment]
I fully agree! If any help is needed I'm here
@KevinMusgrave

**Comment by KevinMusgrave** [comment]
What are the steps to publish to conda-forge?

**Comment by arturdaraujo** [comment]
@giswqs is quite an expert on this, but basically you fork stage recipes from conda forge, create a recipe and create PR to merge it. Once they accept the update is pretty much done automatically.

**Comment by arturdaraujo** [comment]
Chatgpt seems pretty good

Chatgpt:
Publishing a package on Conda Forge is a straightforward process that can be done in a few steps:

Create a new conda package: Create a new conda package by creating a new directory with the package name and adding the necessary files, such as the meta.yaml file that contains the package metadata.

Build the package: Use the conda build command to build the package. This will create a binary package that can be installed using conda.
Test the package: Test the package by installing it in a new environment and making sure it works as expected.

Create a fork of the conda-forge/staged-recipes repository: Go to https://github.com/conda-forge/staged-recipes, and create a fork of the repository.

Add your recipe to the fork: Add your recipe to the fork of the repository by creating a new directory with the package name and adding the necessary files, such as the meta.yaml file.

Submit a pull request: Submit a pull request to the conda-forge/staged-recipes repository with your recipe. This will trigger a build and test of your package on the conda-forge infrastructure.

Wait for the package to be accepted: Once your pull request is accepted, the package will be built and tested on the conda-forge infrastructure, and will be available on the conda-forge channel once the build is successful.

It's important to follow the conda-forge packaging guidelines, the packaging guide is available on the conda-forge website and in the conda-forge-pinning repository.

Keep in mind that publishing on conda-forge is a community-driven process and it's possible that your recipe will be reviewed by the community and may require some modifications before being accepted, so it's important to be open to feedback and willing to make changes to your recipe.

**Comment by giswqs** [comment]
@KevinMusgrave Looks like all package dependencies are already available on conda-forge. I can submit a PR to conda-forge and add you as a maintainer of the recipe. 

![image](https://user-images.githubusercontent.com/5016453/212352190-82687d7f-bcf4-4e10-befe-ec3a505ae802.png)

**Comment by arturdaraujo** [comment]
Here we go! @KevinMusgrave

**Comment by giswqs** [comment]
The Linux and OSX builds passed but the Windows build [failed](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=641143&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=2fb5b0a7-737c-5f5c-8f3f-f6db6174bacf&l=331). 

![image](https://user-images.githubusercontent.com/5016453/212358864-8fdc29cb-5f35-4bfa-adb0-e19ef0545651.png)

**Comment by arturdaraujo** [comment]
I think we can still publish as long as the Linux build passes. I'm not sure how conda-forge works but this should be good enough. Check this package I published: https://github.com/conda-forge/featurewiz-feedstock/pull/19/checks

By the way, I was only able to publish this package because I saw your tutorial on how to publish on conda-forge on youtube. So thanks for that! I struggled a lot with conda-forge documentation, so your material was incredibly helpful. When you decide to make a new tutorial you can count on my help.

**Comment by giswqs** [comment]
@arturdaraujo Great to know that you found my tutorials useful. I used to use conda-build for building conda-forge recipes, now grayskull makes it easier. I should probably update the tutorial. 

I think we need to pass all checks before the recipe can be accepted. Not sure why you only have Linux build listed.

**Comment by arturdaraujo** [comment]
I also wondered about that. Now that I looked back it seems it had something to do with the package I published being a noarch, which I'm not sure what it means for conda-forge tests. Anyway, I don't know if this applies to this package so I'm just guessing here.
https://github.com/conda-forge/staged-recipes/pull/19128#issuecomment-1144827721

**Comment by KevinMusgrave** [comment]
> @giswqs is quite an expert on this, but basically you fork stage recipes from conda forge, create a recipe and create PR to merge it. Once they accept the update is pretty much done automatically.

@arturdaraujo What do you mean by "automatically"? For future releases, do I still need to upload to my existing "metric-learning" conda channel?

@giswqs Thank you for creating the PR. What does it mean to be a maintainer of the conda-forge recipe? If in the future I need to change the dependencies, where would I do that?

**Comment by giswqs** [comment]
@KevinMusgrave Conda-forge will automatically retrieve the updated version from PyPI and automatically create a PR to update the package on conda-forge. We can set up an autobot merge for this. So essentially, there is nothing you need to do on your end. See [this](https://github.com/conda-forge/geemap-feedstock/pull/126) autobot merge example.

If you add/remove dependencies to the package, then we will need to manually create a PR to update the package. Simply add/remove the dependencies from the yml file. See [this](https://github.com/conda-forge/geemap-feedstock/pull/122/files) example. 

I can handle all the updates for the package, but it is always good to have an alternative maintainer in case I became disabled some day. 

Again, it is minimal maintenance work, e.g., adding/removing a few lines and creating a PR. Should take no more than 2-3 minutes, but it makes your package to a much wider audience.

**Comment by KevinMusgrave** [comment]
Ok sounds good. I posted the necessary comment in your PR.

**Comment by BastianZim** [comment]
> Maybe @BastianZim or @ndevenish can help here? We struggling to pass only the Windows test here (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=641143&view=logs&j=240f1fee-52bc-5498-a14a-8361bde76ba0&t=2fb5b0a7-737c-5f5c-8f3f-f6db6174bacf&l=331)
> 
> Here it is the stage-recipe: [conda-forge/staged-recipes#21720](https://github.com/conda-forge/staged-recipes/pull/21720)

The test fails because pytorch is not available for windows on conda-forge. You can just ignore that. Please change the recipe back to noarch and I'll review it.

Ref: https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-python

**Comment by KevinMusgrave** [comment]
Thanks @giswqs @BastianZim @arturdaraujo !
