### ISSUE TITLE
'ImageFolder' object has no attribute 'keys'

### ISSUE THREAD

**Issue by Kiwis2012** [KevinMusgrave/pytorch-metric-learning#582]
**Hello guys, i was using imagefolder and torch.utils.data.ConcatDataset as input training dataset,
but got an attribute error 'ImageFolder' object has no attribute 'keys', as below
i'm using pytorch-metric-learning 2.0.0 and torch  1.13.1+cu117
thanks in advance**

train_dataset=ImageFolder(f'{data_path_prefix}/train/',transform=train_transform)

> AttributeError                            Traceback (most recent call last)
> Cell In[20], line 1
> ----> 1 trainer = trainers.TrainWithClassifier(models,
>       2                                 optimizers,
>       3                                 batch_size,
>       4                                 loss_funcs,
>       5                                 mining_funcs,
>       6                                 train_dataset,
>       7                                 lr_schedulers = schedulers,
>       8                                 sampler=sampler,
>       9                                 dataloader_num_workers = 8,
>      10                                 loss_weights = loss_weights,
>      11                                 end_of_iteration_hook = hooks.end_of_iteration_hook,
>      12                                 end_of_epoch_hook = end_of_epoch_hook)
> 
> File ~\.conda\envs\with_gpu\lib\site-packages\pytorch_metric_learning\trainers\base_trainer.py:61, in BaseTrainer.__init__(self, models, optimizers, batch_size, loss_funcs, dataset, mining_funcs, iterations_per_epoch, data_device, dtype, loss_weights, sampler, collate_fn, lr_schedulers, gradient_clippers, freeze_these, freeze_trunk_batchnorm, label_hierarchy_level, dataloader_num_workers, data_and_label_getter, dataset_labels, set_min_label_to_zero, end_of_iteration_hook, end_of_epoch_hook)
>      59 self.loss_names = list(self.loss_funcs.keys())
>      60 self.custom_setup()
> ---> 61 self.verify_dict_keys()
>      62 self.initialize_models()
>      63 self.initialize_data_device()
> 
> File ~\.conda\envs\with_gpu\lib\site-packages\pytorch_metric_learning\trainers\base_trainer.py:266, in BaseTrainer.verify_dict_keys(self)
>     260 self.allowed_lr_scheduler_key_suffixes = {
>     261     "iteration": "_scheduler_by_iteration",
>     262     "epoch": "_scheduler_by_epoch",
>     263     "plateau": "_scheduler_by_plateau",
>     264 }
>     265 self.set_schema()
> --> 266 self.schema.verify(self)
>     267 self.verify_freeze_these_keys()
> 
> File ~\.conda\envs\with_gpu\lib\site-packages\pytorch_metric_learning\utils\key_checker.py:16, in KeyCheckerDict.verify(self, obj)
>      14 def verify(self, obj):
>      15     for k, v in self.children.items():
> ---> 16         self._verify_prop(getattr(obj, k, None), k, v)
> 
> File ~\.conda\envs\with_gpu\lib\site-packages\pytorch_metric_learning\utils\key_checker.py:25, in KeyCheckerDict._verify_prop(self, obj, obj_name, s)
>      23 if obj is not None:
>      24     keys = val(s.keys)
> ---> 25     for k in obj.keys():
>      26         assert any(
>      27             pattern.match(k) for pattern in c_f.regex_wrapper(keys)
>      28         ), "%s keys must be one of %s" % (obj_name, ", ".join(keys))
>      29     for imp_key in val(s.important):
> 
> AttributeError: 'ImageFolder' object has no attribute 'keys'

**Comment by KevinMusgrave** [comment]
In version 2, the `mining_funcs` argument became optional. So you need to either pass in all arguments by keyword, or swap the order of `train_dataset` and `mining_funcs`:

```python
TrainWithClassifier(
  models,
  optimizers,
  batch_size,
  loss_funcs,
  train_dataset,
  mining_funcs=mining_funcs,
  ...
)
```

**Comment by Kiwis2012** [comment]
thanks for the reply, i switched them and assigned the keywords, then it works. :)
