### ISSUE TITLE
train without metric learning

### ISSUE THREAD

**Issue by brianw0924** [KevinMusgrave/pytorch-metric-learning#584]
Hi, I feel this package is well-organized and easy to extend so I wanted to try using it in other scenario (without metric learning)

Is it possible to train with only classification task? or you recommend other way?

(I currently just set the metric loss weight to 0)

Thank you

**Comment by KevinMusgrave** [comment]
Setting the metric loss weight to 0 is the only way. You might want to look at other frameworks as well:

- https://github.com/rwightman/pytorch-image-models
- https://github.com/Lightning-AI/lightning
