### ISSUE TITLE
Measure Inference time while testing after pruning

### ISSUE THREAD

**Issue by ajktym94** [KevinMusgrave/pytorch-metric-learning#585]
I am trying to prune a model trained using the pytorch-metric-learning library for speeding up inference. The pruning is done based on the [Lottery Ticket Hypothesis](https://arxiv.org/abs/1803.03635) approach. I do structured pruning and remove certain layers. For testing inference speed, I use two methods:

Time1. Using the trunk model alone and just passing a random batched input of the shape (100,3,227,227)
Time2. Using the `GlobalEmbeddingSpaceTester.test()` function after passing the trunk and embedder models along with the test dataset

I take an average of 100 runs of both the above methods. I observe that, for the Time1 approach, the inference time increases with increasing pruning ratio. For the Time2 approach, the inference time decreases with increasing pruning ratio. Both the details are summarized below:

<html><body>

Model | Accuracy | Time1 (s) | Time2 (s)| Size (MB) | MACS | Params
-- | -- | -- | -- | -- | -- | --
Baseline | 0.8765 | 184 | 0 | 636.54 | 8959888640 | 42500160
2% Pruned | 0.787 | 179 | 4561 | 512.22 | 7211417700 | 33957326
4% Pruned | 0.691 | 148 | 4760 | 433.85 | 6118519438 | 28667218
6% Pruned | 0.6333 | 143 | 4779 | 389.48 | 5511440002 | 25759236
8% Pruned | 0.581 | 136 | 4684 | 357.11 | 5070684586 | 23667424

</body>
</html>

With the Time2 approach, why do we not see a speedup? Is it because of what happens inside the test() function?

**Comment by KevinMusgrave** [comment]
But it looks like the Time1 column is decreasing with pruning ratio?

**Comment by ajktym94** [comment]
> But it looks like the Time1 column is decreasing as the pruning ratio increases?

I am sorry. I messed it up. I have edited the comment. I meant Time2 which uses the `test()` function.

**Comment by KevinMusgrave** [comment]
That doesn't seem right. Time1 is for a single batch and takes over 100 seconds, while Time2 is for test() which runs on the whole dataset but takes less than a second.
