### ISSUE TITLE
Usage of sampler in validation

### ISSUE THREAD

**Issue by simonbuehler** [KevinMusgrave/pytorch-metric-learning#588]
hi,
first of all - awesome library, it really helped me with the loss functions and helpers all in one place, thanks!

im doing one-shot learning and extended it to a few shot learing by returning augmented versions of the one image per class for the embedding learning.

i'm using `MPerClassSampler1` ( just a extension to avoid returning duplicate labels in an iteration - interested in a pull request?) with m = 2 and training with softloss works fine. Now i changed from a simple loop to the `trainers.MetricLossOnly` helper. Training is fine but validation is fishy:

```js
INFO:PML:Computing accuracy for the val split w.r.t ['val']
INFO:PML:running k-nn with k=1
INFO:PML:embedding dimensionality is 1000
WARNING:PML:None of the query labels are in the reference set.
INFO:PML:running k-means clustering with k=284
INFO:PML:embedding dimensionality is 1000
WARNING clustering 284 points to 284 centroids: please provide at least 11076 training points
INFO:PML:New best accuracy! nan
```

I have 284 classes in the validation dataset ( disjoint from training) but the `None of the query labels are in the reference set.` message makes me think that that are no two images of the same class in the validation data ( only one per class exists on disk) and the `MPerClassSampler` with m=2 is not used so no validation can be made?

The other warning leaves me clueless and the nan as accuracy even more, here are the relevant pieces of my code:

```python

class Config():
        training_dir = "./data_train/"
        validation_dir = "./data_val/"
        models_output_dir = "./trained_models/"
        train_batch_size = 24
        train_number_epochs = 600


# Build Class disjoint training and validation set
    train_datafolder = datasets.ImageFolder(root=Config.training_dir)
    validation_datafolder = datasets.ImageFolder(root=Config.validation_dir)

    train_dataset = PokeIdNetDataset(imageFolderDataset=train_datafolder,
                                    transform=transforms.Compose([
                                        #
                                    ])
                                    )
    validation_dataset = PokeIdNetDataset(imageFolderDataset=validation_datafolder,
                                        transform=transforms.Compose([
                                            #
                                        ])
                                        )
    assert set(train_datafolder.classes).isdisjoint(
        set(validation_datafolder.classes))
    print("Datasets loaded: Training data has {} classes , validation data {} classes".format(
        len(train_datafolder.classes),  len(validation_datafolder.classes)))

    # Create the loss, miner, sampler, and package them into dictionaries

    # Set the loss function
    softloss_func = losses.SoftTripleLoss(len(train_datafolder.classes),
                                        1000,
                                        centers_per_class=10,
                                        gamma=0.1,
                                        margin=0.01).to(device)
    # Set the mining function
    mining_func = miners.TripletMarginMiner(
        margin=0.5, type_of_triplets="semihard"
    ).to(device)

    # Set the dataloader sampler
    mpSampler = MPerClassSampler1(
        train_datafolder.classes, 2, batch_size=Config.train_batch_size, length_before_new_iter=len(train_datafolder.classes), no_duplicate_labels=True)

    # Set model
    model = PokeIdNet().to(device)

    # Set optimizer
    trunk_optimizer = torch.optim.Adam(
        model.parameters(), lr=0.0001, weight_decay=0.0001)


    # Package the above stuff into dictionaries.
    models = {"trunk": model}
    optimizers = {
        "trunk_optimizer": trunk_optimizer,

    }
    loss_funcs = {"metric_loss": softloss_func}
    mining_funcs = {"tuple_miner": mining_func}

    ### pytorch-metric-learning stuff ###

    # Create the training and testing hooks
    record_keeper, _, _ = logging_presets.get_record_keeper(
        "example_logs", "example_tensorboard"
    )
    hooks = logging_presets.get_hook_container(record_keeper)
    dataset_dict = {"val": validation_dataset}
    model_folder = "example_saved_models"

    from pytorch_metric_learning.utils.accuracy_calculator import AccuracyCalculator

    # Create the tester
    tester = testers.GlobalEmbeddingSpaceTester(
        end_of_testing_hook=hooks.end_of_testing_hook,
        accuracy_calculator=AccuracyCalculator(k="max_bin_count"),
    )

    end_of_epoch_hook = hooks.end_of_epoch_hook(
        tester, dataset_dict, model_folder, test_interval=1, patience=1
    )

    # Create the trainer

    trainer = trainers.MetricLossOnly(
        models,
        optimizers,
        Config.train_batch_size,
        loss_funcs,
        train_dataset,
        mining_funcs=mining_funcs,
        dataloader_num_workers=1,
        iterations_per_epoch=int((next_even(len(train_datafolder.classes)) / Config.train_batch_size )* 2),
        sampler=mpSampler,
        end_of_iteration_hook=hooks.end_of_iteration_hook,
        end_of_epoch_hook=end_of_epoch_hook,
    )

    trainer.train(num_epochs=Config.train_number_epochs)

```

**Comment by KevinMusgrave** [comment]
> i'm using `MPerClassSampler1` ( just a extension to avoid returning duplicate labels in an iteration - interested in a pull request?) 

Can you explain what you mean by "duplicate labels"? The existing MPerClassSampler shouldn't be returning duplicate samples, and if you set the `batch_size` argument it should return exactly `m` samples per class. Any other behavior should probably be considered a bug.
 
> I have 284 classes in the validation dataset ( disjoint from training) but the `None of the query labels are in the reference set.` message makes me think that that are no two images of the same class in the validation data ( only one per class exists on disk) and the `MPerClassSampler` with m=2 is not used so no validation can be made?

Yes, your `dataset_dict` contains `{"val": validation_dataset}`. During testing, the `val` dataset is used as both the query and the reference. As you've mentioned, the `val` dataset only has 1 sample per class. So for each query sample, there are no samples to retrieve (other than itself). Therefore k-nn accuracy can't be computed. This is why the returned accuracy is NaN. (I felt that returning 0 accuracy would be misleading, because the lack of retrieval results is not an indication of the embedding quality.)

The other warning (`"WARNING clustering 284 points to 284 centroids: please provide at least 11076 training points"`) comes from `faiss` and is related to the k-means clustering step for computing the `AMI` and `NMI` metrics. You can exclude these accuracy metrics if you're not interested in them. 

As for sampling during validation, there is no straightforward way to do that with the existing testers. You might be able to override the [`get_all_embeddings` function](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/src/pytorch_metric_learning/testers/base_tester.py#L102) so that it uses a dataloader with your sampler

```python
class YourTester(GlobalEmbeddingSpaceTester):
        def get_all_embeddings(
            self,
            dataset,
            trunk_model,
            embedder_model=None,
            collate_fn=None,
            eval=True,
            return_as_numpy=False,
        ):
            if embedder_model is None:
                embedder_model = torch.nn.Identity()
            if eval:
                trunk_model.eval()
                embedder_model.eval()
            dataloader = <--------- # create your custom dataloader here
            embeddings, labels = self.compute_all_embeddings(
                dataloader, trunk_model, embedder_model
            )
            embeddings = self.maybe_normalize(embeddings)
            if return_as_numpy:
                return embeddings.cpu().numpy(), labels.cpu().numpy()
            return embeddings, labels

```

**Comment by simonbuehler** [comment]
thanks for the insights!

> Can you explain what you mean by "duplicate labels"? The existing MPerClassSampler shouldn't be returning duplicate samples, and if you set the `batch_size` argument it should return exactly `m` samples per class. Any other behavior should probably be considered a bug.

i wasn't precise here, it should mean class, i do want to have every class included once in one epoch so i just added this to keep track of already used classes

```diff
@@ -9 +9 @@
-class MPerClassSampler(Sampler):
+class MPerClassSampler1(Sampler):
@@ -16 +16 @@
-    def __init__(self, labels, m, batch_size=None, length_before_new_iter=100000):
+    def __init__(self, labels, m, batch_size=None, length_before_new_iter=100000, no_duplicate_labels=False):
@@ -24,0 +25 @@
+        self.no_duplicate_labels = no_duplicate_labels
@@ -44,0 +46 @@
+        used_labels = set()
@@ -50,0 +53,9 @@
+
+            curr_label_set = [
+                label for label in curr_label_set if label not in used_labels
+            ]
+            if self.no_duplicate_labels:
+                curr_label_set = [
+                    label for label in self.labels if label not in used_labels
+                ]
+
@@ -51,0 +63 @@
+                used_labels.add(label)
```

> Yes, your `dataset_dict` contains `{"val": validation_dataset}`. The default behavior during testing, is for the `val` dataset to be used as both the query and the reference. As you've mentioned, the `val` dataset only has 1 sample per class. So for each query sample, there are no samples to retrieve (other than itself). Therefore k-nn accuracy can't be computed. This is why the returned accuracy is NaN. (I felt that returning 0 accuracy would be misleading, because the lack of retrieval results is not an indication of the embedding quality.)

good to have the confirmation here and also NaN is precise wrt no result available

> The other warning (`"WARNING clustering 284 points to 284 centroids: please provide at least 11076 training points"`) comes from `faiss` and is related to the k-means clustering step for computing the `AMI` and `NMI` metrics. You can exclude these accuracy metrics from being computed at all if you're not interested in them.

i see, will look into that

> As for sampling during validation, there is no straightforward way to do that with the existing testers. You might be able to override the [`get_all_embeddings` function](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/src/pytorch_metric_learning/testers/base_tester.py#L102) so that it uses a dataloader with your sampler

i followed your approach and think i'm on the right track, but get a error which seems to come from the last batch not beeing filled completly... debugging it right now
```js
File "C:\Users\User\Downloads\pokeid\train copy.py", line 217, in get_all_embeddings
    embeddings, labels = self.compute_all_embeddings(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pytorch_metric_learning\testers\base_tester.py", line 97, in compute_all_embeddings
    all_q[s:e] = q
RuntimeError: The expanded size of the tensor (28) must match the existing size (32) at non-singleton dimension 0.  Target sizes: [28, 1000].  Tensor sizes: [32, 1000]
```

**Comment by KevinMusgrave** [comment]
Let me know if you need help with that error
