### ISSUE TITLE
Is there anything like AUC?

### ISSUE THREAD

**Issue by brianw0924** [KevinMusgrave/pytorch-metric-learning#594]
Hi, I'm looking for AUC metric from given paired dataset (like verification task), did you implemented?

thank you.

**Comment by KevinMusgrave** [comment]
That hasn't been implemented. Would this work? https://torchmetrics.readthedocs.io/en/stable/classification/auroc.html

**Comment by KevinMusgrave** [comment]
Ah ok, I probably won't implement it because there are other libraries that do the job.
