### ISSUE TITLE
Index Error method get_target_mask using CosFaceLoss 

### ISSUE THREAD

**Issue by jailsonpj** [KevinMusgrave/pytorch-metric-learning#616]
Hi, I'm trying to use the CosFace function but I always get this error in the "get_target_mask()" method:
![Captura de tela de 2023-04-21 16-56-58](https://user-images.githubusercontent.com/13952136/233725366-1970a341-28cc-4810-9501-c0203195424a.png)

Can you tell me if this is some version of the library? Can you help me?

Link Code: https://github.com/jailsonpj/master-project/blob/main/exp1_cosface_loss.ipynb

**Comment by KevinMusgrave** [comment]
Are your `labels` integers?

**Comment by jailsonpj** [comment]
I made the conversion to torch.float.

**Comment by KevinMusgrave** [comment]
Ok, they need to be integers instead of float

**Comment by jailsonpj** [comment]
I did the conversion to int but I keep showing error. so i converted to long and it worked.

Thanks a lot for the help
