### ISSUE TITLE
Why do I get diffrent results of outlier?

### ISSUE THREAD

**Issue by kurose635** [KevinMusgrave/pytorch-metric-learning#619]
Hello, Thank you for developing nice library. It is realy good libray for studying! 

I want to load and use a DML model that I have learned in one program in another program.
I implemented dml and outlier in the program that creates the model and confirmed that outlier is working properly.
This program saves model.
https://github.com/Raspberry765/deep-metric-learning/blob/main/SubCenterArcFaceMNIST_LoF_issue.ipynb
I got result  81/60000  using MNIST data.
In another program, when I loaded the model and applied outlier again, quite a few were detected as anomalies.
https://github.com/Raspberry765/deep-metric-learning/blob/main/outlier_only.ipynb
I got result  60000/60000  using MNIST data.
Why is this?

What can I do to achieve the same result?
best regards

**Comment by kurose635** [comment]
Hello Kevin, @KevinMusgrave
Thank you for reply message!
The following modifications and additions have been made to the program that creates the model.
`model.eval()
torch.save(model.state_dict(), '/content/drive/MyDrive/deep_metric_learning/model_dml.pth')
torch.save(optimizer.state_dict(), '/content/drive/MyDrive/deep_metric_learning/optim_dml.pth')
torch.save(loss_func.state_dict(), '/content/drive/MyDrive/deep_metric_learning/loss_func_dml.pth')
torch.save(loss_optimizer.state_dict(), '/content/drive/MyDrive/deep_metric_learning/loss_optim_dml.pth')
`
I saved model, optimizer_state, loss_func, loss_optimizer.
https://colab.research.google.com/drive/1hsgK7zjWdl6fdePETFK-quWMUmFWQYeU?hl=ja#scrollTo=Qd6N5KHMHWqK

And I loaded model, optimizer_state, loss_func, loss_optimizer.
https://github.com/Raspberry765/deep-metric-learning/blob/main/outlier_only.ipynb
```
model = Net().to(device) 
model.eval()
optimizer = optim.Adam(model.parameters(), lr=0.01)
loss_func = losses.SubCenterArcFaceLoss(num_classes=10, embedding_size=256).to(device) 
loss_optimizer = torch.optim.Adam(loss_func.parameters(), lr=1e-4)
#model.eval()
model = model.load_state_dict(torch.load("/content/drive/MyDrive/deep_metric_learning/model_dml.pth"))
#model.eval()#←Error
optimizer.load_state_dict(torch.load("/content/drive/MyDrive/deep_metric_learning/optim_dml.pth"))
loss_func.load_state_dict(torch.load("/content/drive/MyDrive/deep_metric_learning/loss_func_dml.pth"))
loss_optimizer.load_state_dict(torch.load("/content/drive/MyDrive/deep_metric_learning/loss_optim_dml.pth"))
#model.eval()#←Error
```
and, I did embeddings.
`train_embeddings, train_labels = get_all_embeddings(dataset1, model)`

The following error occurred

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-22-f9e220cbbf15>](https://localhost:8080/#) in <cell line: 1>()
----> 1 train_embeddings, train_labels = get_all_embeddings(dataset1, model)
      2 
      3 outliers, _ = loss_func.get_outliers(train_embeddings, train_labels.squeeze(1)) #train modelを異常検知している #lr=0.01 outlier=98
      4 print(f"There are {len(outliers)} outliers")
      5 imshow_many(dataset1, outliers)

1 frames
[/usr/local/lib/python3.9/dist-packages/pytorch_metric_learning/testers/base_tester.py](https://localhost:8080/#) in get_all_embeddings(self, dataset, trunk_model, embedder_model, collate_fn, eval, return_as_numpy)
    112             embedder_model = torch.nn.Identity()
    113         if eval:
--> 114             trunk_model.eval()
    115             embedder_model.eval()
    116         dataloader = c_f.get_eval_dataloader(

AttributeError: '_IncompatibleKeys' object has no attribute 'eval'


```
I tried to resolve the error by adding model.eval() with reference to the following site, but it did not resolve the issue.
https://pytorch.org/tutorials/beginner/saving_loading_models.html?highlight=eval
https://towardsdatascience.com/how-to-save-and-load-your-neural-networks-in-python-cb2063c4a7bd

Are there any other elements to add?
best regards

**Comment by KevinMusgrave** [comment]
Don't assign the result of `load_state_dict`. So instead of:

`model = model.load_state_dict(torch.load("/content/drive/MyDrive/deep_metric_learning/model_dml.pth"))` 

do this:

`model.load_state_dict(torch.load("/content/drive/MyDrive/deep_metric_learning/model_dml.pth"))`

**Comment by kurose635** [comment]
Hello Kevin, @KevinMusgrave
Thank you for reply message soon!
The program worked fine!!
Thank you so much for finding the mistake in my program.
Best regard!
