### ISSUE TITLE
Possible bug in assignment of initial_avg_query_norm

### ISSUE THREAD

**Issue by rheum** [KevinMusgrave/pytorch-metric-learning#620]
Hi all,

while trying to debug why my initial_avg_query_norm was always zero, I found that maybe it's actually a bug in base_distance.py. In contrast to the other assignments in the following lines, here (on line 82), a colon is used.

![image](https://user-images.githubusercontent.com/799919/235897474-4afceb55-da9c-430c-98d1-a291272cf83a.png)

https://github.com/KevinMusgrave/pytorch-metric-learning/blob/d9cd2ae6c8b7148224b3a6ca3cf6ff3e71e00030/src/pytorch_metric_learning/distances/base_distance.py#L82

**Comment by KevinMusgrave** [comment]
Thanks for catching this! The fixed version is now available:

```
pip install pytorch-metric-learning==2.1.1
```

**Comment by rheum** [comment]
Awesome, thanks
