### ISSUE TITLE
Clarification on Negative Pair Selection for NTXentLoss Function

### ISSUE THREAD

**Issue by ZhouMengjie** [KevinMusgrave/pytorch-metric-learning#622]
Dear Contributor, 

Regarding the NTXentLoss function in your code, I am trying to understand the negative pair selection process. Given a group of queries [0,1,2,3,4] and a group of references [0_,1_,2_,3_,4_], could you clarify which samples are considered as negative examples for sample 0? Are [1_,2_,3_,4_] the only negative examples or is it also [1,2,3,4,1_,2_,3_,4_]? Thank you for your help in clarifying this.

**Comment by KevinMusgrave** [comment]
The negatives come from the reference, so they will be `[1_,2_,3_,4_]`

So the loss for sample 0 will use:

- the positive pair `(0, 0_)`
- the negative pairs `(0, 1_), (0, 2_), (0, 3_), (0, 4_)`.
