### ISSUE TITLE
Different loss_fn for trunk and embedder

### ISSUE THREAD

**Issue by brianw0924** [KevinMusgrave/pytorch-metric-learning#623]
Hi, I wonder if there's a way to pass different loss_fn for trunk and embedder separately.

I'm currently just modifying the calculate_loss() and compute_embeddings() to return the trunk and embedder output, and then pass to different loss.

is there any easier way to do this?

**Comment by KevinMusgrave** [comment]
That's currently the easiest way

**Comment by brianw0924** [comment]
Thank you. Got it!
