### ISSUE TITLE
What is the meaning of label in TwoStreamMetricLoss

### ISSUE THREAD

**Issue by brianw0924** [KevinMusgrave/pytorch-metric-learning#626]
Hi, according to the doc of TwoStreamMetricLoss, the dataset need to return (anchor, posneg, label) 

but what does the label mean under (anchor, negative, label)?

is the label binary such that 1 if positive, 0 if negative?

**Comment by KevinMusgrave** [comment]
The variable naming `posneg` is confusing. Really it's just `(anchor, positive, label)`, so `label[i]` is the label for both `anchor[i]` and `positive[i]`.

I guess it was called `posneg` because the positive for one anchor will be the negative of another anchor that has a different label.

**Comment by brianw0924** [comment]
Thank you. Got it!

**Comment by brianw0924** [comment]
Thank you. Got it!
