### ISSUE TITLE
Running error about the tutorial of MoCoCIFAR10

### ISSUE THREAD

**Issue by yuxiaokang-source** [KevinMusgrave/pytorch-metric-learning#627]
When I run the tutorial https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/examples/notebooks/MoCoCIFAR10.ipynb, I get the error

![image](https://github.com/KevinMusgrave/pytorch-metric-learning/assets/59059267/49877ae7-6a84-4319-a69f-728bf17a32d3)
![image](https://github.com/KevinMusgrave/pytorch-metric-learning/assets/59059267/86e6c263-f7c8-4fd3-93e0-edeb55e7b67a)

Can you fix it?

**Comment by KevinMusgrave** [comment]
It seems to run in Google colab. Can you provide more details about your environment, like the version of pytorch, pytorch-metric-learning etc? Can you also provide more of the stack trace? Specifically what line does the error occur at?

**Comment by yuxiaokang-source** [comment]
> It seems to run in Google colab. Can you provide more details about your environment, like the version of pytorch, pytorch-metric-learning etc? Can you also provide more of the stack trace? Specifically what line does the error occur at?

my environment is below:
![image](https://github.com/KevinMusgrave/pytorch-metric-learning/assets/59059267/1e25bf06-ab04-42ca-b3af-7d33d1e6cb7a)

the error occurs
![image](https://github.com/KevinMusgrave/pytorch-metric-learning/assets/59059267/ddaf79e6-b773-4426-a1a2-ebc853fcf4df)

**Comment by KevinMusgrave** [comment]
It seems like the image size is not compatible with the model. Did you change the model or the dataset? Can you check the dimension of `imgK` and `imgQ` ?
