### ISSUE TITLE
Stats are not recorded TripletMarginMiner

### ISSUE THREAD

**Issue by nefagi-01** [KevinMusgrave/pytorch-metric-learning#628]
I am using the `TripletMarginMiner` and I set the attribute `collect_stats` to True in order to access stats like: `pos_pair_dist`, `neg_pair_dist`, `avg_triplet_margin`.

However no information is recorder during the usage of the mining function.

I checked the implementation and it seems to me that the function `set_stats` is correctly implemented but it's never called in the `mine` function or in the `forward` function.

**Comment by KevinMusgrave** [comment]
Fixed in v2.1.2

```
pip install pytorch-metric-learning==2.1.2
```
