### ISSUE TITLE
Sample triplets obtained with TripletMarginMiner to reduce memory usage

### ISSUE THREAD

**Issue by nefagi-01** [KevinMusgrave/pytorch-metric-learning#645]
Hello!

I am currently using `TripletMarginMiner` and I was wondering if there is a way for reducing the number of triplets obtained by some factor `0<p<1`. 

The thing is I am using `TripletMarginMiner` with `type_of_triplets="all"`  because I need both hard and semihard triplets. However this limits the size of my batches to be very small, because otherwise the number of triplets obtained explodes, causing the crash of the kernel because I run out of memory.

I would therefore like to still use `type_of_triplets="all"`, but instead of obtaining all the possible triplets, I would like to obtain only a fraction `p`, to avoid exceeding the memory usage.

Is there a way to do this?

Thank you 🙂

**Comment by KevinMusgrave** [comment]
This feature doesn't exist yet.

Does the memory error happen outside of the mining function? If so, one workaround is to simply truncate or randomly sample the output indices:

```python
a,p,n = miner(embeddings, labels)

# truncate
a,p,n = a[:max_t], p[:max_t], n[:max_t]

# or randomly sample
import numpy as np
random_idx = np.random.choice(np.range(len(a)), size=max_t, replace=False)
a,p,n = a[random_idx], p[random_idx], n[random_idx]
```
