### ISSUE TITLE
Can MatchFinder implement the query library?

### ISSUE THREAD

**Issue by ZH-UCAS** [KevinMusgrave/pytorch-metric-learning#647]
Hello! Thank you for developing this great library. It helps me try metric learning a lot.
I am conducting a binary classification task. I want to use feature vectors for similarity calculation to assist in the final test results.

I want to create a feature vector query library. My model has already obtained a set of labeled feature vectors, and I want to use MatchFinder to select the most representative feature vectors as the query library. Each time a test feature vector is obtained, it will be queried against the query library to determine the classification.

I am unsure how to implement this. Could you provide a simple example, or explain how MatchFinder can be used in this way? As a beginner, I hope you don't mind if I have any questions.

**Comment by KevinMusgrave** [comment]
`MatchFinder` and `InferenceModel` don't help with selecting the most representative vectors. The assumption is that you've decided what vectors to use as the library, and `MatchFinder` and `InferenceModel` will tell you if two embeddings should be considered a "match" or what the nearest embeddings are etc.

In case you haven't seen it, here's a notebook showing how to use `MatchFinder` and `InferenceModel`: https://colab.research.google.com/github/KevinMusgrave/pytorch-metric-learning/blob/master/examples/notebooks/Inference.ipynb
