### ISSUE TITLE
Face-Recognition

### ISSUE THREAD

**Issue by ShaikSarfraj-tech** [KevinMusgrave/pytorch-metric-learning#65]
I unable to install the "tkinter module" in Pycharm platform.
And it is showing "No module named tkinter"
please find the error and debug the error.
Thank You.
[face_rec.txt](https://github.com/KevinMusgrave/pytorch-metric-learning/files/4498793/face_rec.txt)

**Comment by KevinMusgrave** [comment]
This seems unrelated to pytorch-metric-learning. If you'd like to learn how to use this library, you can check out some of the [examples](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/examples/README.md)
