### ISSUE TITLE
how implement combining trunk model and embedding model without pytorch metric learning-based trainer and tester

### ISSUE THREAD

**Issue by sofpya** [KevinMusgrave/pytorch-metric-learning#656]
1. At first, I implement Pytorch Metric learning-based Subcenter Loss example successfully.
2. based on the subcenter loss program, I want to build the architecture including the trunk model and embedding mode like the MetricLossOnly.ipynb
3. In the MetricLossOnly.ipynb, the trainer and tester are encapsulated too deeply. I can't add new function such as recoding  and save the training loss and validation loss. 
4. how to implement the two model (trunk and embedding) based on SubCenterArcFaceMNIST.ipynb

**Comment by KevinMusgrave** [comment]
Something like this:

```python
for (data, labels) in dataloader:
   embeddings = embedder(trunk(data))
   loss = loss_fn(embeddings, labels)
   loss.backward()
   optimizer.step()
   optimizer.zero_grad() 
```

**Comment by sofpya** [comment]
Thank you for your timely reply. I still have a question.
1. How to predict the new class images using Inference.ipynb？
2. I use 'sklearn.metrics' to draw the confusion matrix, is it correct?

**Comment by sofpya** [comment]
I find a problem.:
SubcenterArcFace Loss uses the cosine distance, but the AccuracyCulator uses the L2 distance by 'FaisssKMeans'.
Is there different distance measure that may lead to some different effects in loss and accuracy calculations?

**Comment by sofpya** [comment]
I find a problem.:
SubcenterArcFace Loss uses the cosine distance, but the AccuracyCulator uses the L2 distance by 'FaisssKMeans'.
Is there different distance measure that may lead to some different effects in loss and accuracy calculations?

**Comment by KevinMusgrave** [comment]
> 1. How to predict the new class images using Inference.ipynb？

The inference module doesn't have class prediction functions yet. I suggest using something like [sklearn.neighbors.KNeighborsClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html). See this related issue: https://github.com/KevinMusgrave/pytorch-metric-learning/issues/583

> 2. I use 'sklearn.metrics' to draw the confusion matrix, is it correct?

Yeah, you just need to predict the class of each image first using the KNeighborsClassifier I mentioned above.

> SubcenterArcFace Loss uses the cosine distance, but the AccuracyCulator uses the L2 distance by 'FaisssKMeans'.

Try this:

```python
from pytorch_metric_learning.distances import CosineSimilarity
from pytorch_metric_learning.utils.inference import CustomKNN

knn_func = CustomKNN(CosineSimilarity())
AccuracyCalculator(knn_func=knn_func)
```

**Comment by sofpya** [comment]
Thank you for your help. 
I train a new dataset including 6 classes with 10 images on the training dataset now. When I training, there is a warning about 'WARNING clustering 38 points to 6 centroids: please provide at least 234 training points
dict_keys(['AMI', 'NMI', 'mean_average_precision_at_r', 'precision_at_1', 'r_precision'])'.  How to address it?

**Comment by sofpya** [comment]
Thank you for your help.
I train a new dataset including 6 classes with 10 images on the training dataset now.
1. When I training, there is a warning about 'WARNING clustering 38 points to 6 centroids: please provide at least 234 training points dict_keys(['AMI', 'NMI', 'mean_average_precision_at_r', 'precision_at_1', 'r_precision'])'.
2. the training loss is a dropping trend, but the validation loss didn't.
3. validation dataset of Umap visualization doesn't cluster
 How to address it?

**Comment by sofpya** [comment]
why the model didn't do eval ( model.eval ())for accuracy in  SubCenterArcFaceMNIST.ipynb?
Because, when I do the inference with the same validation dataset using the same epoch training weight,  the value of accuracy metrics has a big difference with the accuracy of validation of training processing.
1. I also use the same code with AccuracyCalculator
2. My prediction of inference is correct in the following code?
`trunk, trunk_output_size = Trunk_embedder_model(DEVICE)
embedder = embedder_model(trunk_output_size, EMBEDDING_SIZE, DEVICE)
classifier = classifier_model(EMBEDDING_SIZE, N_CLASS, DEVICE)
trunk.load_state_dict(torch.load(TRUNK_MODEL, map_location=DEVICE))
embedder.load_state_dict(torch.load(EMBEDDER_MODEL, map_location=DEVICE))
classifier.load_state_dict(torch.load(CLASSIFIER_MODEL, map_location=DEVICE))
trunk.to(DEVICE)
trunk.eval()
embedder.to(DEVICE)
embedder.eval()
classifier.to(DEVICE)
classifier.eval()
# Define image preprocessing transformations
transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

# Build dataloaders for validation and train datasets
test_dataset, test_dataloader = build_dataloader(
    batch_size=64,
    root_dir=TEST_DATASET_PATH,
    transform=transform,
    shuffle=False,
    num_workers=18,
)
train_dataset, train_dataloader = build_dataloader(
    batch_size=64,
    root_dir=TRAIN_DATASET_PATH,
    transform=transform,
    shuffle=False,
    num_workers=18,
)

# Initialize prediction results and true labels
all_predictions = []
all_labels = []
knn_func = CustomKNN(CosineSimilarity())
accuracy_calculator = AccuracyCalculator(include=("precision_at_1","NMI", "AMI", "r_precision", "mean_average_precision_at_r" ), k=1, knn_func=knn_func)
a,b,c,accuracy1,NMI, AMI, precision_at_1, r_precision, mean_average_precision_at_r = accuracy(train_dataset, test_dataset, trunk, embedder,classifier, accuracy_calculator, 1)
with torch.no_grad():
    # Get embeddings for validation and train datasets
    train_embeddings, train_labels = get_all_embeddings_trunk_embedder(train_dataset, trunk, embedder, DEVICE)
    test_embeddings, test_labels = get_all_embeddings_trunk_embedder(test_dataset, trunk, embedder, DEVICE)
    train_labels = train_labels.squeeze(1)
    test_labels = test_labels.squeeze(1)
    logits = classifier(test_embeddings)
    _, predicted = torch.max(logits, 1)
    accuracy_classfier = accuracy_score(test_labels.cpu().numpy(), predicted.cpu().numpy())
    print(f'Accuracy1: {accuracy_classfier * 100:.2f}%')

    print("Computing accuracy")
    accuracies = accuracy_calculator.get_accuracy(
        test_embeddings, test_labels, train_embeddings, train_labels, False
    )
    print(accuracies.keys())
    NMI = accuracies["NMI"]
    AMI = accuracies["AMI"]
    precision_at_1 = accuracies["precision_at_1"]
    r_precision = accuracies["r_precision"]
    mean_average_precision_at_r = accuracies["mean_average_precision_at_r"]
    print("Test set accuracy (NMI) = {}".format(NMI))
    print("Test set accuracy (AMI) = {}".format(AMI))
    print("Test set accuracy (precision_at_1) = {}".format(precision_at_1))
    print("Test set accuracy (r_precision) = {}".format(r_precision))
    print("Test set accuracy (mean_average_precision_at_r) = {}".format(mean_average_precision_at_r))

    # Fit KNN classifier on training embeddings
    knn = KNeighborsClassifier(n_neighbors=3)
    knn.fit(train_embeddings.cpu().numpy(), train_labels.cpu().numpy())

    # Predict on validation embeddings
    predictions = knn.predict(test_embeddings.cpu().numpy())
    confusion_matrixs = confusion_matrix(test_labels.cpu().numpy(), predictions)
    print("Confusion Matrix:", confusion_matrixs)

    # Save predictions and true labels
    all_predictions.extend(predictions)
    all_labels.extend(test_labels.cpu().numpy())

accuracy1 = accuracy_score(test_labels.cpu().numpy(), predictions)
print("Accuracy:", accuracy1)
output_file_path = os.path.join(MODEL_PATH,"test_evaluation_results_100epoch.txt")
with open(output_file_path, "w") as output_file:
    output_file.write("accuracy_classfier: {}\n".format(accuracy_classfier))
    output_file.write("accuracy1: {}\n".format(accuracy1))
    output_file.write("NMI: {}\n".format(NMI))
    output_file.write("AMI: {}\n".format(AMI))
    output_file.write("Precision@1: {}\n".format(precision_at_1))
    output_file.write("R-Precision: {}\n".format(r_precision))
    output_file.write("Mean Average Precision@R: {}\n".format(mean_average_precision_at_r))
# Calculate confusion matrix
confusion_mat = confusion_matrix(all_labels, all_predictions)
print("Confusion Matrix2:")
print(confusion_mat)

# Visualize confusion matrix
labels = np.unique(all_labels)
num_classes = len(labels)

fig, ax = plt.subplots()
im = ax.imshow(confusion_mat, cmap='Blues')

# Set axis labels
ax.set_xticks(np.arange(num_classes))
ax.set_yticks(np.arange(num_classes))
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)

# Add values to each cell
for i in range(num_classes):
    for j in range(num_classes):
        text = ax.text(j, i, confusion_mat[i, j], ha='center', va='center', color='white')

# Add colorbar
cbar = ax.figure.colorbar(im, ax=ax)

# Set plot title and labels
ax.set_title("Confusion Matrix")
ax.set_xlabel("Predicted Label")
ax.set_ylabel("True Label")

# Automatically adjust layout
plt.tight_layout()

# Save the confusion matrix plot
plt.savefig(os.path.join(MODEL_PATH, "tst_confusion_matrix_100epoch.png"))

# Show the plot
plt.show()
`

**Comment by KevinMusgrave** [comment]
> why the model didn't do eval ( model.eval ())for accuracy in SubCenterArcFaceMNIST.ipynb?

You're right, `.eval()` should be called on all models in the notebook.

**Comment by sofpya** [comment]
why is difference between the validation dataset accuracy of training processing and validation dataset accuracy of inference using  AccuracyCalculator with same training weight

**Comment by KevinMusgrave** [comment]
I don't understand your question. Can you reword it or paste in some code?

**Comment by sofpya** [comment]
1. I used the AccuracyCalculator to calculate the Validation dataset's metric during training processing.
2. I employed the training weight of epoch N to predict the Validation dataset's metric using AccuracyCalculator  in the inference.
3. However the metrics result of 1 , 2  is different. In theory, shouldn't the two results be the same?

**Comment by KevinMusgrave** [comment]
Yeah they should be the same. I'd have to see some code in order to determine what the problem is.

**Comment by sofpya** [comment]
The following code is my training code and inference code, Please check it, what the problem is.
1. Training:
`writer = SummaryWriter(SAVE_TENSORBOARD)

# Image transformations
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.Normalize(MEAN, STD),
])


TRAIN_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.Normalize(MEAN, STD),
    RandomHorizontalFlip(p=0.5),  # 随机水平翻转（概率为0.5）
    RandomVerticalFlip(p=0.5),  # 随机垂直翻转（概率为0.5）
    #ColorJitter(brightness=0.5, contrast=0.5)  # 随机调整颜色
])

# Train Dataloader
train_dataset, train_loader = build_dataloader(
    batch_size=BATCH_SIZE,
    root_dir=TRAIN_DATASET,
    transform=TRAIN_transform,
    shuffle=True,
    num_workers=18
)

# Val Dataloader
val_dataset, val_loader = build_dataloader(
    batch_size=BATCH_SIZE,
    root_dir=VAL_DATASET,
    transform=transform,
    shuffle=False,
    num_workers=18
)
# Define model
model = ResNet18(embedding_size=EMBEDDING_SIZE, pretrained=False).to(DEVICE)
model = torchvision.models.resnet18(pretrained=True)
model_output_size = model.fc.in_features
model.fc = nn.Linear(model_output_size, 64)
model.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=Learning_rate)
scheduler = StepLR(optimizer, step_size=30, gamma=0.1)
num_epochs = 100
loss_func = losses.ContrastiveLoss(pos_margin=1, neg_margin=0, distance=CosineSimilarity())

knn_func = CustomKNN(CosineSimilarity())
accuracy_calculator = AccuracyCalculator(include=("precision_at_1","NMI", "AMI", "r_precision", "mean_average_precision_at_r" ), k='max_bin_count', knn_func=knn_func)
###########train###################
def train(model, loss_func, device, train_loader, optimizer, epoch):
    model.train()
    total_loss = 0.0  # Initialize total loss
    num_batches = 0  # Initialize batch count
    for batch_idx, (data, labels) in enumerate(train_loader):
        data, labels = data.to(device), labels.to(device)
        optimizer.zero_grad()
        embeddings = model(data)
        loss = loss_func(embeddings, labels)
        loss.backward()  
        optimizer.step()
        total_loss += loss.item()  # Accumulate loss
        num_batches += 1  # Count batch
        if batch_idx % 10 == 0:
            print("Epoch {} Iteration {}: Train Loss = {}".format(epoch, batch_idx, loss))
    avg_train_loss = total_loss / num_batches  # Compute average loss
    print('Epoch{}:Average Train Loss={}'.format(epoch, avg_train_loss))
    return avg_train_loss
##########test##################
def accuracy(train_set, test_set, model, accuracy_calculator, epoch):
    with torch.no_grad():
        model.eval()
        train_embeddings, train_labels = get_all_embeddings(train_set, model, DEVICE)
        test_embeddings, test_labels = get_all_embeddings(test_set, model, DEVICE)
        print('label shape:', test_labels.shape)
        train_labels = train_labels.squeeze(1)
        test_labels = test_labels.squeeze(1)
        test_loss = loss_func(test_embeddings, test_labels)
        print("Computing accuracy")
        accuracies = accuracy_calculator.get_accuracy(
            test_embeddings, test_labels, train_embeddings, train_labels, False
        )
    print(accuracies.keys())
    NMI = accuracies["NMI"]
    AMI = accuracies["AMI"]
    precision_at_1 = accuracies["precision_at_1"]
    r_precision = accuracies["r_precision"]
    mean_average_precision_at_r = accuracies["mean_average_precision_at_r"]
    print("Epoch {} : Test Loss = {}".format(epoch,  test_loss))
    print("Test set accuracy (NMI) = {}".format(NMI))
    print("Test set accuracy (AMI) = {}".format(AMI))
    print("Test set accuracy (precision_at_1) = {}".format(precision_at_1))
    print("Test set accuracy (r_precision) = {}".format(r_precision))
    print("Test set accuracy (mean_average_precision_at_r) = {}".format(mean_average_precision_at_r))

    # umap visualization
    reducer = umap.UMAP()
    train_embeddings_umap = reducer.fit_transform(train_embeddings.cpu().numpy())
    test_embeddings_umap = reducer.transform(test_embeddings.cpu().numpy())

    plt.figure(figsize=(12, 10))
    plt.scatter(train_embeddings_umap[:, 0], train_embeddings_umap[:, 1], c=train_labels.cpu().numpy(), cmap='Spectral',
                s=5)
    plt.colorbar(boundaries=np.arange(7) - 0.5).set_ticks(np.arange(6))
    plt.savefig(os.path.join(SAVE_umap, f'train_embeddings_epoch_{epoch}.png'))

    plt.figure(figsize=(12, 10))
    plt.scatter(test_embeddings_umap[:, 0], test_embeddings_umap[:, 1], c=test_labels.cpu().numpy(), cmap='Spectral',
                s=5)
    plt.colorbar(boundaries=np.arange(7) - 0.5).set_ticks(np.arange(6))
    plt.savefig(os.path.join(SAVE_umap, f'test_embeddings_epoch_{epoch}.png'))

    return test_loss, NMI, AMI, precision_at_1, r_precision, mean_average_precision_at_r
for epoch in range(1, num_epochs + 1):
    train_loss = train(model, loss_func, DEVICE, train_loader, optimizer, epoch)
    val_loss, NMI, AMI, precision_at_1, r_precision, mean_average_precision_at_r = accuracy(train_dataset, val_dataset, model, accuracy_calculator, epoch)
    torch.save(model.state_dict(), f'{SAVE_PATH}/model_epoch_{epoch}.pth')
   # umap visualization

    writer.add_scalar('Loss/train', train_loss, epoch)  # Record train loss
    writer.add_scalar('Learning rate', optimizer.param_groups[0]['lr'], epoch)  # Record learning rate
    writer.add_scalar('Loss/val', val_loss, epoch)  # Record validation loss
    writer.add_scalar('NMI/val', NMI, epoch)  # Record validation accuracy
    writer.add_scalar('AMI/val', AMI, epoch)  # Record validation accuracy
    writer.add_scalar('precision_at_1/val', precision_at_1, epoch)  # Record validation accuracy
    writer.add_scalar('r_precision/val', r_precision, epoch)  # Record validation accuracy
    writer.add_scalar('mean_average_precision_at_r/val', mean_ave
`
2. inference 
`
# Define model
#model = ResNet18(embedding_size=EMBEDDING_SIZE, pretrained=False).to(DEVICE)

model = torchvision.models.resnet18(pretrained=False)
# Get the number of features before the final layer
model_output_size = model.fc.in_features

# Replace the final layer with a new fully connected layer
# that produces a 64-dimensional output
model.fc = nn.Linear(model_output_size, 64)

# Move model to device and possibly wrap it for multi-GPU training
model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
model.to(DEVICE)
model.eval()

# Define image preprocessing transformations
transform = transforms.Compose([
    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
])

# Build dataloaders for validation and train datasets
test_dataset, test_dataloader = build_dataloader(
    batch_size=64,
    root_dir=TEST_DATASET_PATH,
    transform=transform,
    shuffle=False,
    num_workers=18,
)
train_dataset, train_dataloader = build_dataloader(
    batch_size=64,
    root_dir=TRAIN_DATASET_PATH,
    transform=transform,
    shuffle=False,
    num_workers=18,
)
def cosine_distance(u, v):
    return 1.0 - (u @ v.T) / (np.linalg.norm(u) * np.linalg.norm(v))


# Initialize prediction results and true labels
all_predictions = []
all_labels = []
knn_func = CustomKNN(CosineSimilarity())
accuracy_calculator = AccuracyCalculator(include=("precision_at_1","NMI", "AMI", "r_precision", "mean_average_precision_at_r" ), k='max_bin_count', knn_func=knn_func)


with torch.no_grad():
    # Get embeddings for validation and train datasets
    train_embeddings, train_labels = get_all_embeddings(train_dataset, model, DEVICE)
    test_embeddings, test_labels = get_all_embeddings(test_dataset, model, DEVICE)
    train_labels = train_labels.squeeze(1)
    test_labels = test_labels.squeeze(1)
    print("Computing accuracy")
    accuracies = accuracy_calculator.get_accuracy(
        test_embeddings, test_labels, train_embeddings, train_labels, False )

    print(accuracies.keys())
    NMI = accuracies["NMI"]
    AMI = accuracies["AMI"]
    precision_at_1 = accuracies["precision_at_1"]
    r_precision = accuracies["r_precision"]
    mean_average_precision_at_r = accuracies["mean_average_precision_at_r"]
    print("Test set accuracy (NMI) = {}".format(NMI))
    print("Test set accuracy (AMI) = {}".format(AMI))
    print("Test set accuracy (precision_at_1) = {}".format(precision_at_1))
    print("Test set accuracy (r_precision) = {}".format(r_precision))
    print("Test set accuracy (mean_average_precision_at_r) = {}".format(mean_average_precision_at_r))



    # umap visualization
    reducer = umap.UMAP()
    train_embeddings_umap = reducer.fit_transform(train_embeddings.cpu().numpy())
    test_embeddings_umap = reducer.transform(test_embeddings.cpu().numpy())

    plt.figure(figsize=(12, 10))
    plt.scatter(train_embeddings_umap[:, 0], train_embeddings_umap[:, 1], c=train_labels.cpu().numpy(), cmap='Spectral',
                s=5)
    plt.colorbar(boundaries=np.arange(7) - 0.5).set_ticks(np.arange(6))
    plt.savefig(os.path.join(SAVE_umap, f'train_embeddings.png'))

    plt.figure(figsize=(12, 10))
    plt.scatter(test_embeddings_umap[:, 0], test_embeddings_umap[:, 1], c=test_labels.cpu().numpy(), cmap='Spectral',
                s=5)
    plt.colorbar(boundaries=np.arange(7) - 0.5).set_ticks(np.arange(6))
    plt.savefig(os.path.join(SAVE_umap, f'test_embeddings.png'))

    # Fit KNN classifier on training embeddings
    knn = KNeighborsClassifier(n_neighbors=3, metric=cosine_distance)
    knn.fit(train_embeddings.cpu().numpy(), train_labels.cpu().numpy())

    # Predict on validation embeddings
    predictions = knn.predict(test_embeddings.cpu().numpy())
    confusion_matrixs = confusion_matrix(test_labels.cpu().numpy(), predictions)
    print("Confusion Matrix:", confusion_matrixs)

    # Save predictions and true labels
    all_predictions.extend(predictions)
    all_labels.extend(test_labels.cpu().numpy())

accuracy1 = accuracy_score(test_labels.cpu().numpy(), predictions)
print("Accuracy1:", accuracy1)
output_file_path = os.path.join(PATHS, "evaluation_results.txt")
with open(output_file_path, "w") as output_file:
    output_file.write("Accuracy1: {}\n".format(accuracy1))
    output_file.write("NMI: {}\n".format(NMI))
    output_file.write("AMI: {}\n".format(AMI))
    output_file.write("Precision@1: {}\n".format(precision_at_1))
    output_file.write("R-Precision: {}\n".format(r_precision))
    output_file.write("Mean Average Precision@R: {}\n".format(mean_average_precision_at_r))

# Calculate confusion matrix
confusion_mat = confusion_matrix(all_labels, all_predictions)
print("Confusion Matrix2:")
print(confusion_mat)

# Visualize confusion matrix
labels = np.unique(all_labels)
num_classes = len(labels)

fig, ax = plt.subplots()
im = ax.imshow(confusion_mat, cmap='Blues')

# Set axis labels
ax.set_xticks(np.arange(num_classes))
ax.set_yticks(np.arange(num_classes))
ax.set_xticklabels(labels)
ax.set_yticklabels(labels)

# Add values to each cell
for i in range(num_classes):
    for j in range(num_classes):
        text = ax.text(j, i, confusion_mat[i, j], ha='center', va='center', color='white')

# Add colorbar
cbar = ax.figure.colorbar(im, ax=ax)

# Set plot title and labels
ax.set_title("Confusion Matrix")
ax.set_xlabel("Predicted Label")
ax.set_ylabel("True Label")

# Automatically adjust layout
plt.tight_layout()

# Save the confusion matrix plot
plt.savefig(os.path.join(PATHS,"confusion_matrix.png" ))

# Show the plot
plt.show()

`

**Comment by KevinMusgrave** [comment]
Are some of the training metrics the same as the inference metrics? For example, are precision_at_1, r_precision, and mean_average_precision_at_r calculated during training the same as the values calculated during inference?

**Comment by sofpya** [comment]
the training metrics are same as the inference metrics including  precision_at_1, r_precision, and mean_average_precision_at_r,NMI, AMI. However, the value of metrics of training is different with  inference of that

**Comment by KevinMusgrave** [comment]
Some things I noticed:

- The transform during training uses `MEAN`, and `STD`, but the transform during inference uses `[0.485, 0.456, 0.406], [0.229, 0.224, 0.225])`. Are you sure they are the same values?
- During training you use `VAL_DATASET` as the path for your query set, but during inference you use `TEST_DATASET_PATH`. Are these paths different? If so that would explain the different accuracy metrics, since during training you are computing accuracy using the validation set, and during inference you are computing accuracy using the test set.

**Comment by sofpya** [comment]
1. The values of MEAN and STD are exactly the same during training and inference.
2. To verify the validity of the code, the TEST_DATASET_PATH used in the inference code is the Validation dataset used in the training process
3. But the accuracy is different

**Comment by KevinMusgrave** [comment]
Here's another possible issue:

During training, you convert the images to tensor before resizing:

```python
    transforms.ToTensor,
    transforms.Resize,
    transforms.Normalizee
```

But during inference, you resize before converting to tensor:

```python
    transforms.Resize,
    transforms.ToTensor,
    transforms.Normalizee
```

The [PyTorch documentation](https://pytorch.org/vision/stable/generated/torchvision.transforms.Resize.html) says:

"The output image might be different depending on its type: when downsampling, the interpolation of PIL images and tensors is slightly different, because PIL applies antialiasing. This may lead to significant differences in the performance of a network. Therefore, it is preferable to train and serve a model with the same input types. See also below the antialias parameter, which can help making the output of PIL images and tensors closer."

**Comment by sofpya** [comment]
Thank you so much. The problem has been solved.
