### ISSUE TITLE
how to train using classfier without trainer

### ISSUE THREAD

**Issue by sofpya** [KevinMusgrave/pytorch-metric-learning#657]
```
contrastive_loss = losses.ContrastiveLoss(pos_margin=1, neg_margin=0, distance=CosineSimilarity())
# Set the classification loss:
classification_loss = torch.nn.CrossEntropyLoss()
muti_losses = [classification_loss, contrastive_loss]
loss_func = losses.MultipleLosses(muti_losses, weights=[0.5, 1.0])
   for batch_idx, (data, labels) in enumerate(train_loader):
          data, labels = data.to(device), labels.to(device)
          trunk_optimizer.zero_grad()
          embedder_optimizer.zero_grad()
          classifier_optimizer.zero_grad()
          # trunk model train
          trunk_out = trunk(data)
          embeddings = embedder(trunk_out)
          logits = classifier(embeddings)
          loss = loss_func(logits, labels)
          loss.backward()  
          trunk_optimizer.step()
          embedder_optimizer.step()
          classifier_optimizer.step()
```

File "/home/envs/Pytorch_Metric_Learning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/Pytorch_Metric_Learning/lib/python3.8/site-packages/pytorch_metric_learning/losses/multiple_losses.py", line 44, in forward
    loss_func(embeddings, labels, curr_indices_tuple) * self.weights[i]
  File "/home/Pytorch_Metric_Learning/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() takes 3 positional arguments but 4 were given

**Comment by KevinMusgrave** [comment]
`MultipleLosses` is only compatible with PML's tuple losses.

Compute the loss manually instead:

```python
loss = classification_loss(logits, labels)*0.5 + contrastive_loss(embeddings, labels)
loss.backward()
```
