### ISSUE TITLE
Add MultipleNegativesRanking Loss

### ISSUE THREAD

**Issue by mcschmitz** [KevinMusgrave/pytorch-metric-learning#664]
Hi all!

I'd be great if we could add MultipleNegativesRankingLoss as used in the sentece bert model and introduced in [Efficient Natural Language Response Suggestion for Smart Reply](https://arxiv.org/pdf/1705.00652.pdf).
I can provide a PR if you're interested.

**Comment by KevinMusgrave** [comment]
A PR would be very much appreciated!

**Comment by KevinMusgrave** [comment]
As mentioned in the pull request, I think this is equivalent to NTXentLoss with a customized reducer:

```python
from pytorch_metric_learning.losses import NTXentLoss
from pytorch_metric_learning.reducers import AvgNonZeroReducer, PerAnchorReducer

loss_fn = NTXentLoss(reducer=PerAnchorReducer(AvgNonZeroReducer()))
```
