### ISSUE TITLE
where() missing 2 required positional argument: "input", "other"

### ISSUE THREAD

**Issue by qianjinhao** [KevinMusgrave/pytorch-metric-learning#67]
my pytorch version is 1.1.0 and I have this bug.
/pytorch_metric_learning/miners/batch_hard_miner.py", line 24, in mine
    a_keep_idx = torch.where(a1p_keep & a2n_keep)
TypeError: where() missing 2 required positional argument: "input", "other"

**Comment by KevinMusgrave** [comment]
It looks like torch.where changed in pytorch v1.2.0. Can you try upgrading?

**Comment by KevinMusgrave** [comment]
Closing for now, please reopen if you still have issues
