### ISSUE TITLE
While updating conda(installing current version), I found some erros, how to solve it? 

### ISSUE THREAD

**Issue by SC-PIONEER** [KevinMusgrave/pytorch-metric-learning#674]
>> conda install conda=23.10.0

Result 

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31

Note that strict channel priority may have removed packages required for satisfiability.

**Comment by KevinMusgrave** [comment]
I don't have any suggestions, but here are some people having a similar problem:

- https://stackoverflow.com/questions/71678461/conda-unsatisfiableerror-with-linux64-and-glibc
- https://github.com/conda/conda/issues/12912

You could also try using pip within your conda environment:

```
conda install pip
pip install pytorch-metric-learning
```

**Comment by KevinMusgrave** [comment]
Let me know if you're still having trouble with this.
