### ISSUE TITLE
Got <class 'NoneType'>, but numpy array, torch tensor, or caffe2 blob name are expected.

### ISSUE THREAD

**Issue by Chen94yue** [KevinMusgrave/pytorch-metric-learning#73]
Hi, 
    This error occurs when testing after one epoch.  
Traceback (most recent call last):
  File "main.py", line 116, in <module>
    main(cfg)
  File "main.py", line 96, in main
    trainer.train(num_epochs=cfg.SOLVER.EPOCH)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_metric_learning/trainers/base_trainer.py", line 88, in train
    if self.end_of_epoch_hook(self) is False:
  File "/opt/conda/lib/python3.6/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 51, in actual_hook
    best_epoch = self.save_models_and_eval(trainer, dataset_dict, model_folder, test_interval, tester, test_collate_fn)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 96, in save_models_and_eval
    tester.test(dataset_dict, epoch, trainer.models["trunk"], trainer.models["embedder"], list(dataset_dict.keys()), collate_fn)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_metric_learning/testers/base_tester.py", line 205, in test
    self.end_of_testing_hook(self) if self.end_of_testing_hook else logging.info(self.all_accuracies)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_metric_learning/utils/logging_presets.py", line 64, in end_of_testing_hook
    self.record_keeper.update_records(best, epoch, input_group_name_for_non_objects=self.record_group_name(tester, split_name))
  File "/opt/conda/lib/python3.6/site-packages/record_keeper/record_keeper.py", line 39, in update_records
    self.append_data(group_name, name_in_dict, input_obj, global_iteration)
  File "/opt/conda/lib/python3.6/site-packages/record_keeper/record_keeper.py", line 29, in append_data
    self.tensorboard_writer.add_scalar(tag_name, value, iteration)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 295, in add_scalar
    scalar(tag, scalar_value), global_step, walltime)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/tensorboard/summary.py", line 91, in scalar
    scalar = make_np(scalar)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/tensorboard/_convert_np.py", line 32, in make_np
    'Got {}, but numpy array, torch tensor, or caffe2 blob name are expected.'.format(type(x)))
NotImplementedError: Got <class 'NoneType'>, but numpy array, torch tensor, or caffe2 blob name are expected.

My code is:
![image](https://user-images.githubusercontent.com/34304578/80479081-12f42c80-8981-11ea-8c11-4f5bb909d3d5.png)

**Comment by KevinMusgrave** [comment]
Can you let me know which version of pytorch-metric-learning and record-keeper you're using?

**Comment by Chen94yue** [comment]
faiss-gpu                 1.6.3            
pytorch                   1.2.0           
pytorch-metric-learning   0.9.84           
torchvision               0.4.0            
record-keeper             0.9.24

**Comment by KevinMusgrave** [comment]
@Chen94yue Thanks, I think I know what the bug is. I'll try to work on this later today and upload a new version to pip.

**Comment by KevinMusgrave** [comment]
@Chen94yue Can you try ```pip install pytorch-metric-learning==0.9.85.dev0``` and let me know if the same bug occurs.

**Comment by Chen94yue** [comment]
thx, my bug fixed.

**Comment by Chen94yue** [comment]
Is this training result right? Why some value is nan:

epoch,AMI_level0,NMI_level0,mean_average_precision_at_r_level0,precision_at_1_level0,r_precision_level0,best_epoch,best_accuracy
1,0.03571634389980823,0.9380670339206018,nan,0.05411392405063291,nan,1,nan
2,0.04971500775107919,0.9391037759803879,nan,0.07361550632911393,nan,2,nan
3,0.05644224460528958,0.9395244619237163,nan,0.08536392405063291,nan,3,nan
4,0.06051057625383018,0.9398136875135318,nan,0.0939873417721519,nan,4,nan
5,0.06405937464798545,0.9400855015944669,nan,0.1002373417721519,nan,5,nan

The training log for one epoch is:
INFO:root:TRAINING EPOCH 4
total_loss=0.39131: 100%|#############################################################################################################################################################################| 4532/4532 [1:01:33<00:00,  1.32it/s]
INFO:root:Evaluating epoch 4
INFO:root:Getting embeddings for the val split
100%|#####################################################################################################################################################################################################| 790/790 [04:09<00:00,  3.77it/s]
INFO:root:Running UMAP on the val set
INFO:root:Finished UMAP
INFO:root:UMAP plot for the val split and label set UMAP_level0
INFO:root:Computing accuracy for the val split
INFO:root:running k-nn with k=2
INFO:root:embedding dimensionality is 512
INFO:root:running k-means clustering with k=15060
INFO:root:embedding dimensionality is 512
WARNING clustering 25280 points to 15060 centroids: please provide at least 587340 training points
/opt/conda/lib/python3.6/site-packages/pytorch_metric_learning/utils/accuracy_calculator.py:33: RuntimeWarning: divide by zero encountered in true_divide
  return np.mean(summed_precision_per_row / max_possible_matches_per_row)
/opt/conda/lib/python3.6/site-packages/pytorch_metric_learning/utils/accuracy_calculator.py:33: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(summed_precision_per_row / max_possible_matches_per_row)
/opt/conda/lib/python3.6/site-packages/pytorch_metric_learning/utils/accuracy_calculator.py:22: RuntimeWarning: divide by zero encountered in true_divide
  return np.mean(matches_per_row / max_possible_matches_per_row)
/opt/conda/lib/python3.6/site-packages/pytorch_metric_learning/utils/accuracy_calculator.py:22: RuntimeWarning: invalid value encountered in true_divide
  return np.mean(matches_per_row / max_possible_matches_per_row)
INFO:root:New best accuracy!

**Comment by KevinMusgrave** [comment]
This is occurring because ```mean_average_precision_at_r``` and ```r_precision``` are expecting each sample to have at least 1 other sample of the same class in the dataset. If there are 0 other samples of the same class, then a division by 0 occurs. In contrast, ```precision_at_1``` will just give those samples a score of 0. 

I think the best solution is to make ```mean_average_precision_at_r``` and ```r_precision``` ignore samples that are the only one of their kind. I'll make a separate issue to fix this.

**Comment by KevinMusgrave** [comment]
In the meantime (before I fix this issue), you can use one of the other metrics as the "primary metric" for keeping track of the best model. 

```python
hooks = logging_presets.get_hook_container(record_keeper, primary_metric="AMI")
```

**Comment by KevinMusgrave** [comment]
By the way, if you want to load models to resume training, you can try using [this function](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/src/pytorch_metric_learning/utils/logging_presets.py#L77) like this:

```python
# after you initialize the trainer
# also I think your models have to not be wrapped in dataparallel, but I may be wrong
start_epoch = hooks.load_latest_saved_models(trainer, model_folder, device)

# set to dataparallel
for k, v in self.models.items():
    models[k] = torch.nn.DataParallel(v)

# trainer.train(start_epoch, num_epochs)
```

**Comment by Chen94yue** [comment]
Thanks! 😊

**Comment by KevinMusgrave** [comment]
The latest version (0.9.85) fixes the NaN bug.
