### ISSUE TITLE
the question of DistributedLossWrapper

### ISSUE THREAD

**Issue by hukongzhi** [KevinMusgrave/pytorch-metric-learning#732]
![image](https://github.com/user-attachments/assets/d30d8666-7d11-4c52-815f-7681d552405a)
I want to know about the red line part. In the case of efficient=False, we collect the results on multiple GPUs, and then calculate the loss together. Why does the total loss need to be multiplied by the number of GPUs in the end?

**Comment by hukongzhi** [comment]
Looking forward to your reply.

**Comment by KevinMusgrave** [comment]
I can't remember the specific reason. Here are previous discussions on the scaling:

- https://github.com/KevinMusgrave/pytorch-metric-learning/issues/562
- https://github.com/KevinMusgrave/pytorch-metric-learning/issues/10#issuecomment-835461731

**Comment by hukongzhi** [comment]
I see. Thank you very much.
