### ISSUE TITLE
TwoStreamMetricLoss: shifting indices only works for triplets

### ISSUE THREAD

**Issue by KevinMusgrave** [KevinMusgrave/pytorch-metric-learning#86]
@marijnl This might interest you. If you pass in a pair miner, the indices won't be shifted properly.

**Comment by marijnl** [comment]
Thanks I'll look into it tomorrow

**Comment by KevinMusgrave** [comment]
This logic from CrossBatchMemory should work:
```python
    def shift_indices_tuple(self, indices_tuple, batch_size):
        if len(indices_tuple) == 3:
            indices_tuple = (indices_tuple[0],) + tuple([x+batch_size if len(x) > 0 else x for x in indices_tuple[1:]])
        elif len(indices_tuple) == 4:
            indices_tuple = tuple([x+batch_size if len(x) > 0 and i%2==1 else x for i,x in enumerate(indices_tuple)])
        return indices_tuple
```
Actually, it might make sense to move this to utils/common_functions

**Comment by marijnl** [comment]
Thanks for the pointer. If you don't mind I'll open a new pull request for this bug where I move this logic into common_functions and adapt crossbatch and twostream

**Comment by KevinMusgrave** [comment]
@marijnl That would be great!
